ALTER TABLE RankingStats
ADD IF NOT EXISTS IVRoi FLOAT DEFAULT 0;

ALTER TABLE RankingStatsByTrk
ADD IF NOT EXISTS IVRoi FLOAT DEFAULT 0;

ALTER TABLE FinalOrder
ADD IF NOT EXISTS IVRoi FLOAT DEFAULT 0;


--ALTER TABLE FinalOrder
--REDEFINE IF EXISTS TotalWinOdds FLOAT;


ALTER TABLE RankingStats
ADD IF NOT EXISTS AvgWinOddsProbability FLOAT DEFAULT 0;

ALTER TABLE RankingStats
ADD IF NOT EXISTS AvgOddsProbability FLOAT DEFAULT 0;

ALTER TABLE RankingStatsByTrk
ADD IF NOT EXISTS AvgWinOddsProbability FLOAT DEFAULT 0;

ALTER TABLE RankingStatsByTrk
ADD IF NOT EXISTS AvgOddsProbability FLOAT DEFAULT 0;
