del *.ovl
del *.pdf
del *.dsm
del _qs*.db
del *.obj
del *.i*
del *.exe
del *.map
del *.~h*
del *.~df
del *.~cp
del *.~ba
del *.~ma
del *.tds
del *.~pas
del *.~pa
del *.~dfm
del *.~*


del save\_qs*.db
del save\*.obj
del save\*.i*
del save\topsire.exe
del save\*.~h*
del save\*.~df
del save\*.~cp
del save\*.~ba
del save\*.~ma
del save\*.tds

del genkey\_qs*.db
del genkey\*.obj
del genkey\*.i*
del genkey\topsire.exe
del genkey\*.~h*
del genkey\*.~df
del genkey\*.~cp
del genkey\*.~ba
del genkey\*.~ma
del genkey\*.tds
del genkey\*.exe

del data\*.ibk
del data\*.bbk
del data\*.dbk



