d:
cd \ratings31
pause
del ??.txt
del ???.txt
del *.txt
del r.1
del r.2
del *.bak /s
del *.old /s
del *.dat
del *.idx
del *.ovl
del *.pdf
del *.dsm
del _qs*.db
del *.obj /s
del *.i* /s
rem del *.exe
del *.map
del *.~h*  /s
del *.~df /s
del *.~cp /s
del *.~ba /s
del *.~ma /s
del *.tds
del *.~pas /s
del *.~pa /s
del *.~dfm /s
del *.~* /s
del *.dcu /s

del log\*.log
del log\*.bak
del save\_qs*.db
del save\*.obj
del save\*.i*
del save\topsire.exe
del save\*.~h*
del save\*.~df
del save\*.~cp
del save\*.~ba
del save\*.~ma
del save\*.tds

del genkey\_qs*.db
del genkey\*.obj
del genkey\*.i*
del genkey\topsire.exe
del genkey\*.~h*
del genkey\*.~df
del genkey\*.~cp
del genkey\*.~ba
del genkey\*.~ma
del genkey\*.tds
del genkey\*.exe

del data\*.ibk
del data\*.bbk
del data\*.dbk



