/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "HorseHistory"
(
   "TrkCode" VARCHAR(3) NOT NULL DEFAULT '0',
   "RaceDate" DATE NOT NULL,
   "RaceNbr" SMALLINT NOT NULL,
   "PostPos" SMALLINT NOT NULL,
   "RangeRaceDate" DATE,
   "RaceType" VARCHAR(10),
   "TypeOfRace" VARCHAR(1) DEFAULT 'T',
   "Surface" VARCHAR(1) DEFAULT 'D',
   "TrkCond" VARCHAR(2) DEFAULT 'FT',
   "DistanceInFurlongs" FLOAT DEFAULT 0,
   "Purse" FLOAT DEFAULT 0,
   "ClaimingPrice" FLOAT DEFAULT 0,
   "ProgramNbr" VARCHAR(10),
   "ProgNbrSort" SMALLINT DEFAULT 0,
   "MorningLineDesc" VARCHAR(6),
   "MorningLineTo1" FLOAT DEFAULT 0,
   "MorningLineTo1Rank" SMALLINT DEFAULT 0,
   "FinishPos" SMALLINT DEFAULT 0,
   "Odds" FLOAT DEFAULT 0,
   "IsFavorite" BOOLEAN DEFAULT False,
   "HorseName" VARCHAR(25),
   "HorseNbr" SMALLINT DEFAULT 0,
   "Sex" VARCHAR(1),
   "Age" SMALLINT DEFAULT 0,
   "Equip" VARCHAR(10),
   "Med" VARCHAR(5),
   "IsFirstTimeJuice" BOOLEAN DEFAULT False,
   "IsSecondTimeJuice" BOOLEAN DEFAULT False,
   "IsDebut" BOOLEAN DEFAULT False,
   "IsDebutTwo" BOOLEAN DEFAULT False,
   "IsTurfDebut" BOOLEAN DEFAULT False,
   "DebutIndicator" VARCHAR(2),
   "TurfIndicator" VARCHAR(2),
   "MudIndicator" VARCHAR(2),
   "RouteIndicator" VARCHAR(2),
   "IsClaimed1Back" BOOLEAN DEFAULT False,
   "IsClaimed2Back" BOOLEAN DEFAULT False,
   "IsDirtToTurf" BOOLEAN DEFAULT False,
   "IsTurfToDirt" BOOLEAN DEFAULT False,
   "IsSprToRte" BOOLEAN DEFAULT False,
   "IsRteToSpr" BOOLEAN DEFAULT False,
   "DaysLast" SMALLINT DEFAULT 0,
   "DaysLastWork" SMALLINT DEFAULT 0,
   "DaysLastWork2" SMALLINT DEFAULT 0,
   "DaysLastWork3" SMALLINT DEFAULT 0,
   "NbrWorksLast" SMALLINT DEFAULT 0,
   "StartsWorks21" SMALLINT DEFAULT 0,
   "JkyEquibaseKey" VARCHAR(10),
   "TrnEquibaseKey" VARCHAR(10),
   "SireName" VARCHAR(16),
   "DamSireName" VARCHAR(16),
   "DamName" VARCHAR(25),
   "BredIn" VARCHAR(6),
   "Owner" VARCHAR(45),
   "Breeder" VARCHAR(67),
   "TrnTodayWinPct" FLOAT DEFAULT 0,
   "TrnTodayWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnTurfWinPct" FLOAT DEFAULT 0,
   "TotalTrnTurfWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnWinPct" FLOAT DEFAULT 0,
   "TotalTrnWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnJkyWinPct" FLOAT DEFAULT 0,
   "TotalTrnJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyWinPct" FLOAT DEFAULT 0,
   "TotalJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnOwnWinPct" FLOAT DEFAULT 0,
   "TotalTrnOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalOwnWinPct" FLOAT DEFAULT 0,
   "TotalOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalBrdWinPct" FLOAT DEFAULT 0,
   "TotalBrdWinPctRank" SMALLINT DEFAULT 0,
   "LastSpeed" SMALLINT DEFAULT 0,
   "LastSpeedRank" SMALLINT DEFAULT 0,
   "Power" FLOAT DEFAULT 0,
   "PowerRank" SMALLINT DEFAULT 0,
   "BackSpeed" SMALLINT DEFAULT 0,
   "BackSpeedRank" SMALLINT DEFAULT 0,
   "EarlyPace" FLOAT DEFAULT 0,
   "EarlyPaceRank" SMALLINT DEFAULT 0,
   "EarlyPacePos" FLOAT DEFAULT 9999,
   "EarlyPacePosRank" SMALLINT DEFAULT 0,
   "MiddlePace" FLOAT DEFAULT 0,
   "MiddlePaceRank" SMALLINT DEFAULT 0,
   "MiddlePacePos" FLOAT DEFAULT 9999,
   "MiddlePacePosRank" SMALLINT DEFAULT 0,
   "LatePace" FLOAT DEFAULT 0,
   "LatePaceRank" SMALLINT DEFAULT 0,
   "LatePacePos" FLOAT DEFAULT 9999,
   "LatePacePosRank" SMALLINT DEFAULT 0,
   "FinishPacePos" FLOAT DEFAULT 0,
   "FinishPacePosRank" SMALLINT DEFAULT 0,
   "AvgClass" FLOAT DEFAULT 0,
   "AvgClassRank" SMALLINT DEFAULT 0,
   "MorningLineTo1Fair" FLOAT DEFAULT 0,
   "MorningLineTo1FairProbability" FLOAT DEFAULT 0,
   "FinalOrderKey" VARCHAR(50) DEFAULT '0',
   "FinalWinPct" FLOAT DEFAULT 0,
   "FinalWinPctRank" SMALLINT DEFAULT 0,
   "FinalValueBet" FLOAT DEFAULT 0,
   "PrimaryOrderKey" VARCHAR(50),
   "PrimaryWinPct" FLOAT DEFAULT 0,
   "PrimaryWinPctRank" SMALLINT DEFAULT 0,
   "PrimaryValueBet" FLOAT DEFAULT 0,
   "SecondaryOrderKey" VARCHAR(50),
   "SecondaryWinPct" FLOAT DEFAULT 0,
   "SecondaryWinPctRank" SMALLINT DEFAULT 0,
   "SecondaryValueBet" FLOAT DEFAULT 0,
   "DefaultOrderKey" VARCHAR(50),
   "DefaultWinPct" FLOAT DEFAULT 0,
   "DefaultWinPctRank" SMALLINT DEFAULT 0,
   "DefaultValueBet" FLOAT DEFAULT 0,
   "DamAllWinPct" FLOAT DEFAULT 0,
   "DamAllWinPctRank" SMALLINT DEFAULT 0,
   "DamAllTurfWinPct" FLOAT DEFAULT 0,
   "DamAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "DamAllMudWinPct" FLOAT DEFAULT 0,
   "DamAllMudWinPctRank" SMALLINT DEFAULT 0,
   "SireAllWinPct" FLOAT DEFAULT 0,
   "SireAllWinPctRank" SMALLINT DEFAULT 0,
   "SireAllTurfWinPct" FLOAT DEFAULT 0,
   "SireAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "SireAllMudWinPct" FLOAT DEFAULT 0,
   "SireAllMudWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllWinPct" FLOAT DEFAULT 0,
   "DamSireAllWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllTurfWinPct" FLOAT DEFAULT 0,
   "DamSireAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllMudWinPct" FLOAT DEFAULT 0,
   "DamSireAllMudWinPctRank" SMALLINT DEFAULT 0,
   "AvgSpeed" SMALLINT DEFAULT 0,
   "AvgSpeedRank" SMALLINT DEFAULT 0,
   "AvgClassRating" SMALLINT DEFAULT 0,
   "AvgClassRatingRank" SMALLINT DEFAULT 0,
   "BackClass" SMALLINT DEFAULT 0,
   "BackClassRank" SMALLINT DEFAULT 0,
   "CurrClass" SMALLINT DEFAULT 0,
   "CurrClassRank" SMALLINT DEFAULT 0,
   "TotalTrn2yoWinPct" FLOAT DEFAULT 0,
   "TotalTrn2yoWinPctRank" SMALLINT DEFAULT 0,
   "TrnTrackRank" SMALLINT DEFAULT 0,
   "JkyTrackRank" SMALLINT DEFAULT 0,
   "TrnWinsRank" SMALLINT DEFAULT 0,
   "TrnEarningsRank" SMALLINT DEFAULT 0,
   "JkyWinsRank" SMALLINT DEFAULT 0,
   "JkyEarningsRank" SMALLINT DEFAULT 0,
   "OwnWinsRank" SMALLINT DEFAULT 0,
   "OwnEarningsRank" SMALLINT DEFAULT 0,
   "Sire2yoWinPct" FLOAT DEFAULT 0,
   "Sire2yoWinPctRank" SMALLINT DEFAULT 0,
   "Dam2yoWinPct" FLOAT DEFAULT 0,
   "Dam2yoWinPctRank" SMALLINT DEFAULT 0,
   "DamDebutWinPct" FLOAT DEFAULT 0,
   "TotalTrnFavWinPct" SMALLINT DEFAULT 0,
   "IsDollar" BOOLEAN DEFAULT False,
   "IsDoubleDollar" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner0" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner1" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner2" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner3" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner0" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner1" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner2" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner3" BOOLEAN DEFAULT False,
   "IsTripleLiner0" BOOLEAN DEFAULT False,
   "IsTripleLiner1" BOOLEAN DEFAULT False,
   "IsTripleLiner2" BOOLEAN DEFAULT False,
   "IsTripleLiner3" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner" BOOLEAN DEFAULT False,
   "IsTripleDot" BOOLEAN DEFAULT False,
   "IsFrontDoubleDot" BOOLEAN DEFAULT False,
   "IsBackDoubleDot" BOOLEAN DEFAULT False,
   "IsTripleLiner" BOOLEAN DEFAULT False,
   "IsWagerSheetSelected" BOOLEAN DEFAULT False,
   "IsPrintedOnValueSheet" BOOLEAN DEFAULT False,
   "IsLinerSheetSelected" BOOLEAN DEFAULT False,
   "IsYouBetTrack" BOOLEAN DEFAULT True,
   "IsLayoffAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndDown" BOOLEAN DEFAULT False,
   "IsFirstTimeClaiming" BOOLEAN DEFAULT False,
   "IsBelowClaimedPrice" BOOLEAN DEFAULT False,
   "TrnTurfToDirtWinPct" SMALLINT DEFAULT 0,
   "TrnDirtToTurfWinPct" SMALLINT DEFAULT 0,
   "TrnRteToSprWinPct" SMALLINT DEFAULT 0,
   "TrnSprToRteWinPct" SMALLINT DEFAULT 0,
   "TotalTrnDebutWinPct" SMALLINT DEFAULT 0,
   "TotalTrnDebutTwoWinPct" SMALLINT DEFAULT 0,
   "TotalTrn120PlusWinPct" SMALLINT DEFAULT 0,
   "TotalTrnWork120PlusWinPct" SMALLINT DEFAULT 0,
   "TotalTrnAftClmWinPct" SMALLINT DEFAULT 0,
   "TotalTrnFirstJuiceWinPct" SMALLINT DEFAULT 0,
   "TotalTrnSecondJuiceWinPct" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOnWinPct" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOffWinPct" SMALLINT DEFAULT 0,
   "TotalTrnClaimed1BackWinPct" SMALLINT DEFAULT 0,
   "TotalTrnClaimed2BackWinPct" SMALLINT DEFAULT 0,
   "LastTrkCode" VARCHAR(3),
   "LastRaceNbr" SMALLINT DEFAULT 0,
   "LastRaceDate" DATE,
   "LastPostPos" SMALLINT DEFAULT 0,
   "LastRaceType" VARCHAR(6),
   "LastDistance" FLOAT DEFAULT 0,
   "LastSurf" VARCHAR(1) DEFAULT 'D',
   "LastClaimed" VARCHAR(1) DEFAULT 'False',
   "LastClmPrice" FLOAT DEFAULT 0,
   "LastPurse" FLOAT DEFAULT 0,
   "LastOdds" FLOAT DEFAULT 0,
   "LastFinishPos" SMALLINT DEFAULT 0,
   "LastFavoriteIndicator" VARCHAR(1),
   "LastTrkCond" VARCHAR(2) DEFAULT 'FT',
   "AngleDesc" VARCHAR(100),
   "RouteStarts" SMALLINT DEFAULT 0,
   "SprintStarts" SMALLINT DEFAULT 0,
   "IsBlinkersOn" BOOLEAN DEFAULT False,
   "IsBlinkersOff" BOOLEAN DEFAULT False,
   "LastEquip" VARCHAR(7),
   "EstTimeOfRace" TIME,
   "EstTimeOfFirstRace" TIME,
   "NbrDebutStarters" SMALLINT,
   "AvgPurse" FLOAT DEFAULT 0,
   "Entry" VARCHAR(5),
   "ProgramNbrSort" SMALLINT,
   "IsScratched" BOOLEAN DEFAULT False,
   "Color" VARCHAR(10),
   "Weight" SMALLINT,
   "Trainer" VARCHAR(30),
   "Jockey" VARCHAR(25),
   "TotalTrn1To45WinPct" FLOAT DEFAULT 0,
   "TotalTrnWork1To45WinPct" FLOAT DEFAULT 0,
   "TotalTrn2oWinPctRank" SMALLINT DEFAULT 0,
   "TrnStkWinPct" SMALLINT DEFAULT 0,
   "TrnClmWinPct" SMALLINT DEFAULT 0,
   "TrnMdnWinPct" SMALLINT DEFAULT 0,
   "TrnAlwWinPct" SMALLINT DEFAULT 0,
   "TotalJkyTurfWinPct" FLOAT DEFAULT 0,
   "Sire" VARCHAR(16),
   "SireTurfLastYearRank" SMALLINT DEFAULT 0,
   "SireTurfLastYearStarts" SMALLINT DEFAULT 0,
   "SireGeneralLastYearRank" SMALLINT DEFAULT 0,
   "SireJuvenileLastYearRank" SMALLINT DEFAULT 0,
   "SireTurfThisYearRank" SMALLINT DEFAULT 0,
   "SireTurfThisYearStarts" SMALLINT DEFAULT 0,
   "SireGeneralThisYearRank" SMALLINT DEFAULT 0,
   "SireJuvenileThisYearRank" SMALLINT DEFAULT 0,
   "Dam" VARCHAR(16),
   "DamSire" VARCHAR(16),
   "LastBL" FLOAT DEFAULT 0,
   "LastDQIndicator" VARCHAR(1),
   "LastClassRating" SMALLINT DEFAULT 0,
   "LastDay" VARCHAR(2),
   "LastMonthDesc" VARCHAR(3),
   "LastYear" VARCHAR(4),
   "LastCall1st" FLOAT,
   "LastCall2nd" FLOAT,
   "LastCall3rd" FLOAT,
   "LastFinCall" FLOAT,
   "LastGateBreak" VARCHAR(2),
   "LastLen1Back" VARCHAR(7),
   "LastLen2Back" VARCHAR(7),
   "LastStLenBack" VARCHAR(7),
   "LastFinishBeaten" VARCHAR(7),
   "LastWeight" SMALLINT,
   "LastTrackVariant" SMALLINT,
   "LastClass" FLOAT,
   "LastHorseTime" FLOAT,
   "LastWinTime" FLOAT,
   "LastSRWinner" SMALLINT,
   "Last2TrkCode" VARCHAR(3),
   "Last2RaceNbr" INTEGER DEFAULT 0,
   "Last2RaceDate" DATE,
   "Last2PostPos" SMALLINT DEFAULT 0,
   "Last2RaceType" VARCHAR(6),
   "Last2Surf" VARCHAR(1),
   "Last2Distance" FLOAT DEFAULT 0,
   "Last2FinishPos" SMALLINT DEFAULT 0,
   "Last2BL" FLOAT DEFAULT 0,
   "Last2Odds" FLOAT DEFAULT 0,
   "Last2FavoriteIndicator" VARCHAR(1),
   "Last2DQIndicator" VARCHAR(1),
   "Last2TrkCond" VARCHAR(2),
   "Last2ClmPrice" FLOAT DEFAULT 0,
   "Last2Claimed" VARCHAR(1),
   "Last2Purse" FLOAT DEFAULT 0,
   "Last2ClassRating" SMALLINT DEFAULT 0,
   "Last2Day" VARCHAR(2),
   "Last2MonthDesc" VARCHAR(3),
   "Last2Year" VARCHAR(4),
   "Last2Call1st" FLOAT,
   "Last2Call2nd" FLOAT,
   "Last2Call3rd" FLOAT,
   "Last2FinCall" FLOAT,
   "Last2GateBreak" VARCHAR(2),
   "Last2Len1Back" VARCHAR(7),
   "Last2Len2Back" VARCHAR(7),
   "Last2StLenBack" VARCHAR(7),
   "Last2FinishBeaten" VARCHAR(7),
   "Last2Equip" VARCHAR(7),
   "Last2Weight" VARCHAR(3),
   "Last2TrackVariant" SMALLINT,
   "Last2Class" FLOAT,
   "Last2HorseTime" FLOAT,
   "Last2WinTime" FLOAT,
   "Last2SRWinner" FLOAT,
   "Last3TrkCode" VARCHAR(3),
   "Last3RaceNbr" INTEGER DEFAULT 0,
   "Last3RaceDate" DATE,
   "Last3PostPos" SMALLINT DEFAULT 0,
   "Last3RaceType" VARCHAR(6),
   "Last3Surf" VARCHAR(1),
   "Last3Distance" FLOAT DEFAULT 0,
   "Last3FinishPos" SMALLINT DEFAULT 0,
   "Last3BL" FLOAT DEFAULT 0,
   "Last3Odds" FLOAT DEFAULT 0,
   "Last3FavoriteIndicator" VARCHAR(1),
   "Last3DQIndicator" VARCHAR(1),
   "Last3TrkCond" VARCHAR(2),
   "Last3ClmPrice" FLOAT DEFAULT 0,
   "Last3Claimed" VARCHAR(1),
   "Last3Purse" FLOAT DEFAULT 0,
   "Last3ClassRating" SMALLINT DEFAULT 0,
   "Last3Day" VARCHAR(2),
   "Last3MonthDesc" VARCHAR(3),
   "Last3Year" VARCHAR(4),
   "Last3Call1st" VARCHAR(7),
   "Last3Call2nd" VARCHAR(7),
   "Last3Call3rd" VARCHAR(7),
   "Last3FinCall" VARCHAR(7),
   "Last3GateBreak" VARCHAR(2),
   "Last3Len1Back" VARCHAR(7),
   "Last3Len2Back" VARCHAR(7),
   "Last3StLenBack" VARCHAR(7),
   "Last3FinishBeaten" VARCHAR(7),
   "Last3Equip" VARCHAR(7),
   "Last3Weight" VARCHAR(10),
   "Last3TrackVariant" VARCHAR(3),
   "Last3Class" FLOAT,
   "Last3HorseTime" FLOAT,
   "Last3WinTime" FLOAT,
   "Last3SRWinner" SMALLINT,
   "EstMorningLineOrderKey" VARCHAR(50),
   "EstMorningLineWinPct" FLOAT DEFAULT 0,
   "EstMorningLineWinPctRank" SMALLINT DEFAULT 0,
   "EstMorningLineValueBet" FLOAT DEFAULT 0,
   "DamDebutWinPctRank" SMALLINT DEFAULT 0,
   "SireDebutWinPct" SMALLINT DEFAULT 0,
   "SireDebutWinPctRank" SMALLINT DEFAULT 0,
   "SireTrfRteWinPct" SMALLINT DEFAULT 0,
   "SireTrfRteWinPctRank" SMALLINT DEFAULT 0,
   "SireDirtSprWinPct" SMALLINT DEFAULT 0,
   "SireDirtSprWinPctRank" SMALLINT DEFAULT 0,
   "SireDirtRteWinPct" SMALLINT DEFAULT 0,
   "SireDirtRteWinPctRank" SMALLINT DEFAULT 0,
   "EarlyPaceAdvantage" FLOAT DEFAULT 0,
   "MiddlePaceAdvantage" FLOAT DEFAULT 0,
   "LatePaceAdvantage" FLOAT DEFAULT 0,
   "LifeStarts" SMALLINT DEFAULT 0,
   "LifeWins" SMALLINT DEFAULT 0,
   "LifeEPS" INTEGER DEFAULT 0,
   "TurfStarts" SMALLINT DEFAULT 0,
   "TurfWins" SMALLINT DEFAULT 0,
   "TurfEarnings" INTEGER DEFAULT 0,
   "TurfEPS" INTEGER DEFAULT 0,
   "MudStarts" SMALLINT DEFAULT 0,
   "MudWins" SMALLINT DEFAULT 0,
   "MudEPS" INTEGER DEFAULT 0,
   "TrkStarts" SMALLINT DEFAULT 0,
   "TrkWins" SMALLINT DEFAULT 0,
   "TrkEPS" INTEGER DEFAULT 0,
   "RouteWins" SMALLINT DEFAULT 0,
   "SprintWins" SMALLINT DEFAULT 0,
   "IsPrintedOnAngleSheet" BOOLEAN DEFAULT False,
   "TodaysWagerOrderKey" VARCHAR(50),
   "TotalTrn46To120WinPct" FLOAT,
   "TotalTrnWork46To120WinPct" FLOAT,
   "QSP" FLOAT,
   "QSPRank" SMALLINT,
   "KSP" FLOAT,
   "KSPRank" SMALLINT,
   "QSPRunStyle" VARCHAR(1),
PRIMARY KEY ("TrkCode","RaceDate","RaceNbr","PostPos") COMPRESS FULL
DESCRIPTION 'Horse History'
LOCALE CODE 0
USER MAJOR VERSION 4
);

CREATE INDEX IF NOT EXISTS "ByRaceDate" ON "HorseHistory" ("RangeRaceDate","RaceDate") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByHorseName" ON "HorseHistory" ("RangeRaceDate","HorseName") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByFinalWinPctRank" ON "HorseHistory" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","FinalWinPct" DESC) COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByProgramNbr" ON "HorseHistory" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","ProgramNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByRaceDateTrkCode" ON "HorseHistory" ("RangeRaceDate","RaceDate","TrkCode","RaceNbr","PostPos") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByRangeRaceDate" ON "HorseHistory" ("RangeRaceDate","RaceDate","TrkCode","RaceDate","RaceNbr","PostPos") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByPrimaryWinPctRank" ON "HorseHistory" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","PrimaryWinPct" DESC) COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "BySecondaryWinPctRank" ON "HorseHistory" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","SecondaryWinPct" DESC) COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByDefaultWinPctRank" ON "HorseHistory" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","DefaultWinPct" DESC) COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByOdds" ON "HorseHistory" ("RangeRaceDate","Odds") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByFinishPos" ON "HorseHistory" ("RangeRaceDate","FinishPos") COMPRESS FULL;
