/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "PP"
(
   "TrkCode" VARCHAR(3) NOT NULL,
   "RaceDate" DATE NOT NULL,
   "HorseNbr" SMALLINT NOT NULL,
   "PPNbr" SMALLINT,
   "HHTrkCode" VARCHAR(3),
   "HHRaceDate" DATE,
   "HHRaceNbr" SMALLINT,
   "HHPostPos" SMALLINT,
   "Top3Finishers" VARCHAR(75),
   "RaceDesc" VARCHAR(250),
   "Comment2" VARCHAR(75),
   "RunningLine" VARCHAR(75),
   "FractionsLine" VARCHAR(75),
   "TrackLine" VARCHAR(75),
   "OddsLine" VARCHAR(75),
   "ExtraLine" VARCHAR(75),
   "ClassLine" VARCHAR(75),
   "Day" VARCHAR(2),
   "MonthDesc" VARCHAR(3),
   "Year" VARCHAR(4),
   "DateOfRace" DATE,
   "DaysFromTodaysRace" INTEGER,
   "RaceNbr" VARCHAR(2),
   "TrkAbbr" VARCHAR(3),
   "Surf" VARCHAR(1),
   "TrkCond" VARCHAR(2),
   "DistanceDesc" VARCHAR(10),
   "Call1st" FLOAT,
   "Call2nd" FLOAT,
   "Call3rd" FLOAT,
   "FinCall" FLOAT,
   "RaceType" VARCHAR(3),
   "ClmPrice" INTEGER,
   "Claimed" VARCHAR(1),
   "Purse" INTEGER,
   "RaceConditions" VARCHAR(15),
   "Speed" INTEGER DEFAULT 0,
   "PostPos" INTEGER,
   "GateBreak" VARCHAR(2),
   "Len1Back" VARCHAR(7),
   "EarlyPacePos" FLOAT,
   "Len2Back" VARCHAR(7),
   "MiddlePacePos" FLOAT,
   "StLenBack" VARCHAR(7),
   "LatePacePos" FLOAT,
   "FinishPacePos" FLOAT,
   "EarlyPace" FLOAT,
   "MiddlePace" FLOAT,
   "LatePace" FLOAT,
   "DQIndicator" VARCHAR(1),
   "FinishBeaten" VARCHAR(7),
   "Jockey" VARCHAR(15),
   "Equip" VARCHAR(7),
   "Weight" INTEGER,
   "Odds" FLOAT,
   "FavoriteIndicator" VARCHAR(1),
   "TrackVariant" INTEGER,
   "Class" INTEGER DEFAULT 0,
   "HorseTime" FLOAT,
   "WinTime" FLOAT,
   "SRWinner" INTEGER,
   "FldSize" SMALLINT,
PRIMARY KEY ("TrkCode","RaceDate","HorseNbr","PPNbr") COMPRESS FULL
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE INDEX IF NOT EXISTS "ByReportKey" ON "PP" ("TrkCode","RaceDate","HorseNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByHHKey" ON "PP" ("HHTrkCode","HHRaceDate","HHRaceNbr","HHPostPos","PPNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByBackClass" ON "PP" ("HHTrkCode","HHRaceDate","HHRaceNbr","HHPostPos","Class" DESC) COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByBackSpeed" ON "PP" ("HHTrkCode","HHRaceDate","HHRaceNbr","HHPostPos","Speed" DESC) COMPRESS FULL;
