/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "Race"
(
   "TrkCode" VARCHAR(3) NOT NULL,
   "RaceDate" DATE NOT NULL,
   "RangeRaceDate" DATE,
   "RaceNbr" SMALLINT NOT NULL,
   "IsActive" BOOLEAN DEFAULT True,
   "Surface" VARCHAR(1) DEFAULT 'D',
   "DistanceInFeet" SMALLINT DEFAULT 0,
   "DistanceInYards" SMALLINT DEFAULT 0,
   "DistanceInFurlongs" FLOAT DEFAULT 0,
   "DistanceDesc" VARCHAR(15),
   "RaceType" VARCHAR(4),
   "TypeOfRace" VARCHAR(1) DEFAULT 'T',
   "RaceTypeDesc" VARCHAR(25),
   "RaceDesc" VARCHAR(250),
   "RaceCondition" MEMO,
   "IsTurfRace" BOOLEAN DEFAULT False,
   "IsRouteRace" BOOLEAN DEFAULT False,
   "IsMaidenSpecialRace" BOOLEAN DEFAULT False,
   "IsMaidenClaimingRace" BOOLEAN DEFAULT False,
   "IsMaidenOrTurfRace" BOOLEAN DEFAULT False,
   "IsTwoYearOldRace" BOOLEAN DEFAULT False,
   "IsClaimingRace" BOOLEAN DEFAULT False,
   "AgeSexRestriction" VARCHAR(3),
   "Purse" FLOAT DEFAULT 0,
   "ClaimingPrice" FLOAT DEFAULT 0,
   "SimulcastTrkCode" VARCHAR(3),
   "SimulcastRaceNbr" SMALLINT DEFAULT 0,
   "EstTimeOfRace" TIME,
   "LocalTimeOfRace" TIME,
   "EstTimeOfFirstRace" TIME,
   "RaceAutoInc" AUTOINC,
   "TimeDiff" TIME,
   "WagerType" MEMO,
   "IsDDRace" BOOLEAN DEFAULT False,
   "DDRaceNbr" VARCHAR(10),
   "IsPk3Race" BOOLEAN DEFAULT False,
   "Pk3RaceNbr" VARCHAR(10),
   "IsPk4Race" BOOLEAN DEFAULT False,
   "Pk4RaceNbr" SMALLINT DEFAULT 0,
   "IsPk6Race" BOOLEAN DEFAULT False,
   "PK6RaceNbr" SMALLINT DEFAULT 0,
   "IsTriRace" BOOLEAN DEFAULT False,
   "IsSuperRace" BOOLEAN DEFAULT False,
   "IsQuiRace" BOOLEAN DEFAULT False,
   "IsExaRace" BOOLEAN DEFAULT False,
   "NbrTriKey" INTEGER DEFAULT 0,
   "IsPk3Leg1" BOOLEAN DEFAULT False,
   "IsPk4Leg1" BOOLEAN DEFAULT False,
   "IsPk6Leg1" BOOLEAN DEFAULT False,
   "IsPk9Leg1" BOOLEAN DEFAULT False,
   "IsDDLeg1" BOOLEAN DEFAULT False,
   "IsChalkValue" BOOLEAN DEFAULT False,
   "IsPlayableValue" BOOLEAN DEFAULT False,
   "IsFinalValue" BOOLEAN DEFAULT False,
   "TotalPk3Choices" SMALLINT DEFAULT 0,
   "Pk3KeyType" SMALLINT DEFAULT 0,
   "Pk3Selected" BOOLEAN DEFAULT False,
   "TotalTriChoices" SMALLINT DEFAULT 0,
   "TotalSuperChoices" SMALLINT DEFAULT 0,
   "TotalDDChoices" SMALLINT DEFAULT 0,
   "TopLastSpeed" INTEGER DEFAULT 0,
   "TopBackSpeed" INTEGER DEFAULT 0,
   "TopBackClass" INTEGER DEFAULT 0,
   "TopLastClass" INTEGER DEFAULT 0,
   "AltWager1" VARCHAR(40),
   "AltWager2" VARCHAR(40),
   "AltWager3" VARCHAR(40),
   "AltWager4" VARCHAR(40),
   "AltWager5" VARCHAR(40),
   "AltWager6" VARCHAR(40),
   "Wager1" VARCHAR(40),
   "Wager2" VARCHAR(40),
   "Wager3" VARCHAR(40),
   "Wager4" VARCHAR(40),
   "Wager5" VARCHAR(40),
   "Wager6" VARCHAR(40),
   "WagerFinalOrder" VARCHAR(40),
   "WagerSheetOrder" VARCHAR(40),
   "Chalk" VARCHAR(25),
   "Value" VARCHAR(25),
   "Tri" VARCHAR(40),
   "DD" VARCHAR(40),
   "Super" VARCHAR(40),
   "Exacta" VARCHAR(40),
   "Quinella" VARCHAR(40),
   "Pick3" VARCHAR(40),
   "Pick4" VARCHAR(40),
   "Pick6" VARCHAR(40),
   "ParTime" VARCHAR(40),
   "IsCreateAngle" BOOLEAN DEFAULT False,
   "IsCreateValue" BOOLEAN DEFAULT False,
   "IsCreateTip" BOOLEAN DEFAULT False,
   "IsCreatePk3" BOOLEAN DEFAULT False,
   "IsCreateDetail" BOOLEAN DEFAULT False,
   "IsCreateAlt" BOOLEAN DEFAULT False,
   "IsPrintedOnValueSheet" BOOLEAN DEFAULT False,
   "IsLinerSheetSelected" BOOLEAN DEFAULT False,
   "IsOverlaySheetSelected" BOOLEAN DEFAULT False,
   "IsWagerSheetSelected" BOOLEAN DEFAULT False,
   "IsYoubetTrack" BOOLEAN DEFAULT False,
   "RacePicks" MEMO,
   "IsRacePicksAvailable" BOOLEAN DEFAULT False,
   "WPSWagerAmt" FLOAT DEFAULT 0,
   "SfcWagerAmt" FLOAT DEFAULT 0,
   "TriWagerAmt" FLOAT DEFAULT 0,
   "ExaWagerAmt" FLOAT DEFAULT 0,
   "QuiWagerAmt" FLOAT DEFAULT 0,
   "DDWagerAmt" FLOAT DEFAULT 0,
   "Pk3WagerAmt" FLOAT DEFAULT 0,
   "Pk4WagerAmt" FLOAT DEFAULT 0,
   "Pk6WagerAmt" FLOAT DEFAULT 0,
   "TopEarlyPace" FLOAT DEFAULT 0,
   "TopMiddlePace" FLOAT DEFAULT 0,
   "TopLatePace" FLOAT DEFAULT 0,
   "TopEarlyPacePos" FLOAT DEFAULT 0,
   "TopMiddlePacePos" FLOAT DEFAULT 0,
   "TopLatePacePos" FLOAT DEFAULT 0,
   "SecondEarlyPace" FLOAT DEFAULT 0,
   "SecondMiddlePace" FLOAT DEFAULT 0,
   "SecondLatePace" FLOAT DEFAULT 0,
   "SecondEarlyPacePos" FLOAT DEFAULT 0,
   "SecondMiddlePacePos" FLOAT DEFAULT 0,
   "SecondLatePacePos" FLOAT DEFAULT 0,
   "TotalMorningLineTo1Probability" FLOAT DEFAULT 0,
   "TotalFinalLineTo1Probability" FLOAT DEFAULT 0,
   "MaxWPSBet" FLOAT DEFAULT 0,
   "MaxGimmickBet" FLOAT DEFAULT 0,
   "NbrStarters" SMALLINT DEFAULT 0,
   "NbrDebutStarters" SMALLINT DEFAULT 0,
   "NbrDebutTwoStarters" SMALLINT DEFAULT 0,
   "NbrTurfDebutStarters" SMALLINT DEFAULT 0,
   "NbrRouteDebutStarters" SMALLINT DEFAULT 0,
   "NbrScratchedStarters" SMALLINT DEFAULT 0,
   "NbrRunners" SMALLINT DEFAULT 0,
   "IsEquibaseChartsProcessed" BOOLEAN DEFAULT False,
   "IsDRFChartsProcessed" BOOLEAN DEFAULT False,
   "OrigSurface" VARCHAR(1) DEFAULT 'D',
   "IsPk9Place" BOOLEAN DEFAULT False,
   "Pk9RaceNbr" SMALLINT,
   "RaceCondition1" VARCHAR(40),
   "RaceCondition2" VARCHAR(40),
   "RaceCondition3" VARCHAR(40),
   "RaceCondition4" VARCHAR(40),
   "RaceCondition5" VARCHAR(40),
   "RaceCondition6" VARCHAR(40),
   "RaceCondition7" VARCHAR(40),
   "RaceCondition8" VARCHAR(40),
   "RaceCondition9" VARCHAR(40),
   "RaceCondition10" VARCHAR(40),
   "BetLine" VARCHAR(255),
   "RaceConditions" VARCHAR(15),
   "TrkCond" VARCHAR(3) DEFAULT 'FT',
   "OrigDistanceDesc" VARCHAR(20),
   "IsPPValue" BOOLEAN DEFAULT False,
   "IsMLValue" BOOLEAN DEFAULT False,
   "FootNotes" MEMO,
   "Trainers" VARCHAR(512),
   "Owners" VARCHAR(512),
   "ScratchedHorses" VARCHAR(512),
   "FractionalTimes" VARCHAR(100),
   "IsExactaMatched" BOOLEAN DEFAULT False,
   "ExactaNbrs" VARCHAR(50),
   "ExactaWager" SMALLINT DEFAULT 0,
   "ExactaPayout" FLOAT DEFAULT 0,
   "IsTrifectaMatched" BOOLEAN DEFAULT False,
   "TrifectaNbrs" VARCHAR(50),
   "TrifectaWager" SMALLINT DEFAULT 0,
   "TrifectaPayout" FLOAT DEFAULT 0,
   "IsSuperfectaMatched" BOOLEAN DEFAULT False,
   "SuperfectaNbrs" VARCHAR(50),
   "SuperfectaWager" SMALLINT DEFAULT 0,
   "SuperfectaPayout" FLOAT DEFAULT 0,
   "IsDailyDoubleMatchedFirstRace" BOOLEAN DEFAULT False,
   "IsDailyDoubleMatchedLastRace" BOOLEAN DEFAULT False,
   "DDFirstRace" VARCHAR(40),
   "DDLastRace" VARCHAR(40),
   "DailyDoubleNbrsFirstRace" VARCHAR(50),
   "DailyDoubleNbrsLastRace" VARCHAR(50),
   "DailyDoubleWagerFirstRace" SMALLINT DEFAULT 0,
   "DailyDoubleWagerLastRace" SMALLINT DEFAULT 0,
   "DailyDoublePayoutFirstRace" FLOAT DEFAULT 0,
   "DailyDoublePayoutLastRace" FLOAT DEFAULT 0,
   "IsQuinellaMatched" BOOLEAN DEFAULT False,
   "QuinellaNbrs" VARCHAR(50),
   "QuinellaWager" SMALLINT DEFAULT 0,
   "QuinellaPayout" FLOAT DEFAULT 0,
   "IsPick3MatchedFirstRace" BOOLEAN DEFAULT False,
   "IsPick3MatchedLastRace" BOOLEAN DEFAULT False,
   "Pick3FirstRace" VARCHAR(40),
   "Pick3LastRace" VARCHAR(40),
   "Pick3NbrsFirstRace" VARCHAR(50),
   "Pick3NbrsLastRace" VARCHAR(50),
   "Pick3WagerFirstRace" SMALLINT DEFAULT 0,
   "Pick3WagerLastRace" SMALLINT DEFAULT 0,
   "Pick3PayoutFirstRace" FLOAT DEFAULT 0,
   "Pick3PayoutLastRace" FLOAT DEFAULT 0,
   "Pick3NbrsLeg1" VARCHAR(25),
   "Pick3NbrsLeg2" VARCHAR(25),
   "Pick3NbrsLeg3" VARCHAR(25),
   "IsPick4MatchedFirstRace" BOOLEAN DEFAULT False,
   "IsPick4MatchedLastRace" BOOLEAN DEFAULT False,
   "Pick4FirstRace" VARCHAR(40),
   "Pick4LastRace" VARCHAR(40),
   "Pick4NbrsFirstRace" VARCHAR(50),
   "Pick4NbrsLastRace" VARCHAR(50),
   "Pick4WagerFirstRace" SMALLINT DEFAULT 0,
   "Pick4WagerLastRace" SMALLINT DEFAULT 0,
   "Pick4PayoutFirstRace" FLOAT DEFAULT 0,
   "Pick4PayoutLastRace" FLOAT DEFAULT 0,
   "Pick4NbrsLeg1" VARCHAR(25),
   "Pick4NbrsLeg2" VARCHAR(25),
   "Pick4NbrsLeg3" VARCHAR(25),
   "Pick4NbrsLeg4" VARCHAR(25),
   "IsPick6MatchedFirstRace" BOOLEAN DEFAULT False,
   "IsPick6MatchedLastRace" BOOLEAN DEFAULT False,
   "Pick6FirstRace" VARCHAR(40),
   "Pick6LastRace" VARCHAR(40),
   "Pick6NbrsFirstRace" VARCHAR(50),
   "Pick6NbrsLastRace" VARCHAR(50),
   "Pick6WagerFirstRace" SMALLINT DEFAULT 0,
   "Pick6WagerLastRace" SMALLINT DEFAULT 0,
   "Pick6PayoutFirstRace" FLOAT DEFAULT 0,
   "Pick6PayoutLastRace" FLOAT DEFAULT 0,
   "IsWinMatched" BOOLEAN DEFAULT False,
   "WinNbrs" VARCHAR(50),
   "WinPayout" FLOAT DEFAULT 0,
   "WinPlcPayout" FLOAT DEFAULT 0,
   "WinShoPayout" FLOAT DEFAULT 0,
   "IsPlcMatched" BOOLEAN DEFAULT False,
   "PlcNbrs" VARCHAR(50),
   "PlcPayout" FLOAT DEFAULT 0,
   "PlcShoPayout" FLOAT DEFAULT 0,
   "IsShoMatched" BOOLEAN DEFAULT False,
   "ShoNbrs" VARCHAR(50),
   "ShoPayout" FLOAT DEFAULT 0,
   "Weather" VARCHAR(100),
   "TopLastSRWinner" INTEGER DEFAULT 0,
   "RaceShape" VARCHAR(50),
PRIMARY KEY ("TrkCode","RaceDate","RaceNbr") COMPRESS FULL
INDEX PAGE SIZE 16384
BLOB BLOCK SIZE 1024
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE INDEX IF NOT EXISTS "ByEstTimeOfRace" ON "Race" ("RangeRaceDate","RaceDate","EstTimeOfRace") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByTrkCodeRaceNbr" ON "Race" ("RangeRaceDate","TrkCode","RaceNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByRaceNbr" ON "Race" ("RangeRaceDate","RaceNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByEstTimeOfFirstRace" ON "Race" ("RangeRaceDate","RaceDate","EstTimeOfFirstRace","TrkCode","RaceNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByRangeRaceDate" ON "Race" ("RangeRaceDate","RaceDate","TrkCode","RaceDate","RaceNbr") COMPRESS FULL;
