/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "ENTRY"
(
   "TrkCode" VARCHAR(3) NOT NULL,
   "RaceDate" DATE NOT NULL,
   "RangeRaceDate" DATE,
   "RaceNbr" SMALLINT NOT NULL,
   "PostPos" SMALLINT NOT NULL,
   "RaceType" VARCHAR(4),
   "EstTimeOfRace" TIME,
   "TodaysClass" SMALLINT DEFAULT 0,
   "AvgPurse" FLOAT DEFAULT 0,
   "Entry" VARCHAR(5),
   "ProgramNbr" VARCHAR(10),
   "ProgramNbrSort" SMALLINT,
   "MorningLineDesc" VARCHAR(15),
   "ValueIndicator" VARCHAR(2),
   "HorseName" VARCHAR(25),
   "Med" VARCHAR(5),
   "Equip" VARCHAR(6),
   "IsDebut" BOOLEAN DEFAULT False,
   "IsDebutTwo" BOOLEAN DEFAULT False,
   "IsFirstTimeJuice" BOOLEAN DEFAULT False,
   "IsSecondTimeJuice" BOOLEAN DEFAULT False,
   "IsBlinkersOn" BOOLEAN DEFAULT False,
   "IsBlinkersOff" BOOLEAN DEFAULT False,
   "TurfIndicator" VARCHAR(2),
   "DebutIndicator" VARCHAR(2),
   "RouteIndicator" VARCHAR(2),
   "MudIndicator" VARCHAR(2),
   "IsScratched" BOOLEAN DEFAULT False,
   "Age" SMALLINT DEFAULT 0,
   "Sex" VARCHAR(3),
   "Color" VARCHAR(10),
   "Weight" VARCHAR(10),
   "TrnEquibaseKey" VARCHAR(10),
   "IsSuperTrainer" BOOLEAN DEFAULT False,
   "Trainer" VARCHAR(30),
   "TrnWinsRank" SMALLINT DEFAULT 0,
   "TrnEarningsRank" SMALLINT DEFAULT 0,
   "TrnTrackRank" SMALLINT DEFAULT 0,
   "JkyEquibaseKey" VARCHAR(10),
   "IsSuperJockey" BOOLEAN DEFAULT False,
   "Jockey" VARCHAR(25),
   "JkyWinsRank" SMALLINT DEFAULT 0,
   "JkyEarningsRank" SMALLINT DEFAULT 0,
   "JkyTrackRank" SMALLINT DEFAULT 0,
   "IsSuperOwner" BOOLEAN DEFAULT False,
   "Owner" VARCHAR(45),
   "OwnWinsRank" SMALLINT DEFAULT 0,
   "OwnEarningsRank" SMALLINT DEFAULT 0,
   "Breeder" VARCHAR(67),
   "TotalTrnOdds0To2Starts" SMALLINT DEFAULT 0,
   "TotalTrnOdds0To2Wins" SMALLINT DEFAULT 0,
   "TotalTrnOdds0To2WinPct" FLOAT DEFAULT 0,
   "TotalTrnOdds2To5Starts" SMALLINT DEFAULT 0,
   "TotalTrnOdds2To5Wins" SMALLINT DEFAULT 0,
   "TotalTrnOdds2To5WinPct" FLOAT DEFAULT 0,
   "TotalTrnOdds6To9Starts" SMALLINT DEFAULT 0,
   "TotalTrnOdds6To9Wins" SMALLINT DEFAULT 0,
   "TotalTrnOdds6To9WinPct" FLOAT DEFAULT 0,
   "TotalTrnOdds10PlusStarts" SMALLINT DEFAULT 0,
   "TotalTrnOdds10PlusWins" SMALLINT DEFAULT 0,
   "TotalTrnOdds10PlusWinPct" FLOAT DEFAULT 0,
   "TotalTrnStarts" SMALLINT DEFAULT 0,
   "TotalTrnWins" SMALLINT DEFAULT 0,
   "TotalTrnWinPct" FLOAT DEFAULT 0,
   "TotalTrnWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnJkyStarts" SMALLINT DEFAULT 0,
   "TotalTrnJkyWins" SMALLINT DEFAULT 0,
   "TotalTrnJkyWinPct" FLOAT DEFAULT 0,
   "TotalTrnJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnOwnStarts" SMALLINT DEFAULT 0,
   "TotalTrnOwnWins" SMALLINT DEFAULT 0,
   "TotalTrnOwnWinPct" FLOAT DEFAULT 0,
   "TotalTrnOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnDaysStarts" SMALLINT DEFAULT 0,
   "TotalTrnDaysWins" SMALLINT DEFAULT 0,
   "TotalTrnDaysWinPct" FLOAT DEFAULT 0,
   "TotalTrnDaysWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnJkyDaysStarts" INTEGER DEFAULT 0,
   "TotalTrnJkyDaysWins" INTEGER DEFAULT 0,
   "TotalTrnJkyDaysWinPct" FLOAT DEFAULT 0,
   "TotalTrnJkyDaysWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn1To45Starts" SMALLINT DEFAULT 0,
   "TotalTrn1To45Wins" SMALLINT DEFAULT 0,
   "TotalTrn1To45WinPct" FLOAT DEFAULT 0,
   "TotalTrnWork1To45Starts" SMALLINT DEFAULT 0,
   "TotalTrnWork1To45Wins" SMALLINT DEFAULT 0,
   "TotalTrnWork1To45WinPct" FLOAT DEFAULT 0,
   "TotalTrn46To120Starts" SMALLINT DEFAULT 0,
   "TotalTrn46To120Wins" SMALLINT DEFAULT 0,
   "TotalTrn46To120WinPct" FLOAT DEFAULT 0,
   "TotalTrnWork46To120Starts" SMALLINT DEFAULT 0,
   "TotalTrnWork46To120Wins" SMALLINT DEFAULT 0,
   "TotalTrnWork46To120WinPct" FLOAT DEFAULT 0,
   "TotalTrn120PlusStarts" SMALLINT DEFAULT 0,
   "TotalTrn120PlusWins" SMALLINT DEFAULT 0,
   "TotalTrn120PlusWinPct" FLOAT DEFAULT 0,
   "TotalTrnWork120PlusStarts" SMALLINT DEFAULT 0,
   "TotalTrnWork120PlusWins" SMALLINT DEFAULT 0,
   "TotalTrnWork120PlusWinPct" FLOAT DEFAULT 0,
   "TotalTrnDebutStarts" SMALLINT DEFAULT 0,
   "TotalTrnDebutWins" SMALLINT DEFAULT 0,
   "TotalTrnDebutWinPct" FLOAT DEFAULT 0,
   "TotalTrnDebutTwoStarts" SMALLINT DEFAULT 0,
   "TotalTrnDebutTwoWins" SMALLINT DEFAULT 0,
   "TotalTrnDebutTwoWinPct" FLOAT DEFAULT 0,
   "TotalTrnFirstJuiceStarts" SMALLINT DEFAULT 0,
   "TotalTrnFirstJuiceWins" SMALLINT DEFAULT 0,
   "TotalTrnFirstJuiceWinPct" FLOAT DEFAULT 0,
   "TotalTrnSecondJuiceStarts" SMALLINT DEFAULT 0,
   "TotalTrnSecondJuiceWins" SMALLINT DEFAULT 0,
   "TotalTrnSecondJuiceWinPct" FLOAT DEFAULT 0,
   "TotalTrnBlinkersOnStarts" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOnWins" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOnWinPct" FLOAT DEFAULT 0,
   "TotalTrnBlinkersOffStarts" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOffWins" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOffWinPct" FLOAT DEFAULT 0,
   "TotalTrnTurfStarts" SMALLINT DEFAULT 0,
   "TotalTrnTurfWins" SMALLINT DEFAULT 0,
   "TotalTrnTurfWinPct" FLOAT DEFAULT 0,
   "TotalTrnTurfWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn10Starts" SMALLINT DEFAULT 0,
   "TotalTrn10Wins" SMALLINT DEFAULT 0,
   "TotalTrn10WinPct" FLOAT DEFAULT 0,
   "TotalTrn10WinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn30Starts" SMALLINT DEFAULT 0,
   "TotalTrn30Wins" SMALLINT DEFAULT 0,
   "TotalTrn30WinPct" FLOAT DEFAULT 0,
   "TotalTrn30WinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnAftClmStarts" SMALLINT DEFAULT 0,
   "TotalTrnAftClmWins" SMALLINT DEFAULT 0,
   "TotalTrnAftClmWinPct" FLOAT DEFAULT 0,
   "TotalTrnOddsStarts" SMALLINT DEFAULT 0,
   "TotalTrnOddsWins" SMALLINT DEFAULT 0,
   "TotalTrnOddsWinPct" FLOAT DEFAULT 0,
   "TotalTrnOddsWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn1stStarts" SMALLINT DEFAULT 0,
   "TotalTrn1stWins" SMALLINT DEFAULT 0,
   "TotalTrn1stWinPct" FLOAT DEFAULT 0,
   "TotalTrnOddsLe5Starts" SMALLINT DEFAULT 0,
   "TotalTrnOddsLe5Wins" SMALLINT DEFAULT 0,
   "TotalTrnOddsLe5WinPct" FLOAT DEFAULT 0,
   "TotalTrnOddsGt5Starts" SMALLINT DEFAULT 0,
   "TotalTrnOddsGt5Wins" SMALLINT DEFAULT 0,
   "TotalTrnOddsGt5WinPct" FLOAT DEFAULT 0,
   "TotalTrnFavStarts" SMALLINT DEFAULT 0,
   "TotalTrnFavWins" SMALLINT DEFAULT 0,
   "TotalTrnFavWinPct" FLOAT DEFAULT 0,
   "TotalTrn2yoStarts" SMALLINT DEFAULT 0,
   "TotalTrn2yoWins" SMALLINT DEFAULT 0,
   "TotalTrn2yoWinPct" FLOAT DEFAULT 0,
   "TotalTrn2oWinPctRank" SMALLINT DEFAULT 0,
   "TrnTodayStarts" SMALLINT DEFAULT 0,
   "TrnTodayWins" SMALLINT DEFAULT 0,
   "TrnTodayWinPct" FLOAT DEFAULT 0,
   "TrnTodayWinPctRank" SMALLINT DEFAULT 0,
   "TrnDirtToTurfStarts" SMALLINT DEFAULT 0,
   "TrnDirtToTurfWinPct" SMALLINT DEFAULT 0,
   "TrnTurfToDirtStarts" SMALLINT DEFAULT 0,
   "TrnTurfToDirtWinPct" SMALLINT DEFAULT 0,
   "TrnRteToSprStarts" SMALLINT DEFAULT 0,
   "TrnRteToSprWinPct" SMALLINT DEFAULT 0,
   "TrnSprToRteStarts" SMALLINT DEFAULT 0,
   "TrnSprToRteWinPct" SMALLINT DEFAULT 0,
   "TrnStkWinPct" SMALLINT DEFAULT 0,
   "TrnClmWinPct" SMALLINT DEFAULT 0,
   "TrnMdnWinPct" SMALLINT DEFAULT 0,
   "TrnAlwWinPct" SMALLINT DEFAULT 0,
   "TotalJkyStarts" SMALLINT DEFAULT 0,
   "TotalJkyWins" SMALLINT DEFAULT 0,
   "TotalJkyWinPct" FLOAT DEFAULT 0,
   "TotalJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyDaysStarts" SMALLINT DEFAULT 0,
   "TotalJkyDaysWins" SMALLINT DEFAULT 0,
   "TotalJkyDaysWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyDaysWinPct" FLOAT DEFAULT 0,
   "TotalJkyOddsStarts" SMALLINT DEFAULT 0,
   "TotalJkyOddsWins" SMALLINT DEFAULT 0,
   "TotalJkyOddsWinPct" FLOAT DEFAULT 0,
   "TotalJkyOddsWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyTurfStarts" SMALLINT DEFAULT 0,
   "TotalJkyTurfWins" SMALLINT DEFAULT 0,
   "TotalJkyTurfWinPct" FLOAT DEFAULT 0,
   "TotalJky10Starts" SMALLINT DEFAULT 0,
   "TotalJky10Wins" SMALLINT DEFAULT 0,
   "TotalJky10WinPct" FLOAT DEFAULT 0,
   "TotalJky10WinPctRank" SMALLINT DEFAULT 0,
   "TotalJky30Starts" SMALLINT DEFAULT 0,
   "TotalJky30Wins" SMALLINT DEFAULT 0,
   "TotalJky30WinPct" FLOAT DEFAULT 0,
   "TotalJky30WinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyOddsLe5Starts" SMALLINT DEFAULT 0,
   "TotalJkyOddsLe5Wins" SMALLINT DEFAULT 0,
   "TotalJkyOddsLe5WinPct" FLOAT DEFAULT 0,
   "TotalJkyOddsGt5Starts" SMALLINT DEFAULT 0,
   "TotalJkyOddsGt5Wins" SMALLINT DEFAULT 0,
   "TotalJkyOddsGt5WinPct" FLOAT DEFAULT 0,
   "TotalJkyFavStarts" SMALLINT DEFAULT 0,
   "TotalJkyFavWins" SMALLINT DEFAULT 0,
   "TotalJkyFavWinPct" FLOAT DEFAULT 0,
   "TotalJky2yoStarts" SMALLINT DEFAULT 0,
   "TotalJky2yoWins" SMALLINT DEFAULT 0,
   "TotalJky2yoWinPct" FLOAT DEFAULT 0,
   "TotalOwnStarts" SMALLINT DEFAULT 0,
   "TotalOwnWins" SMALLINT DEFAULT 0,
   "TotalOwnWinPct" FLOAT DEFAULT 0,
   "TotalOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalBrdStarts" SMALLINT DEFAULT 0,
   "TotalBrdWins" SMALLINT DEFAULT 0,
   "TotalBrdWinPct" FLOAT DEFAULT 0,
   "TotalBrdWinPctRank" SMALLINT DEFAULT 0,
   "BredIn" VARCHAR(6),
   "Sire" VARCHAR(16),
   "SireTurfLastYearRank" SMALLINT DEFAULT 0,
   "SireTurfLastYearStarts" SMALLINT DEFAULT 0,
   "SireTurfLastYearPctOfEarnings" SMALLINT DEFAULT 0,
   "SireGeneralLastYearRank" SMALLINT DEFAULT 0,
   "SireGeneralLastYearStudFee" FLOAT DEFAULT 0,
   "SireJuvenileLastYearRank" SMALLINT DEFAULT 0,
   "SireTurfThisYearRank" SMALLINT DEFAULT 0,
   "SireTurfThisYearStarts" SMALLINT DEFAULT 0,
   "SireTurfThisYearPctOfEarnings" SMALLINT DEFAULT 0,
   "SireGeneralThisYearRank" SMALLINT DEFAULT 0,
   "SireGeneralThisYearStudFee" FLOAT DEFAULT 0,
   "SireJuvenileThisYearRank" SMALLINT DEFAULT 0,
   "Dam" VARCHAR(16),
   "DamSire" VARCHAR(16),
   "DaysLast" SMALLINT DEFAULT 0,
   "DaysLastWork" SMALLINT DEFAULT 0,
   "DaysLastWork2" SMALLINT DEFAULT 0,
   "DaysLastWork3" SMALLINT DEFAULT 0,
   "NbrWorksLast" SMALLINT DEFAULT 0,
   "StartsWorks21" SMALLINT DEFAULT 0,
   "LastTrkCode" VARCHAR(3),
   "LastRaceNbr" INTEGER DEFAULT 0,
   "LastRaceDate" DATE,
   "LastPostPos" SMALLINT DEFAULT 0,
   "LastRaceType" VARCHAR(6),
   "LastSurf" VARCHAR(1),
   "LastRaceConditions" VARCHAR(20),
   "LastDistanceDesc" VARCHAR(16),
   "LastDistance" FLOAT DEFAULT 0,
   "LastOdds" FLOAT DEFAULT 0,
   "LastFavoriteIndicator" VARCHAR(21),
   "LastDQIndicator" VARCHAR(15),
   "LastJockey" VARCHAR(15),
   "LastComment" VARCHAR(22),
   "LastComment2" VARCHAR(67),
   "LastTrkCond" VARCHAR(11),
   "LastClmPrice" FLOAT DEFAULT 0,
   "LastClaimed" VARCHAR(1),
   "LastPurse" FLOAT DEFAULT 0,
   "LastTopFinish1" VARCHAR(30),
   "LastTopFinish2" VARCHAR(30),
   "LastTopFinish3" VARCHAR(30),
   "LastRaceDesc" VARCHAR(255),
   "LastDay" VARCHAR(2),
   "LastMonthDesc" VARCHAR(3),
   "LastYear" VARCHAR(4),
   "LastGateBreak" VARCHAR(2),
   "LastLen1Back" VARCHAR(7),
   "LastLen2Back" VARCHAR(7),
   "LastStLenBack" VARCHAR(7),
   "LastFinishBeaten" VARCHAR(7),
   "LastEquip" VARCHAR(7),
   "LastWeight" INTEGER,
   "LastTrackVariant" INTEGER,
   "LastClass" SMALLINT,
   "LastClassRank" SMALLINT,
   "LastHorseTime" FLOAT,
   "LastSRWinner" INTEGER,
   "FinalOrderKey" VARCHAR(50),
   "FinalStarts" INTEGER DEFAULT 0,
   "FinalWins" INTEGER DEFAULT 0,
   "FinalWinPct" FLOAT DEFAULT 0,
   "FinalWinPctRank" SMALLINT DEFAULT 0,
   "FinalAvgOdds" FLOAT DEFAULT 0,
   "FinalMinOdds" FLOAT DEFAULT 0,
   "FinalMaxOdds" FLOAT DEFAULT 0,
   "FinalAvgWinOdds" FLOAT DEFAULT 0,
   "FinalMinWinOdds" FLOAT DEFAULT 0,
   "FinalMaxWinOdds" FLOAT DEFAULT 0,
   "FinalValueBet" FLOAT DEFAULT 0,
   "FinalIV" FLOAT DEFAULT 0,
   "FinalIVRoi" FLOAT DEFAULT 0,
   "PrimaryOrderKey" VARCHAR(50),
   "PrimaryStarts" INTEGER DEFAULT 0,
   "PrimaryWins" INTEGER DEFAULT 0,
   "PrimaryWinPct" FLOAT DEFAULT 0,
   "PrimaryWinPctRank" SMALLINT DEFAULT 0,
   "PrimaryAvgOdds" FLOAT DEFAULT 0,
   "PrimaryMinOdds" FLOAT DEFAULT 0,
   "PrimaryMaxOdds" FLOAT DEFAULT 0,
   "PrimaryAvgWinOdds" FLOAT DEFAULT 0,
   "PrimaryMinWinOdds" FLOAT DEFAULT 0,
   "PrimaryMaxWinOdds" FLOAT DEFAULT 0,
   "PrimaryValueBet" FLOAT DEFAULT 0,
   "PrimaryIV" FLOAT DEFAULT 0,
   "PrimaryIVRoi" FLOAT DEFAULT 0,
   "SecondaryOrderKey" VARCHAR(50),
   "SecondaryStarts" INTEGER DEFAULT 0,
   "SecondaryWins" INTEGER DEFAULT 0,
   "SecondaryWinPct" FLOAT DEFAULT 0,
   "SecondaryWinPctRank" SMALLINT DEFAULT 0,
   "SecondaryAvgOdds" FLOAT DEFAULT 0,
   "SecondaryMinOdds" FLOAT DEFAULT 0,
   "SecondaryMaxOdds" FLOAT DEFAULT 0,
   "SecondaryAvgWinOdds" FLOAT DEFAULT 0,
   "SecondaryMinWinOdds" FLOAT DEFAULT 0,
   "SecondaryMaxWinOdds" FLOAT DEFAULT 0,
   "SecondaryValueBet" FLOAT DEFAULT 0,
   "SecondaryIV" FLOAT DEFAULT 0,
   "SecondaryIVRoi" FLOAT DEFAULT 0,
   "DefaultOrderKey" VARCHAR(50),
   "DefaultStarts" INTEGER DEFAULT 0,
   "DefaultWins" INTEGER DEFAULT 0,
   "DefaultWinPct" FLOAT DEFAULT 0,
   "DefaultWinPctRank" SMALLINT DEFAULT 0,
   "DefaultAvgOdds" FLOAT DEFAULT 0,
   "DefaultMinOdds" FLOAT DEFAULT 0,
   "DefaultMaxOdds" FLOAT DEFAULT 0,
   "DefaultAvgWinOdds" FLOAT DEFAULT 0,
   "DefaultMinWinOdds" FLOAT DEFAULT 0,
   "DefaultMaxWinOdds" FLOAT DEFAULT 0,
   "DefaultValueBet" FLOAT DEFAULT 0,
   "DefaultIV" FLOAT DEFAULT 0,
   "DefaultIVRoi" FLOAT DEFAULT 0,
   "EstMorningLineOrderKey" VARCHAR(50),
   "EstMorningLineStarts" INTEGER DEFAULT 0,
   "EstMorningLineWins" INTEGER DEFAULT 0,
   "EstMorningLineWinPct" FLOAT DEFAULT 0,
   "EstMorningLineWinPctRank" SMALLINT DEFAULT 0,
   "EstMorningLineAvgOdds" FLOAT DEFAULT 0,
   "EstMorningLineMinOdds" FLOAT DEFAULT 0,
   "EstMorningLineMaxOdds" FLOAT DEFAULT 0,
   "EstMorningLineAvgWinOdds" FLOAT DEFAULT 0,
   "EstMorningLineMinWinOdds" FLOAT DEFAULT 0,
   "EstMorningLineMaxWinOdds" FLOAT DEFAULT 0,
   "EstMorningLineValueBet" FLOAT DEFAULT 0,
   "EstMorningLineIV" FLOAT DEFAULT 0,
   "EstMorningLineIVRoi" FLOAT DEFAULT 0,
   "MorningLineTo1" FLOAT,
   "MorningLineTo1Fair" FLOAT,
   "MorningLineTo1Probability" FLOAT,
   "MorningLineTo1FairProbability" FLOAT,
   "MorningLineTo1Rank" SMALLINT,
   "IsDirtToTurf" BOOLEAN DEFAULT False,
   "IsTurfToDirt" BOOLEAN DEFAULT False,
   "IsSprToRte" BOOLEAN DEFAULT False,
   "IsRteToSpr" BOOLEAN DEFAULT False,
   "Sire_Rec_Foal" VARCHAR(9),
   "Sire_Rec_Turf" VARCHAR(9),
   "Sire_Rec_2yr" VARCHAR(9),
   "Sire_Rec_Stk" VARCHAR(9),
   "Sire_Rec_OffTrk" VARCHAR(9),
   "Sire_Rec_Fts" VARCHAR(9),
   "Sire_Rec_OfsTrk" VARCHAR(9),
   "Sire_Rec_Ds" VARCHAR(9),
   "Sire_Rec_Dr" VARCHAR(9),
   "Sire_Rec_Ts" VARCHAR(9),
   "Sire_Rec_Tr" VARCHAR(9),
   "Dam_Rec_Foal" VARCHAR(9),
   "Dam_Rec_TurfSt" VARCHAR(9),
   "Dam_Rec_2yr" VARCHAR(9),
   "Dam_Rec_StkSt" VARCHAR(9),
   "Dam_Rec_OffTrk" VARCHAR(9),
   "Dam_Rec_Fts" VARCHAR(9),
   "Dam_Rec_OfsTrk" VARCHAR(9),
   "Dam_Rec_Ds" VARCHAR(9),
   "Dam_Rec_Dr" VARCHAR(9),
   "Dam_Rec_Ts" VARCHAR(9),
   "Dam_Rec_Tr" VARCHAR(9),
   "SireAllWinPct" FLOAT DEFAULT 0,
   "SireAllTurfWinPct" FLOAT DEFAULT 0,
   "SireAllMudWinPct" FLOAT DEFAULT 0,
   "DamAllWinPct" FLOAT DEFAULT 0,
   "DamAllTurfWinPct" FLOAT DEFAULT 0,
   "DamAllMudWinPct" FLOAT DEFAULT 0,
   "DamSireAllWinPct" FLOAT DEFAULT 0,
   "DamSireAllTurfWinPct" FLOAT DEFAULT 0,
   "DamSireAllMudWinPct" FLOAT DEFAULT 0,
   "Dam2yoWinPct" SMALLINT DEFAULT 0,
   "Dam2yoWinPctRank" SMALLINT DEFAULT 0,
   "DamDebutWinPct" SMALLINT DEFAULT 0,
   "DamDebutWinPctRank" SMALLINT DEFAULT 0,
   "Sire2yoWinPct" SMALLINT DEFAULT 0,
   "Sire2yoWinPctRank" SMALLINT DEFAULT 0,
   "SireDebutWinPct" SMALLINT DEFAULT 0,
   "SireDebutWinPctRank" SMALLINT DEFAULT 0,
   "SireTrfSprWinPct" SMALLINT DEFAULT 0,
   "SireTrfSprWinPctRank" SMALLINT DEFAULT 0,
   "SireTrfRteWinPct" SMALLINT DEFAULT 0,
   "SireTrfRteWinPctRank" SMALLINT DEFAULT 0,
   "SireDirtSprWinPct" SMALLINT DEFAULT 0,
   "SireDirtSprWinPctRank" SMALLINT DEFAULT 0,
   "SireDirtRteWinPct" SMALLINT DEFAULT 0,
   "SireDirtRteWinPctRank" SMALLINT DEFAULT 0,
   "DamAllWinPctRank" SMALLINT DEFAULT 0,
   "DamAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "DamAllMudWinPctRank" SMALLINT DEFAULT 0,
   "SireAllWinPctRank" SMALLINT DEFAULT 0,
   "SireAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "SireAllMudWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllMudWinPctRank" SMALLINT DEFAULT 0,
   "ClassRating" FLOAT DEFAULT 0,
   "ClassRatingRank" SMALLINT DEFAULT 0,
   "TurfRating" FLOAT DEFAULT 0,
   "TurfRatingRank" SMALLINT DEFAULT 0,
   "MudRating" FLOAT DEFAULT 0,
   "MudRatingRank" SMALLINT DEFAULT 0,
   "LastSpeed" SMALLINT DEFAULT 0,
   "LastSpeedRank" SMALLINT DEFAULT 0,
   "Power" FLOAT DEFAULT 0,
   "PowerRank" SMALLINT DEFAULT 0,
   "BackSpeed" SMALLINT DEFAULT 0,
   "BackSpeedRank" SMALLINT DEFAULT 0,
   "AvgClass" FLOAT DEFAULT 0,
   "AvgClassRank" SMALLINT DEFAULT 0,
   "AvgSpeed" SMALLINT DEFAULT 0,
   "AvgSpeedRank" SMALLINT DEFAULT 0,
   "AvgClassRating" SMALLINT DEFAULT 0,
   "AvgClassRatingRank" SMALLINT DEFAULT 0,
   "BackClass" SMALLINT DEFAULT 0,
   "BackClassRank" SMALLINT DEFAULT 0,
   "BackPace1" FLOAT DEFAULT 0,
   "BackPace1Rank" SMALLINT DEFAULT 0,
   "BackPace2" FLOAT DEFAULT 0,
   "BackPace2Rank" SMALLINT DEFAULT 0,
   "PastSpeed" SMALLINT DEFAULT 0,
   "PastSpeedRank" SMALLINT DEFAULT 0,
   "CurrClass" SMALLINT DEFAULT 0,
   "CurrClassRank" SMALLINT DEFAULT 0,
   "AxcisEarlyPace" FLOAT DEFAULT 0,
   "AxcisEarlyPaceRank" SMALLINT DEFAULT 0,
   "AxcisEarlyPacePos" FLOAT DEFAULT 9999,
   "AxcisEarlyPacePosRank" SMALLINT DEFAULT 0,
   "AxcisMiddlePace" FLOAT DEFAULT 0,
   "AxcisMiddlePaceRank" SMALLINT DEFAULT 0,
   "AxcisMiddlePacePos" FLOAT DEFAULT 9999,
   "AxcisMiddlePacePosRank" SMALLINT DEFAULT 0,
   "AxcisLatePace" FLOAT DEFAULT 0,
   "AxcisLatePaceRank" SMALLINT DEFAULT 0,
   "AxcisLatePacePos" FLOAT DEFAULT 9999,
   "AxcisLatePacePosRank" SMALLINT DEFAULT 0,
   "EarlyPace" FLOAT DEFAULT 0,
   "EarlyPaceRank" SMALLINT DEFAULT 0,
   "EarlyPacePos" FLOAT DEFAULT 9999,
   "EarlyPacePosRank" SMALLINT DEFAULT 0,
   "EarlyPaceO" FLOAT DEFAULT 0,
   "EarlyPaceORank" SMALLINT DEFAULT 0,
   "EarlyPacePosO" FLOAT DEFAULT 9999,
   "EarlyPacePosORank" SMALLINT DEFAULT 0,
   "EarlyPaceH" FLOAT DEFAULT 0,
   "EarlyPaceHRank" SMALLINT DEFAULT 0,
   "EarlyPacePosH" FLOAT DEFAULT 9999,
   "EarlyPacePosHRank" SMALLINT DEFAULT 0,
   "MiddlePace" FLOAT DEFAULT 0,
   "MiddlePaceRank" SMALLINT DEFAULT 0,
   "MiddlePacePos" FLOAT DEFAULT 9999,
   "MiddlePacePosRank" SMALLINT DEFAULT 0,
   "MiddlePaceO" FLOAT DEFAULT 0,
   "MiddlePaceORank" SMALLINT DEFAULT 0,
   "MiddlePacePosO" FLOAT DEFAULT 9999,
   "MiddlePacePosORank" SMALLINT DEFAULT 0,
   "MiddlePaceH" FLOAT DEFAULT 0,
   "MiddlePaceHRank" SMALLINT DEFAULT 0,
   "MiddlePacePosH" FLOAT DEFAULT 9999,
   "MiddlePacePosHRank" SMALLINT DEFAULT 0,
   "LatePace" FLOAT DEFAULT 0,
   "LatePaceRank" SMALLINT DEFAULT 0,
   "LatePacePos" FLOAT DEFAULT 9999,
   "LatePacePosRank" SMALLINT DEFAULT 0,
   "LatePaceH" FLOAT DEFAULT 0,
   "LatePaceHRank" SMALLINT DEFAULT 0,
   "LatePacePosH" FLOAT DEFAULT 9999,
   "LatePacePosHRank" SMALLINT DEFAULT 0,
   "LatePaceO" FLOAT DEFAULT 0,
   "LatePaceORank" SMALLINT DEFAULT 0,
   "LatePacePosO" FLOAT DEFAULT 9999,
   "LatePacePosORank" SMALLINT DEFAULT 0,
   "FinishPacePos" FLOAT DEFAULT 0,
   "FinishPacePosRank" SMALLINT DEFAULT 0,
   "EarlyPaceAdvantage" FLOAT DEFAULT 0,
   "MiddlePaceAdvantage" FLOAT DEFAULT 0,
   "LatePaceAdvantage" FLOAT DEFAULT 0,
   "Speed1Back" SMALLINT DEFAULT 0,
   "Speed2Back" SMALLINT DEFAULT 0,
   "Speed3Back" SMALLINT DEFAULT 0,
   "Speed4Back" SMALLINT DEFAULT 0,
   "Speed5Back" SMALLINT DEFAULT 0,
   "TimesSpdDeclined" SMALLINT DEFAULT 0,
   "IsClaimed1Back" BOOLEAN DEFAULT False,
   "IsClaimed2Back" BOOLEAN DEFAULT False,
   "IsLayoffAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndDown" BOOLEAN DEFAULT False,
   "IsFirstTimeClaiming" BOOLEAN DEFAULT False,
   "IsBelowClaimedPrice" BOOLEAN DEFAULT False,
   "LifeStarts" SMALLINT DEFAULT 0,
   "LifeWins" SMALLINT DEFAULT 0,
   "LifePlcs" SMALLINT DEFAULT 0,
   "LifeShos" SMALLINT DEFAULT 0,
   "LifeEarnings" INTEGER DEFAULT 0,
   "LifeEPS" INTEGER DEFAULT 0,
   "TurfStarts" SMALLINT DEFAULT 0,
   "TurfWins" SMALLINT DEFAULT 0,
   "TurfPlcs" SMALLINT DEFAULT 0,
   "TurfShos" SMALLINT DEFAULT 0,
   "TurfEarnings" INTEGER DEFAULT 0,
   "TurfEPS" INTEGER DEFAULT 0,
   "MudStarts" SMALLINT DEFAULT 0,
   "MudWins" SMALLINT DEFAULT 0,
   "MudPlcs" SMALLINT DEFAULT 0,
   "MudShos" SMALLINT DEFAULT 0,
   "MudEarnings" INTEGER DEFAULT 0,
   "MudEPS" INTEGER DEFAULT 0,
   "TrkStarts" SMALLINT DEFAULT 0,
   "TrkWins" SMALLINT DEFAULT 0,
   "TrkPlcs" SMALLINT DEFAULT 0,
   "TrkShos" SMALLINT DEFAULT 0,
   "TrkEarnings" INTEGER DEFAULT 0,
   "TrkEPS" INTEGER DEFAULT 0,
   "RouteStarts" SMALLINT DEFAULT 0,
   "RouteWins" SMALLINT DEFAULT 0,
   "RoutePlcs" SMALLINT DEFAULT 0,
   "RouteShos" SMALLINT DEFAULT 0,
   "SprintStarts" SMALLINT DEFAULT 0,
   "SprintWins" SMALLINT DEFAULT 0,
   "SprintPlcs" SMALLINT DEFAULT 0,
   "SprintShos" SMALLINT DEFAULT 0,
   "Pk3Choice" FLOAT DEFAULT 0,
   "TriChoice" FLOAT DEFAULT 0,
   "SuperChoice" FLOAT DEFAULT 0,
   "DDChoice" FLOAT DEFAULT 0,
   "ValueChoice" SMALLINT DEFAULT 0,
   "AngleChoice" INTEGER DEFAULT 0,
   "AngleDesc" VARCHAR(100),
   "TipChoice" INTEGER DEFAULT 0,
   "IsCreateAngle" BOOLEAN DEFAULT False,
   "IsCreateTip" BOOLEAN DEFAULT False,
   "IsCreateAlt" BOOLEAN DEFAULT False,
   "IsCreatePK3" BOOLEAN DEFAULT False,
   "IsCreateDetail" BOOLEAN DEFAULT False,
   "IsCreateValue" BOOLEAN DEFAULT False,
   "IsPlayableValue" BOOLEAN DEFAULT False,
   "IsFinalValue" BOOLEAN DEFAULT False,
   "IsChalkValue" BOOLEAN DEFAULT False,
   "IsOverlaySheetSelected" BOOLEAN DEFAULT False,
   "IsWagerSheetSelected" BOOLEAN DEFAULT False,
   "IsYouBetTrack" BOOLEAN DEFAULT False,
   "IsLinerSheetSelected" BOOLEAN DEFAULT False,
   "IsPrintedOnAngleSheet" BOOLEAN DEFAULT False,
   "IsPrintedOnValueSheet" BOOLEAN DEFAULT False,
   "HorseNbr" SMALLINT DEFAULT 0,
   "WorkLine1" VARCHAR(250),
   "WorkLine2" VARCHAR(250),
   "Wager" VARCHAR(10),
   "WagerAmt" INTEGER DEFAULT 0,
   "PlcWagerAmt" SMALLINT DEFAULT 0,
   "ShoWagerAmt" SMALLINT DEFAULT 0,
   "IsDollar" BOOLEAN DEFAULT False,
   "IsDoubleDollar" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner" BOOLEAN DEFAULT False,
   "IsTripleLiner" BOOLEAN DEFAULT False,
   "IsFrontDoubleDot" BOOLEAN DEFAULT False,
   "IsBackDoubleDot" BOOLEAN DEFAULT False,
   "IsTripleDot" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner0" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner0" BOOLEAN DEFAULT False,
   "IsTripleLiner0" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner1" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner1" BOOLEAN DEFAULT False,
   "IsTripleLiner1" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner2" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner2" BOOLEAN DEFAULT False,
   "IsTripleLiner2" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner3" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner3" BOOLEAN DEFAULT False,
   "IsTripleLiner3" BOOLEAN DEFAULT False,
   "LinerKeyByTrkAll" VARCHAR(40),
   "LinerStartsByTrkAll" INTEGER DEFAULT 0,
   "LinerWinsByTrkAll" INTEGER DEFAULT 0,
   "LinerWinPctByTrkAll" FLOAT DEFAULT 0,
   "LinerAvgOddsByTrkAll" FLOAT DEFAULT 0,
   "LinerMinOddsByTrkAll" FLOAT DEFAULT 0,
   "LinerMaxOddsByTrkAll" FLOAT DEFAULT 0,
   "LinerAvgWinOddsByTrkAll" FLOAT DEFAULT 0,
   "LinerMinWinOddsByTrkAll" FLOAT DEFAULT 0,
   "LinerMaxWinOddsByTrkAll" FLOAT DEFAULT 0,
   "LinerValueBetByTrkAll" FLOAT DEFAULT 0,
   "LinerIVByTrkAll" FLOAT DEFAULT 0,
   "LinerIVRoiByTrkAll" FLOAT DEFAULT 0,
   "LinerKeyByTrk0To3" VARCHAR(40),
   "LinerStartsByTrk0To3" INTEGER DEFAULT 0,
   "LinerWinsByTrk0To3" INTEGER DEFAULT 0,
   "LinerWinPctByTrk0To3" FLOAT DEFAULT 0,
   "LinerValueBetByTrk0To3" FLOAT DEFAULT 0,
   "LinerAvgOddsByTrk0To3" FLOAT DEFAULT 0,
   "LinerMinOddsByTrk0To3" FLOAT DEFAULT 0,
   "LinerMaxOddsByTrk0To3" FLOAT DEFAULT 0,
   "LinerAvgWinOddsByTrk0To3" FLOAT DEFAULT 0,
   "LinerMinWinOddsByTrk0To3" FLOAT DEFAULT 0,
   "LinerMaxWinOddsByTrk0To3" FLOAT DEFAULT 0,
   "LinerIVByTrk0To3" FLOAT DEFAULT 0,
   "LinerIVRoiByTrk0To3" FLOAT DEFAULT 0,
   "TodaysWagerOrderKey" VARCHAR(50),
   "TodaysWagerStarts" INTEGER DEFAULT 0,
   "TodaysWagerWins" INTEGER DEFAULT 0,
   "TodaysWagerWinPct" FLOAT DEFAULT 0,
   "TodaysWagerWinPctRank" SMALLINT DEFAULT 0,
   "TodaysWagerAvgOdds" FLOAT DEFAULT 0,
   "TodaysWagerMinOdds" FLOAT DEFAULT 0,
   "TodaysWagerMaxOdds" FLOAT DEFAULT 0,
   "TodaysWagerAvgWinOdds" FLOAT DEFAULT 0,
   "TodaysWagerMinWinOdds" FLOAT DEFAULT 0,
   "TodaysWagerMaxWinOdds" FLOAT DEFAULT 0,
   "TodaysWagerValueBet" FLOAT DEFAULT 0,
   "TodaysWagerIV" FLOAT DEFAULT 0,
   "TodaysWagerIVRoi" FLOAT DEFAULT 0,
   "TodaysWagerLineTo1" FLOAT DEFAULT 0,
   "TodaysWagerLineTo1Probability" FLOAT DEFAULT 0,
   "TodaysWagerLineTo1Fair" FLOAT DEFAULT 0,
   "TodaysWagerLineTo1FairProbability" FLOAT DEFAULT 0,
   "TodaysWagerME" FLOAT DEFAULT 0,
   "TodaysWagerKellyPct" FLOAT DEFAULT 0,
   "TodaysWagerExpectedProfitLossPct" FLOAT DEFAULT 0,
   "LinerIVAvgOddsByTrkAll" FLOAT DEFAULT 0,
   "LinerIVAvgOddsByTrk0To3" FLOAT DEFAULT 0,
   "Last2TrkCode" VARCHAR(3),
   "Last2RaceNbr" INTEGER DEFAULT 0,
   "Last2RaceDate" DATE,
   "Last2PostPos" SMALLINT DEFAULT 0,
   "Last2RaceType" VARCHAR(6),
   "Last2Surf" VARCHAR(1),
   "Last2RaceConditions" VARCHAR(20),
   "Last2DistanceDesc" VARCHAR(16),
   "Last2Distance" FLOAT DEFAULT 0,
   "Last2Odds" FLOAT DEFAULT 0,
   "Last2FavoriteIndicator" VARCHAR(21),
   "Last2DQIndicator" VARCHAR(15),
   "Last2Jockey" VARCHAR(15),
   "Last2Comment" VARCHAR(22),
   "Last2Comment2" VARCHAR(67),
   "Last2TrkCond" VARCHAR(11),
   "Last2ClmPrice" FLOAT DEFAULT 0,
   "Last2Claimed" VARCHAR(1),
   "Last2Purse" FLOAT DEFAULT 0,
   "Last2TopFinish1" VARCHAR(30),
   "Last2TopFinish2" VARCHAR(30),
   "Last2TopFinish3" VARCHAR(30),
   "Last2RaceDesc" VARCHAR(255),
   "Last2Day" VARCHAR(2),
   "Last2MonthDesc" VARCHAR(3),
   "Last2Year" VARCHAR(4),
   "Last2GateBreak" VARCHAR(2),
   "Last2Len1Back" VARCHAR(7),
   "Last2Len2Back" VARCHAR(7),
   "Last2StLenBack" VARCHAR(7),
   "Last2FinishBeaten" VARCHAR(7),
   "Last2Equip" VARCHAR(7),
   "Last2Weight" INTEGER,
   "Last2TrackVariant" INTEGER,
   "Last2Class" INTEGER,
   "Last2Speed" INTEGER,
   "Last2HorseTime" FLOAT,
   "Last2SRWinner" INTEGER,
   "Last3TrkCode" VARCHAR(3),
   "Last3RaceNbr" INTEGER DEFAULT 0,
   "Last3RaceDate" DATE,
   "Last3PostPos" SMALLINT DEFAULT 0,
   "Last3RaceType" VARCHAR(6),
   "Last3Surf" VARCHAR(1),
   "Last3RaceConditions" VARCHAR(20),
   "Last3DistanceDesc" VARCHAR(16),
   "Last3Distance" FLOAT DEFAULT 0,
   "Last3Odds" FLOAT DEFAULT 0,
   "Last3FavoriteIndicator" VARCHAR(21),
   "Last3DQIndicator" VARCHAR(15),
   "Last3Jockey" VARCHAR(15),
   "Last3Comment" VARCHAR(22),
   "Last3Comment2" VARCHAR(67),
   "Last3TrkCond" VARCHAR(11),
   "Last3ClmPrice" FLOAT DEFAULT 0,
   "Last3Claimed" VARCHAR(1),
   "Last3Purse" FLOAT DEFAULT 0,
   "Last3TopFinish1" VARCHAR(30),
   "Last3TopFinish2" VARCHAR(30),
   "Last3TopFinish3" VARCHAR(30),
   "Last3RaceDesc" VARCHAR(255),
   "Last3Day" VARCHAR(2),
   "Last3MonthDesc" VARCHAR(3),
   "Last3Year" VARCHAR(4),
   "Last3GateBreak" VARCHAR(2),
   "Last3Len1Back" VARCHAR(7),
   "Last3Len2Back" VARCHAR(7),
   "Last3StLenBack" VARCHAR(7),
   "Last3FinishBeaten" VARCHAR(7),
   "Last3Equip" VARCHAR(7),
   "Last3Weight" INTEGER,
   "Last3TrackVariant" INTEGER,
   "Last3Class" INTEGER,
   "Last3Speed" INTEGER,
   "Last3HorseTime" FLOAT,
   "Last3SRWinner" INTEGER,
   "Odds" FLOAT DEFAULT 0,
   "FinishPos" FLOAT DEFAULT 0,
   "TodaysWagerExpectedWinRoi" FLOAT DEFAULT 0,
   "QSP1stCall" SMALLINT,
   "QSP1stCallRank" SMALLINT,
   "QSP1stCallRunStyle" VARCHAR(2),
   "QSP2ndCall" SMALLINT,
   "QSP2ndCallRank" SMALLINT,
   "QSP2ndCallRunStyle" VARCHAR(2),
   "KSP1stCall" SMALLINT,
   "KSP1stCallRank" SMALLINT,
   "KSP2ndCall" SMALLINT,
   "KSP2ndCallRank" SMALLINT,
   "ByTrkEPSRank" SMALLINT,
   "ByMudEPSRank" SMALLINT,
   "ByTrfEPSRank" SMALLINT,
   "IsLastOutMoveOnTurn" BOOLEAN DEFAULT False,
   "DaysLastOutMoveOnTurn" INTEGER DEFAULT 0,
   "IsLastOutFFMove" BOOLEAN DEFAULT False,
   "DaysLastOutFFMove" INTEGER DEFAULT 0,
   "IsPriorToLastOutMoveOnTurn" BOOLEAN DEFAULT False,
   "DaysPriorToLastOutMoveOnTurn" INTEGER DEFAULT 0,
   "IsPriorToLastOutFFMove" BOOLEAN DEFAULT False,
   "DaysPriorToLastOutFFMove" INTEGER DEFAULT 0,
   "LastSRWinnerRank" INTEGER DEFAULT 0,
   "LastFractionsLine" VARCHAR(75),
   "LastRunningLine" VARCHAR(75),
   "Last2FractionsLine" VARCHAR(75),
   "Last2RunningLine" VARCHAR(75),
   "Last3FractionsLine" VARCHAR(75),
   "Last3RunningLine" VARCHAR(75),
   "LowestWeight" INTEGER DEFAULT 999,
   "LastPos1stCall" FLOAT DEFAULT 0,
   "LastPos2ndCall" FLOAT DEFAULT 0,
   "LastPosStrCall" FLOAT DEFAULT 0,
   "Last2Pos1stCall" FLOAT DEFAULT 0,
   "Last2Pos2ndCall" FLOAT DEFAULT 0,
   "Last2PosStrCall" FLOAT DEFAULT 0,
   "Last3Pos1stCall" FLOAT DEFAULT 0,
   "Last3Pos2ndCall" FLOAT DEFAULT 0,
   "Last3PosStrCall" FLOAT DEFAULT 0,
   "LastTime1stCall" FLOAT DEFAULT 0,
   "LastTime2ndCall" FLOAT DEFAULT 0,
   "LastTimeStrCall" FLOAT DEFAULT 0,
   "LastTimeFinCall" FLOAT DEFAULT 0,
   "Last2Time1stCall" FLOAT DEFAULT 0,
   "Last2Time2ndCall" FLOAT DEFAULT 0,
   "Last2TimeStrCall" FLOAT DEFAULT 0,
   "Last2TimeFinCall" FLOAT DEFAULT 0,
   "Last3Time1stCall" FLOAT DEFAULT 0,
   "Last3Time2ndCall" FLOAT DEFAULT 0,
   "Last3TimeStrCall" FLOAT DEFAULT 0,
   "Last3TimeFinCall" FLOAT DEFAULT 0,
   "LastBL1stCall" FLOAT DEFAULT 0,
   "LastBL2ndCall" FLOAT DEFAULT 0,
   "LastBLStrCall" FLOAT DEFAULT 0,
   "LastBLFinCall" FLOAT DEFAULT 0,
   "Last2BL1stCall" FLOAT DEFAULT 0,
   "Last2BL2ndCall" FLOAT DEFAULT 0,
   "Last2BLStrCall" FLOAT DEFAULT 0,
   "Last2BLFinCall" FLOAT DEFAULT 0,
   "Last3BL1stCall" FLOAT DEFAULT 0,
   "Last3BL2ndCall" FLOAT DEFAULT 0,
   "Last3BLStrCall" FLOAT DEFAULT 0,
   "Last3BLFinCall" FLOAT DEFAULT 0,
   "LastPosFinCall" FLOAT DEFAULT 0,
   "Last2PosFinCall" FLOAT DEFAULT 0,
   "Last3PosFinCall" FLOAT DEFAULT 0,
PRIMARY KEY ("TrkCode","RaceDate","RaceNbr","PostPos") COMPRESS FULL
INDEX PAGE SIZE 16384
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE NOCASE INDEX IF NOT EXISTS "ByHorseName" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","HorseName") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByRangeRaceDate" ON "ENTRY" ("RangeRaceDate","RaceDate","TrkCode","RaceDate","RaceNbr","PostPos") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByHorseNbr" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","HorseNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByMorningLineTo1" ON "ENTRY" ("RangeRaceDate","MorningLineTo1") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByEstTimeOfRace" ON "ENTRY" ("RangeRaceDate","EstTimeOfRace") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByProgSortOrder" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","ProgramNbrSort") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByPrimaryWinPctRank" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","PrimaryWinPct" DESC,"TrnTrackRank","JkyTrackRank","TrnWinsRank","JkyWinsRank","OwnWinsRank") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "BySecondaryWinPctRank" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","SecondaryWinPct" DESC,"TrnTrackRank","JkyTrackRank","TrnWinsRank","JkyWinsRank","OwnWinsRank") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByDefaultWinPctRank" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","DefaultWinPct" DESC,"TrnTrackRank","JkyTrackRank","TrnWinsRank","JkyWinsRank","OwnWinsRank") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByFinalWinPctRank" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","FinalWinPct" DESC,"TrnTrackRank","JkyTrackRank","TrnWinsRank","JkyWinsRank","OwnWinsRank") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByTodaysWagerWinPctRank" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","TodaysWagerWinPct" DESC,"TrnTrackRank","JkyTrackRank","TrnWinsRank","JkyWinsRank","OwnWinsRank") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByTEst" ON "ENTRY" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","KSP1stCall" DESC) COMPRESS FULL;
