unit createrace;

interface

procedure CreateTables(CreateDatabaseName: string);

implementation

{$IFDEF VER170}
uses Forms, Classes, DB, DBISAMTb, SysUtils, Variants;
{$ENDIF}
{$IFDEF VER150}
uses Forms, Classes, DB, DBISAMTb, SysUtils, Variants;
{$ENDIF}
{$IFDEF VER140}
uses Forms, Classes, DB, DBISAMTb, SysUtils, Variants;
{$ENDIF}
{$IFDEF VER130}
uses Forms, Classes, DB, DBISAMTb, SysUtils;
{$ENDIF}

procedure CreateTables(CreateDatabaseName: string);
var
   TableToCreate: TDBISAMTable;
begin
   TableToCreate := TDBISAMTable.Create(Application);
   try
      with TableToCreate do begin
         DatabaseName := CreateDatabaseName;
         TableName := 'entry';
         Exclusive := True;
         if (not Exists) then begin
            with FieldDefs do begin
               Clear;
               Add('TrkCode', ftString, 3, True);
               Add('RaceDate', ftDate, 0, True);
               Add('RangeRaceDate', ftDate);
               Add('RaceNbr', ftSmallint, 0, True);
               Add('PostPos', ftSmallint, 0, True);
               Add('RaceType', ftString, 4);
               Add('EstTimeOfRace', ftTime);
               Add('TodaysClass', ftSmallint, 0, False, '0');
               Add('AvgPurse', ftFloat, 0, False, '0');
               Add('Entry', ftString, 5);
               Add('ProgramNbr', ftString, 10);
               Add('ProgramNbrSort', ftSmallint);
               Add('MorningLineDesc', ftString, 15);
               Add('ValueIndicator', ftString, 2);
               Add('HorseName', ftString, 25);
               Add('Med', ftString, 5);
               Add('Equip', ftString, 6);
               Add('IsDebut', ftBoolean, 0, False, 'False');
               Add('IsDebutTwo', ftBoolean, 0, False, 'False');
               Add('IsFirstTimeJuice', ftBoolean, 0, False, 'False');
               Add('IsSecondTimeJuice', ftBoolean, 0, False, 'False');
               Add('IsBlinkersOn', ftBoolean, 0, False, 'False');
               Add('IsBlinkersOff', ftBoolean, 0, False, 'False');
               Add('TurfIndicator', ftString, 2);
               Add('DebutIndicator', ftString, 2);
               Add('RouteIndicator', ftString, 2);
               Add('MudIndicator', ftString, 2);
               Add('IsScratched', ftBoolean, 0, False, 'False');
               Add('Age', ftSmallint, 0, False, '0');
               Add('Sex', ftString, 3);
               Add('Color', ftString, 10);
               Add('Weight', ftString, 10);
               Add('TrnEquibaseKey', ftString, 10);
               Add('IsSuperTrainer', ftBoolean, 0, False, 'False');
               Add('Trainer', ftString, 30);
               Add('TrnWinsRank', ftSmallint, 0, False, '0');
               Add('TrnEarningsRank', ftSmallint, 0, False, '0');
               Add('TrnTrackRank', ftSmallint, 0, False, '0');
               Add('JkyEquibaseKey', ftString, 10);
               Add('IsSuperJockey', ftBoolean, 0, False, 'False');
               Add('Jockey', ftString, 25);
               Add('JkyWinsRank', ftSmallint, 0, False, '0');
               Add('JkyEarningsRank', ftSmallint, 0, False, '0');
               Add('JkyTrackRank', ftSmallint, 0, False, '0');
               Add('IsSuperOwner', ftBoolean, 0, False, 'False');
               Add('Owner', ftString, 45);
               Add('OwnWinsRank', ftSmallint, 0, False, '0');
               Add('OwnEarningsRank', ftSmallint, 0, False, '0');
               Add('Breeder', ftString, 67);
               Add('TotalTrnOdds0To2Starts', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds0To2Wins', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds0To2WinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOdds2To5Starts', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds2To5Wins', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds2To5WinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOdds6To9Starts', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds6To9Wins', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds6To9WinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOdds10PlusStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds10PlusWins', ftSmallint, 0, False, '0');
               Add('TotalTrnOdds10PlusWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnWins', ftSmallint, 0, False, '0');
               Add('TotalTrnWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrnJkyStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnJkyWins', ftSmallint, 0, False, '0');
               Add('TotalTrnJkyWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnJkyWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrnOwnStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnOwnWins', ftSmallint, 0, False, '0');
               Add('TotalTrnOwnWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOwnWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrnDaysStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnDaysWins', ftSmallint, 0, False, '0');
               Add('TotalTrnDaysWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnDaysWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrnJkyDaysStarts', ftInteger, 0, False, '0');
               Add('TotalTrnJkyDaysWins', ftInteger, 0, False, '0');
               Add('TotalTrnJkyDaysWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnJkyDaysWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrn1To45Starts', ftSmallint, 0, False, '0');
               Add('TotalTrn1To45Wins', ftSmallint, 0, False, '0');
               Add('TotalTrn1To45WinPct', ftFloat, 0, False, '0');
               Add('TotalTrnWork1To45Starts', ftSmallint, 0, False, '0');
               Add('TotalTrnWork1To45Wins', ftSmallint, 0, False, '0');
               Add('TotalTrnWork1To45WinPct', ftFloat, 0, False, '0');
               Add('TotalTrn46To120Starts', ftSmallint, 0, False, '0');
               Add('TotalTrn46To120Wins', ftSmallint, 0, False, '0');
               Add('TotalTrn46To120WinPct', ftFloat, 0, False, '0');
               Add('TotalTrnWork46To120Starts', ftSmallint, 0, False, '0');
               Add('TotalTrnWork46To120Wins', ftSmallint, 0, False, '0');
               Add('TotalTrnWork46To120WinPct', ftFloat, 0, False, '0');
               Add('TotalTrn120PlusStarts', ftSmallint, 0, False, '0');
               Add('TotalTrn120PlusWins', ftSmallint, 0, False, '0');
               Add('TotalTrn120PlusWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnWork120PlusStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnWork120PlusWins', ftSmallint, 0, False, '0');
               Add('TotalTrnWork120PlusWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnDebutStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnDebutWins', ftSmallint, 0, False, '0');
               Add('TotalTrnDebutWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnDebutTwoStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnDebutTwoWins', ftSmallint, 0, False, '0');
               Add('TotalTrnDebutTwoWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnFirstJuiceStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnFirstJuiceWins', ftSmallint, 0, False, '0');
               Add('TotalTrnFirstJuiceWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnSecondJuiceStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnSecondJuiceWins', ftSmallint, 0, False, '0');
               Add('TotalTrnSecondJuiceWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnBlinkersOnStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnBlinkersOnWins', ftSmallint, 0, False, '0');
               Add('TotalTrnBlinkersOnWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnBlinkersOffStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnBlinkersOffWins', ftSmallint, 0, False, '0');
               Add('TotalTrnBlinkersOffWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnTurfStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnTurfWins', ftSmallint, 0, False, '0');
               Add('TotalTrnTurfWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnTurfWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrn10Starts', ftSmallint, 0, False, '0');
               Add('TotalTrn10Wins', ftSmallint, 0, False, '0');
               Add('TotalTrn10WinPct', ftFloat, 0, False, '0');
               Add('TotalTrn10WinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrn30Starts', ftSmallint, 0, False, '0');
               Add('TotalTrn30Wins', ftSmallint, 0, False, '0');
               Add('TotalTrn30WinPct', ftFloat, 0, False, '0');
               Add('TotalTrn30WinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrnAftClmStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnAftClmWins', ftSmallint, 0, False, '0');
               Add('TotalTrnAftClmWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOddsStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnOddsWins', ftSmallint, 0, False, '0');
               Add('TotalTrnOddsWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOddsWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalTrn1stStarts', ftSmallint, 0, False, '0');
               Add('TotalTrn1stWins', ftSmallint, 0, False, '0');
               Add('TotalTrn1stWinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOddsLe5Starts', ftSmallint, 0, False, '0');
               Add('TotalTrnOddsLe5Wins', ftSmallint, 0, False, '0');
               Add('TotalTrnOddsLe5WinPct', ftFloat, 0, False, '0');
               Add('TotalTrnOddsGt5Starts', ftSmallint, 0, False, '0');
               Add('TotalTrnOddsGt5Wins', ftSmallint, 0, False, '0');
               Add('TotalTrnOddsGt5WinPct', ftFloat, 0, False, '0');
               Add('TotalTrnFavStarts', ftSmallint, 0, False, '0');
               Add('TotalTrnFavWins', ftSmallint, 0, False, '0');
               Add('TotalTrnFavWinPct', ftFloat, 0, False, '0');
               Add('TotalTrn2yoStarts', ftSmallint, 0, False, '0');
               Add('TotalTrn2yoWins', ftSmallint, 0, False, '0');
               Add('TotalTrn2yoWinPct', ftFloat, 0, False, '0');
               Add('TotalTrn2oWinPctRank', ftSmallint, 0, False, '0');
               Add('TrnTodayStarts', ftSmallint, 0, False, '0');
               Add('TrnTodayWins', ftSmallint, 0, False, '0');
               Add('TrnTodayWinPct', ftFloat, 0, False, '0');
               Add('TrnTodayWinPctRank', ftSmallint, 0, False, '0');
               Add('TrnDirtToTurfStarts', ftSmallint, 0, False, '0');
               Add('TrnDirtToTurfWinPct', ftSmallint, 0, False, '0');
               Add('TrnTurfToDirtStarts', ftSmallint, 0, False, '0');
               Add('TrnTurfToDirtWinPct', ftSmallint, 0, False, '0');
               Add('TrnRteToSprStarts', ftSmallint, 0, False, '0');
               Add('TrnRteToSprWinPct', ftSmallint, 0, False, '0');
               Add('TrnSprToRteStarts', ftSmallint, 0, False, '0');
               Add('TrnSprToRteWinPct', ftSmallint, 0, False, '0');
               Add('TrnStkWinPct', ftSmallint, 0, False, '0');
               Add('TrnClmWinPct', ftSmallint, 0, False, '0');
               Add('TrnMdnWinPct', ftSmallint, 0, False, '0');
               Add('TrnAlwWinPct', ftSmallint, 0, False, '0');
               Add('TotalJkyStarts', ftSmallint, 0, False, '0');
               Add('TotalJkyWins', ftSmallint, 0, False, '0');
               Add('TotalJkyWinPct', ftFloat, 0, False, '0');
               Add('TotalJkyWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalJkyDaysStarts', ftSmallint, 0, False, '0');
               Add('TotalJkyDaysWins', ftSmallint, 0, False, '0');
               Add('TotalJkyDaysWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalJkyDaysWinPct', ftFloat, 0, False, '0');
               Add('TotalJkyOddsStarts', ftSmallint, 0, False, '0');
               Add('TotalJkyOddsWins', ftSmallint, 0, False, '0');
               Add('TotalJkyOddsWinPct', ftFloat, 0, False, '0');
               Add('TotalJkyOddsWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalJkyTurfStarts', ftSmallint, 0, False, '0');
               Add('TotalJkyTurfWins', ftSmallint, 0, False, '0');
               Add('TotalJkyTurfWinPct', ftFloat, 0, False, '0');
               Add('TotalJky10Starts', ftSmallint, 0, False, '0');
               Add('TotalJky10Wins', ftSmallint, 0, False, '0');
               Add('TotalJky10WinPct', ftFloat, 0, False, '0');
               Add('TotalJky10WinPctRank', ftSmallint, 0, False, '0');
               Add('TotalJky30Starts', ftSmallint, 0, False, '0');
               Add('TotalJky30Wins', ftSmallint, 0, False, '0');
               Add('TotalJky30WinPct', ftFloat, 0, False, '0');
               Add('TotalJky30WinPctRank', ftSmallint, 0, False, '0');
               Add('TotalJkyOddsLe5Starts', ftSmallint, 0, False, '0');
               Add('TotalJkyOddsLe5Wins', ftSmallint, 0, False, '0');
               Add('TotalJkyOddsLe5WinPct', ftFloat, 0, False, '0');
               Add('TotalJkyOddsGt5Starts', ftSmallint, 0, False, '0');
               Add('TotalJkyOddsGt5Wins', ftSmallint, 0, False, '0');
               Add('TotalJkyOddsGt5WinPct', ftFloat, 0, False, '0');
               Add('TotalJkyFavStarts', ftSmallint, 0, False, '0');
               Add('TotalJkyFavWins', ftSmallint, 0, False, '0');
               Add('TotalJkyFavWinPct', ftFloat, 0, False, '0');
               Add('TotalJky2yoStarts', ftSmallint, 0, False, '0');
               Add('TotalJky2yoWins', ftSmallint, 0, False, '0');
               Add('TotalJky2yoWinPct', ftFloat, 0, False, '0');
               Add('TotalOwnStarts', ftSmallint, 0, False, '0');
               Add('TotalOwnWins', ftSmallint, 0, False, '0');
               Add('TotalOwnWinPct', ftFloat, 0, False, '0');
               Add('TotalOwnWinPctRank', ftSmallint, 0, False, '0');
               Add('TotalBrdStarts', ftSmallint, 0, False, '0');
               Add('TotalBrdWins', ftSmallint, 0, False, '0');
               Add('TotalBrdWinPct', ftFloat, 0, False, '0');
               Add('TotalBrdWinPctRank', ftSmallint, 0, False, '0');
               Add('BredIn', ftString, 6);
               Add('Sire', ftString, 16);
               Add('SireTurfLastYearRank', ftSmallint, 0, False, '0');
               Add('SireTurfLastYearStarts', ftSmallint, 0, False, '0');
               Add('SireTurfLastYearPctOfEarnings', ftSmallint, 0, False, '0');
               Add('SireGeneralLastYearRank', ftSmallint, 0, False, '0');
               Add('SireGeneralLastYearStudFee', ftFloat, 0, False, '0');
               Add('SireJuvenileLastYearRank', ftSmallint, 0, False, '0');
               Add('SireTurfThisYearRank', ftSmallint, 0, False, '0');
               Add('SireTurfThisYearStarts', ftSmallint, 0, False, '0');
               Add('SireTurfThisYearPctOfEarnings', ftSmallint, 0, False, '0');
               Add('SireGeneralThisYearRank', ftSmallint, 0, False, '0');
               Add('SireGeneralThisYearStudFee', ftFloat, 0, False, '0');
               Add('SireJuvenileThisYearRank', ftSmallint, 0, False, '0');
               Add('Dam', ftString, 16);
               Add('DamSire', ftString, 16);
               Add('DaysLast', ftSmallint, 0, False, '0');
               Add('DaysLastWork', ftSmallint, 0, False, '0');
               Add('DaysLastWork2', ftSmallint, 0, False, '0');
               Add('DaysLastWork3', ftSmallint, 0, False, '0');
               Add('NbrWorksLast', ftSmallint, 0, False, '0');
               Add('StartsWorks21', ftSmallint, 0, False, '0');
               Add('LastTrkCode', ftString, 3);
               Add('LastRaceNbr', ftInteger, 0, False, '0');
               Add('LastRaceDate', ftDate);
               Add('LastPostPos', ftSmallint, 0, False, '0');
               Add('LastRaceType', ftString, 6);
               Add('LastSurf', ftString, 1);
               Add('LastRaceConditions', ftString, 20);
               Add('LastDistanceDesc', ftString, 16);
               Add('LastDistance', ftFloat, 0, False, '0');
               Add('LastOdds', ftFloat, 0, False, '0');
               Add('LastFavoriteIndicator', ftString, 21);
               Add('LastDQIndicator', ftString, 15);
               Add('LastJockey', ftString, 15);
               Add('LastComment', ftString, 22);
               Add('LastComment2', ftString, 67);
               Add('LastTrkCond', ftString, 11);
               Add('LastClmPrice', ftFloat, 0, False, '0');
               Add('LastClaimed', ftString, 1);
               Add('LastPurse', ftFloat, 0, False, '0');
               Add('LastTopFinish1', ftString, 30);
               Add('LastTopFinish2', ftString, 30);
               Add('LastTopFinish3', ftString, 30);
               Add('LastRaceDesc', ftString, 255);
               Add('LastDay', ftString, 2);
               Add('LastMonthDesc', ftString, 3);
               Add('LastYear', ftString, 4);
               Add('LastGateBreak', ftString, 2);
               Add('LastLen1Back', ftString, 7);
               Add('LastLen2Back', ftString, 7);
               Add('LastStLenBack', ftString, 7);
               Add('LastFinishBeaten', ftString, 7);
               Add('LastEquip', ftString, 7);
               Add('LastWeight', ftInteger);
               Add('LastTrackVariant', ftInteger);
               Add('LastClass', ftFloat);
               Add('LastClassRank', ftSmallint);
               Add('LastHorseTime', ftFloat);
               Add('LastSRWinner', ftInteger);
               Add('FinalOrderKey', ftString, 50);
               Add('FinalStarts', ftInteger, 0, False, '0');
               Add('FinalWins', ftInteger, 0, False, '0');
               Add('FinalWinPct', ftFloat, 0, False, '0');
               Add('FinalWinPctRank', ftSmallint, 0, False, '0');
               Add('FinalAvgOdds', ftFloat, 0, False, '0');
               Add('FinalMinOdds', ftFloat, 0, False, '0');
               Add('FinalMaxOdds', ftFloat, 0, False, '0');
               Add('FinalAvgWinOdds', ftFloat, 0, False, '0');
               Add('FinalMinWinOdds', ftFloat, 0, False, '0');
               Add('FinalMaxWinOdds', ftFloat, 0, False, '0');
               Add('FinalValueBet', ftFloat, 0, False, '0');
               Add('FinalIV', ftFloat, 0, False, '0');
               Add('FinalIVRoi', ftFloat, 0, False, '0');
               Add('PrimaryOrderKey', ftString, 50);
               Add('PrimaryStarts', ftInteger, 0, False, '0');
               Add('PrimaryWins', ftInteger, 0, False, '0');
               Add('PrimaryWinPct', ftFloat, 0, False, '0');
               Add('PrimaryWinPctRank', ftSmallint, 0, False, '0');
               Add('PrimaryAvgOdds', ftFloat, 0, False, '0');
               Add('PrimaryMinOdds', ftFloat, 0, False, '0');
               Add('PrimaryMaxOdds', ftFloat, 0, False, '0');
               Add('PrimaryAvgWinOdds', ftFloat, 0, False, '0');
               Add('PrimaryMinWinOdds', ftFloat, 0, False, '0');
               Add('PrimaryMaxWinOdds', ftFloat, 0, False, '0');
               Add('PrimaryValueBet', ftFloat, 0, False, '0');
               Add('PrimaryIV', ftFloat, 0, False, '0');
               Add('PrimaryIVRoi', ftFloat, 0, False, '0');
               Add('SecondaryOrderKey', ftString, 50);
               Add('SecondaryStarts', ftInteger, 0, False, '0');
               Add('SecondaryWins', ftInteger, 0, False, '0');
               Add('SecondaryWinPct', ftFloat, 0, False, '0');
               Add('SecondaryWinPctRank', ftSmallint, 0, False, '0');
               Add('SecondaryAvgOdds', ftFloat, 0, False, '0');
               Add('SecondaryMinOdds', ftFloat, 0, False, '0');
               Add('SecondaryMaxOdds', ftFloat, 0, False, '0');
               Add('SecondaryAvgWinOdds', ftFloat, 0, False, '0');
               Add('SecondaryMinWinOdds', ftFloat, 0, False, '0');
               Add('SecondaryMaxWinOdds', ftFloat, 0, False, '0');
               Add('SecondaryValueBet', ftFloat, 0, False, '0');
               Add('SecondaryIV', ftFloat, 0, False, '0');
               Add('SecondaryIVRoi', ftFloat, 0, False, '0');
               Add('DefaultOrderKey', ftString, 50);
               Add('DefaultStarts', ftInteger, 0, False, '0');
               Add('DefaultWins', ftInteger, 0, False, '0');
               Add('DefaultWinPct', ftFloat, 0, False, '0');
               Add('DefaultWinPctRank', ftSmallint, 0, False, '0');
               Add('DefaultAvgOdds', ftFloat, 0, False, '0');
               Add('DefaultMinOdds', ftFloat, 0, False, '0');
               Add('DefaultMaxOdds', ftFloat, 0, False, '0');
               Add('DefaultAvgWinOdds', ftFloat, 0, False, '0');
               Add('DefaultMinWinOdds', ftFloat, 0, False, '0');
               Add('DefaultMaxWinOdds', ftFloat, 0, False, '0');
               Add('DefaultValueBet', ftFloat, 0, False, '0');
               Add('DefaultIV', ftFloat, 0, False, '0');
               Add('DefaultIVRoi', ftFloat, 0, False, '0');
               Add('EstMorningLineOrderKey', ftString, 50);
               Add('EstMorningLineStarts', ftInteger, 0, False, '0');
               Add('EstMorningLineWins', ftInteger, 0, False, '0');
               Add('EstMorningLineWinPct', ftFloat, 0, False, '0');
               Add('EstMorningLineWinPctRank', ftSmallint, 0, False, '0');
               Add('EstMorningLineAvgOdds', ftFloat, 0, False, '0');
               Add('EstMorningLineMinOdds', ftFloat, 0, False, '0');
               Add('EstMorningLineMaxOdds', ftFloat, 0, False, '0');
               Add('EstMorningLineAvgWinOdds', ftFloat, 0, False, '0');
               Add('EstMorningLineMinWinOdds', ftFloat, 0, False, '0');
               Add('EstMorningLineMaxWinOdds', ftFloat, 0, False, '0');
               Add('EstMorningLineValueBet', ftFloat, 0, False, '0');
               Add('EstMorningLineIV', ftFloat, 0, False, '0');
               Add('EstMorningLineIVRoi', ftFloat, 0, False, '0');
               Add('MorningLineTo1', ftFloat);
               Add('MorningLineTo1Fair', ftFloat);
               Add('MorningLineTo1Probability', ftFloat);
               Add('MorningLineTo1FairProbability', ftFloat);
               Add('MorningLineTo1Rank', ftSmallint);
               Add('IsDirtToTurf', ftBoolean, 0, False, 'False');
               Add('IsTurfToDirt', ftBoolean, 0, False, 'False');
               Add('IsSprToRte', ftBoolean, 0, False, 'False');
               Add('IsRteToSpr', ftBoolean, 0, False, 'False');
               Add('Sire_Rec_Foal', ftString, 9);
               Add('Sire_Rec_Turf', ftString, 9);
               Add('Sire_Rec_2yr', ftString, 9);
               Add('Sire_Rec_Stk', ftString, 9);
               Add('Sire_Rec_OffTrk', ftString, 9);
               Add('Sire_Rec_Fts', ftString, 9);
               Add('Sire_Rec_OfsTrk', ftString, 9);
               Add('Sire_Rec_Ds', ftString, 9);
               Add('Sire_Rec_Dr', ftString, 9);
               Add('Sire_Rec_Ts', ftString, 9);
               Add('Sire_Rec_Tr', ftString, 9);
               Add('Dam_Rec_Foal', ftString, 9);
               Add('Dam_Rec_TurfSt', ftString, 9);
               Add('Dam_Rec_2yr', ftString, 9);
               Add('Dam_Rec_StkSt', ftString, 9);
               Add('Dam_Rec_OffTrk', ftString, 9);
               Add('Dam_Rec_Fts', ftString, 9);
               Add('Dam_Rec_OfsTrk', ftString, 9);
               Add('Dam_Rec_Ds', ftString, 9);
               Add('Dam_Rec_Dr', ftString, 9);
               Add('Dam_Rec_Ts', ftString, 9);
               Add('Dam_Rec_Tr', ftString, 9);
               Add('SireAllWinPct', ftFloat, 0, False, '0');
               Add('SireAllTurfWinPct', ftFloat, 0, False, '0');
               Add('SireAllMudWinPct', ftFloat, 0, False, '0');
               Add('DamAllWinPct', ftFloat, 0, False, '0');
               Add('DamAllTurfWinPct', ftFloat, 0, False, '0');
               Add('DamAllMudWinPct', ftFloat, 0, False, '0');
               Add('DamSireAllWinPct', ftFloat, 0, False, '0');
               Add('DamSireAllTurfWinPct', ftFloat, 0, False, '0');
               Add('DamSireAllMudWinPct', ftFloat, 0, False, '0');
               Add('Dam2yoWinPct', ftSmallint, 0, False, '0');
               Add('Dam2yoWinPctRank', ftSmallint, 0, False, '0');
               Add('DamDebutWinPct', ftSmallint, 0, False, '0');
               Add('DamDebutWinPctRank', ftSmallint, 0, False, '0');
               Add('Sire2yoWinPct', ftSmallint, 0, False, '0');
               Add('Sire2yoWinPctRank', ftSmallint, 0, False, '0');
               Add('SireDebutWinPct', ftSmallint, 0, False, '0');
               Add('SireDebutWinPctRank', ftSmallint, 0, False, '0');
               Add('SireTrfSprWinPct', ftSmallint, 0, False, '0');
               Add('SireTrfSprWinPctRank', ftSmallint, 0, False, '0');
               Add('SireTrfRteWinPct', ftSmallint, 0, False, '0');
               Add('SireTrfRteWinPctRank', ftSmallint, 0, False, '0');
               Add('SireDirtSprWinPct', ftSmallint, 0, False, '0');
               Add('SireDirtSprWinPctRank', ftSmallint, 0, False, '0');
               Add('SireDirtRteWinPct', ftSmallint, 0, False, '0');
               Add('SireDirtRteWinPctRank', ftSmallint, 0, False, '0');
               Add('DamAllWinPctRank', ftSmallint, 0, False, '0');
               Add('DamAllTurfWinPctRank', ftSmallint, 0, False, '0');
               Add('DamAllMudWinPctRank', ftSmallint, 0, False, '0');
               Add('SireAllWinPctRank', ftSmallint, 0, False, '0');
               Add('SireAllTurfWinPctRank', ftSmallint, 0, False, '0');
               Add('SireAllMudWinPctRank', ftSmallint, 0, False, '0');
               Add('DamSireAllWinPctRank', ftSmallint, 0, False, '0');
               Add('DamSireAllTurfWinPctRank', ftSmallint, 0, False, '0');
               Add('DamSireAllMudWinPctRank', ftSmallint, 0, False, '0');
               Add('ClassRating', ftFloat, 0, False, '0');
               Add('ClassRatingRank', ftSmallint, 0, False, '0');
               Add('TurfRating', ftFloat, 0, False, '0');
               Add('TurfRatingRank', ftSmallint, 0, False, '0');
               Add('MudRating', ftFloat, 0, False, '0');
               Add('MudRatingRank', ftSmallint, 0, False, '0');
               Add('LastSpeed', ftSmallint, 0, False, '0');
               Add('LastSpeedRank', ftSmallint, 0, False, '0');
               Add('Power', ftFloat, 0, False, '0');
               Add('PowerRank', ftSmallint, 0, False, '0');
               Add('BackSpeed', ftSmallint, 0, False, '0');
               Add('BackSpeedRank', ftSmallint, 0, False, '0');
               Add('AvgClass', ftFloat, 0, False, '0');
               Add('AvgClassRank', ftSmallint, 0, False, '0');
               Add('AvgSpeed', ftSmallint, 0, False, '0');
               Add('AvgSpeedRank', ftSmallint, 0, False, '0');
               Add('AvgClassRating', ftFloat, 0, False, '0');
               Add('AvgClassRatingRank', ftSmallint, 0, False, '0');
               Add('BackClass', ftFloat, 0, False, '0');
               Add('BackClassRank', ftSmallint, 0, False, '0');
               Add('BackPace1', ftFloat, 0, False, '0');
               Add('BackPace1Rank', ftSmallint, 0, False, '0');
               Add('BackPace2', ftFloat, 0, False, '0');
               Add('BackPace2Rank', ftSmallint, 0, False, '0');
               Add('PastSpeed', ftSmallint, 0, False, '0');
               Add('PastSpeedRank', ftSmallint, 0, False, '0');
               Add('CurrClass', ftFloat);
               Add('CurrClassRank', ftSmallint, 0, False, '0');
               Add('AxcisEarlyPace', ftFloat, 0, False, '0');
               Add('AxcisEarlyPaceRank', ftSmallint, 0, False, '0');
               Add('AxcisEarlyPacePos', ftFloat, 0, False, '9999');
               Add('AxcisEarlyPacePosRank', ftSmallint, 0, False, '0');
               Add('AxcisMiddlePace', ftFloat, 0, False, '0');
               Add('AxcisMiddlePaceRank', ftSmallint, 0, False, '0');
               Add('AxcisMiddlePacePos', ftFloat, 0, False, '9999');
               Add('AxcisMiddlePacePosRank', ftSmallint, 0, False, '0');
               Add('AxcisLatePace', ftFloat, 0, False, '0');
               Add('AxcisLatePaceRank', ftSmallint, 0, False, '0');
               Add('AxcisLatePacePos', ftFloat, 0, False, '9999');
               Add('AxcisLatePacePosRank', ftSmallint, 0, False, '0');
               Add('EarlyPace', ftFloat, 0, False, '0');
               Add('EarlyPaceRank', ftSmallint, 0, False, '0');
               Add('EarlyPacePos', ftFloat, 0, False, '9999');
               Add('EarlyPacePosRank', ftSmallint, 0, False, '0');
               Add('EarlyPaceO', ftFloat, 0, False, '0');
               Add('EarlyPaceORank', ftSmallint, 0, False, '0');
               Add('EarlyPacePosO', ftFloat, 0, False, '9999');
               Add('EarlyPacePosORank', ftSmallint, 0, False, '0');
               Add('EarlyPaceH', ftFloat, 0, False, '0');
               Add('EarlyPaceHRank', ftSmallint, 0, False, '0');
               Add('EarlyPacePosH', ftFloat, 0, False, '9999');
               Add('EarlyPacePosHRank', ftSmallint, 0, False, '0');
               Add('MiddlePace', ftFloat, 0, False, '0');
               Add('MiddlePaceRank', ftSmallint, 0, False, '0');
               Add('MiddlePacePos', ftFloat, 0, False, '9999');
               Add('MiddlePacePosRank', ftSmallint, 0, False, '0');
               Add('MiddlePaceO', ftFloat, 0, False, '0');
               Add('MiddlePaceORank', ftSmallint, 0, False, '0');
               Add('MiddlePacePosO', ftFloat, 0, False, '9999');
               Add('MiddlePacePosORank', ftSmallint, 0, False, '0');
               Add('MiddlePaceH', ftFloat, 0, False, '0');
               Add('MiddlePaceHRank', ftSmallint, 0, False, '0');
               Add('MiddlePacePosH', ftFloat, 0, False, '9999');
               Add('MiddlePacePosHRank', ftSmallint, 0, False, '0');
               Add('LatePace', ftFloat, 0, False, '0');
               Add('LatePaceRank', ftSmallint, 0, False, '0');
               Add('LatePacePos', ftFloat, 0, False, '9999');
               Add('LatePacePosRank', ftSmallint, 0, False, '0');
               Add('LatePaceH', ftFloat, 0, False, '0');
               Add('LatePaceHRank', ftSmallint, 0, False, '0');
               Add('LatePacePosH', ftFloat, 0, False, '9999');
               Add('LatePacePosHRank', ftSmallint, 0, False, '0');
               Add('LatePaceO', ftFloat, 0, False, '0');
               Add('LatePaceORank', ftSmallint, 0, False, '0');
               Add('LatePacePosO', ftFloat, 0, False, '9999');
               Add('LatePacePosORank', ftSmallint, 0, False, '0');
               Add('FinishPacePos', ftFloat, 0, False, '0');
               Add('FinishPacePosRank', ftSmallint, 0, False, '0');
               Add('EarlyPaceAdvantage', ftFloat, 0, False, '0');
               Add('MiddlePaceAdvantage', ftFloat, 0, False, '0');
               Add('LatePaceAdvantage', ftFloat, 0, False, '0');
               Add('Speed1Back', ftSmallint, 0, False, '0');
               Add('Speed2Back', ftSmallint, 0, False, '0');
               Add('Speed3Back', ftSmallint, 0, False, '0');
               Add('Speed4Back', ftSmallint, 0, False, '0');
               Add('Speed5Back', ftSmallint, 0, False, '0');
               Add('TimesSpdDeclined', ftSmallint, 0, False, '0');
               Add('IsClaimed1Back', ftBoolean, 0, False, 'False');
               Add('IsClaimed2Back', ftBoolean, 0, False, 'False');
               Add('IsLayoffAndUp', ftBoolean, 0, False, 'False');
               Add('IsClaimedAndUp', ftBoolean, 0, False, 'False');
               Add('IsClaimedAndDown', ftBoolean, 0, False, 'False');
               Add('IsFirstTimeClaiming', ftBoolean, 0, False, 'False');
               Add('IsBelowClaimedPrice', ftBoolean, 0, False, 'False');
               Add('LifeStarts', ftSmallint, 0, False, '0');
               Add('LifeWins', ftSmallint, 0, False, '0');
               Add('LifePlcs', ftSmallint, 0, False, '0');
               Add('LifeShos', ftSmallint, 0, False, '0');
               Add('LifeEarnings', ftInteger, 0, False, '0');
               Add('LifeEPS', ftInteger, 0, False, '0');
               Add('TurfStarts', ftSmallint, 0, False, '0');
               Add('TurfWins', ftSmallint, 0, False, '0');
               Add('TurfPlcs', ftSmallint, 0, False, '0');
               Add('TurfShos', ftSmallint, 0, False, '0');
               Add('TurfEarnings', ftInteger, 0, False, '0');
               Add('TurfEPS', ftInteger, 0, False, '0');
               Add('MudStarts', ftSmallint, 0, False, '0');
               Add('MudWins', ftSmallint, 0, False, '0');
               Add('MudPlcs', ftSmallint, 0, False, '0');
               Add('MudShos', ftSmallint, 0, False, '0');
               Add('MudEarnings', ftInteger, 0, False, '0');
               Add('MudEPS', ftInteger, 0, False, '0');
               Add('TrkStarts', ftSmallint, 0, False, '0');
               Add('TrkWins', ftSmallint, 0, False, '0');
               Add('TrkPlcs', ftSmallint, 0, False, '0');
               Add('TrkShos', ftSmallint, 0, False, '0');
               Add('TrkEarnings', ftInteger, 0, False, '0');
               Add('TrkEPS', ftInteger, 0, False, '0');
               Add('RouteStarts', ftSmallint, 0, False, '0');
               Add('RouteWins', ftSmallint, 0, False, '0');
               Add('RoutePlcs', ftSmallint, 0, False, '0');
               Add('RouteShos', ftSmallint, 0, False, '0');
               Add('SprintStarts', ftSmallint, 0, False, '0');
               Add('SprintWins', ftSmallint, 0, False, '0');
               Add('SprintPlcs', ftSmallint, 0, False, '0');
               Add('SprintShos', ftSmallint, 0, False, '0');
               Add('Pk3Choice', ftFloat, 0, False, '0');
               Add('TriChoice', ftFloat, 0, False, '0');
               Add('SuperChoice', ftFloat, 0, False, '0');
               Add('DDChoice', ftFloat, 0, False, '0');
               Add('ValueChoice', ftSmallint, 0, False, '0');
               Add('AngleChoice', ftInteger, 0, False, '0');
               Add('AngleDesc', ftString, 100);
               Add('TipChoice', ftInteger, 0, False, '0');
               Add('IsCreateAngle', ftBoolean, 0, False, 'False');
               Add('IsCreateTip', ftBoolean, 0, False, 'False');
               Add('IsCreateAlt', ftBoolean, 0, False, 'False');
               Add('IsCreatePK3', ftBoolean, 0, False, 'False');
               Add('IsCreateDetail', ftBoolean, 0, False, 'False');
               Add('IsCreateValue', ftBoolean, 0, False, 'False');
               Add('IsPlayableValue', ftBoolean, 0, False, 'False');
               Add('IsFinalValue', ftBoolean, 0, False, 'False');
               Add('IsChalkValue', ftBoolean, 0, False, 'False');
               Add('IsOverlaySheetSelected', ftBoolean, 0, False, 'False');
               Add('IsWagerSheetSelected', ftBoolean, 0, False, 'False');
               Add('IsYouBetTrack', ftBoolean, 0, False, 'False');
               Add('IsLinerSheetSelected', ftBoolean, 0, False, 'False');
               Add('IsPrintedOnAngleSheet', ftBoolean, 0, False, 'False');
               Add('IsPrintedOnValueSheet', ftBoolean, 0, False, 'False');
               Add('HorseNbr', ftSmallint, 0, False, '0');
               Add('WorkLine1', ftString, 250);
               Add('WorkLine2', ftString, 250);
               Add('Wager', ftString, 10);
               Add('WagerAmt', ftInteger, 0, False, '0');
               Add('PlcWagerAmt', ftSmallint, 0, False, '0');
               Add('ShoWagerAmt', ftSmallint, 0, False, '0');
               Add('IsDollar', ftBoolean, 0, False, 'False');
               Add('IsDoubleDollar', ftBoolean, 0, False, 'False');
               Add('IsFrontDoubleLiner', ftBoolean, 0, False, 'False');
               Add('IsBackDoubleLiner', ftBoolean, 0, False, 'False');
               Add('IsTripleLiner', ftBoolean, 0, False, 'False');
               Add('IsFrontDoubleDot', ftBoolean, 0, False, 'False');
               Add('IsBackDoubleDot', ftBoolean, 0, False, 'False');
               Add('IsTripleDot', ftBoolean, 0, False, 'False');
               Add('IsFrontDoubleLiner0', ftBoolean, 0, False, 'False');
               Add('IsBackDoubleLiner0', ftBoolean, 0, False, 'False');
               Add('IsTripleLiner0', ftBoolean, 0, False, 'False');
               Add('IsFrontDoubleLiner1', ftBoolean, 0, False, 'False');
               Add('IsBackDoubleLiner1', ftBoolean, 0, False, 'False');
               Add('IsTripleLiner1', ftBoolean, 0, False, 'False');
               Add('IsFrontDoubleLiner2', ftBoolean, 0, False, 'False');
               Add('IsBackDoubleLiner2', ftBoolean, 0, False, 'False');
               Add('IsTripleLiner2', ftBoolean, 0, False, 'False');
               Add('IsFrontDoubleLiner3', ftBoolean, 0, False, 'False');
               Add('IsBackDoubleLiner3', ftBoolean, 0, False, 'False');
               Add('IsTripleLiner3', ftBoolean, 0, False, 'False');
               Add('LinerKeyByTrkAll', ftString, 40);
               Add('LinerStartsByTrkAll', ftInteger, 0, False, '0');
               Add('LinerWinsByTrkAll', ftInteger, 0, False, '0');
               Add('LinerWinPctByTrkAll', ftFloat, 0, False, '0');
               Add('LinerAvgOddsByTrkAll', ftFloat, 0, False, '0');
               Add('LinerMinOddsByTrkAll', ftFloat, 0, False, '0');
               Add('LinerMaxOddsByTrkAll', ftFloat, 0, False, '0');
               Add('LinerAvgWinOddsByTrkAll', ftFloat, 0, False, '0');
               Add('LinerMinWinOddsByTrkAll', ftFloat, 0, False, '0');
               Add('LinerMaxWinOddsByTrkAll', ftFloat, 0, False, '0');
               Add('LinerValueBetByTrkAll', ftFloat, 0, False, '0');
               Add('LinerIVByTrkAll', ftFloat, 0, False, '0');
               Add('LinerIVRoiByTrkAll', ftFloat, 0, False, '0');
               Add('LinerKeyByTrk0To3', ftString, 40);
               Add('LinerStartsByTrk0To3', ftInteger, 0, False, '0');
               Add('LinerWinsByTrk0To3', ftInteger, 0, False, '0');
               Add('LinerWinPctByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerValueBetByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerAvgOddsByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerMinOddsByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerMaxOddsByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerAvgWinOddsByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerMinWinOddsByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerMaxWinOddsByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerIVByTrk0To3', ftFloat, 0, False, '0');
               Add('LinerIVRoiByTrk0To3', ftFloat, 0, False, '0');
               Add('TodaysWagerOrderKey', ftString, 50);
               Add('TodaysWagerStarts', ftInteger, 0, False, '0');
               Add('TodaysWagerWins', ftInteger, 0, False, '0');
               Add('TodaysWagerWinPct', ftFloat, 0, False, '0');
               Add('TodaysWagerWinPctRank', ftSmallint, 0, False, '0');
               Add('TodaysWagerAvgOdds', ftFloat, 0, False, '0');
               Add('TodaysWagerMinOdds', ftFloat, 0, False, '0');
               Add('TodaysWagerMaxOdds', ftFloat, 0, False, '0');
               Add('TodaysWagerAvgWinOdds', ftFloat, 0, False, '0');
               Add('TodaysWagerMinWinOdds', ftFloat, 0, False, '0');
               Add('TodaysWagerMaxWinOdds', ftFloat, 0, False, '0');
               Add('TodaysWagerValueBet', ftFloat, 0, False, '0');
               Add('TodaysWagerIV', ftFloat, 0, False, '0');
               Add('TodaysWagerIVRoi', ftFloat, 0, False, '0');
               Add('TodaysWagerLineTo1', ftFloat, 0, False, '0');
               Add('TodaysWagerLineTo1Probability', ftFloat, 0, False, '0');
               Add('TodaysWagerLineTo1Fair', ftFloat, 0, False, '0');
               Add('TodaysWagerLineTo1FairProbability', ftFloat, 0, False, '0');
               Add('TodaysWagerME', ftFloat, 0, False, '0');
               Add('TodaysWagerKellyPct', ftFloat, 0, False, '0');
               Add('TodaysWagerExpectedProfitLossPct', ftFloat, 0, False, '0');
               Add('LinerIVAvgOddsByTrkAll', ftFloat, 0, False, '0');
               Add('LinerIVAvgOddsByTrk0To3', ftFloat, 0, False, '0');
               Add('Last2TrkCode', ftString, 3);
               Add('Last2RaceNbr', ftInteger, 0, False, '0');
               Add('Last2RaceDate', ftDate);
               Add('Last2PostPos', ftSmallint, 0, False, '0');
               Add('Last2RaceType', ftString, 6);
               Add('Last2Surf', ftString, 1);
               Add('Last2RaceConditions', ftString, 20);
               Add('Last2DistanceDesc', ftString, 16);
               Add('Last2Distance', ftFloat, 0, False, '0');
               Add('Last2Odds', ftFloat, 0, False, '0');
               Add('Last2FavoriteIndicator', ftString, 21);
               Add('Last2DQIndicator', ftString, 15);
               Add('Last2Jockey', ftString, 15);
               Add('Last2Comment', ftString, 22);
               Add('Last2Comment2', ftString, 67);
               Add('Last2TrkCond', ftString, 11);
               Add('Last2ClmPrice', ftFloat, 0, False, '0');
               Add('Last2Claimed', ftString, 1);
               Add('Last2Purse', ftFloat, 0, False, '0');
               Add('Last2TopFinish1', ftString, 30);
               Add('Last2TopFinish2', ftString, 30);
               Add('Last2TopFinish3', ftString, 30);
               Add('Last2RaceDesc', ftString, 255);
               Add('Last2Day', ftString, 2);
               Add('Last2MonthDesc', ftString, 3);
               Add('Last2Year', ftString, 4);
               Add('Last2GateBreak', ftString, 2);
               Add('Last2Len1Back', ftString, 7);
               Add('Last2Len2Back', ftString, 7);
               Add('Last2StLenBack', ftString, 7);
               Add('Last2FinishBeaten', ftString, 7);
               Add('Last2Equip', ftString, 7);
               Add('Last2Weight', ftInteger);
               Add('Last2TrackVariant', ftInteger);
               Add('Last2Class', ftFloat);
               Add('Last2Speed', ftInteger);
               Add('Last2HorseTime', ftFloat);
               Add('Last2SRWinner', ftInteger);
               Add('Last3TrkCode', ftString, 3);
               Add('Last3RaceNbr', ftInteger, 0, False, '0');
               Add('Last3RaceDate', ftDate);
               Add('Last3PostPos', ftSmallint, 0, False, '0');
               Add('Last3RaceType', ftString, 6);
               Add('Last3Surf', ftString, 1);
               Add('Last3RaceConditions', ftString, 20);
               Add('Last3DistanceDesc', ftString, 16);
               Add('Last3Distance', ftFloat, 0, False, '0');
               Add('Last3Odds', ftFloat, 0, False, '0');
               Add('Last3FavoriteIndicator', ftString, 21);
               Add('Last3DQIndicator', ftString, 15);
               Add('Last3Jockey', ftString, 15);
               Add('Last3Comment', ftString, 22);
               Add('Last3Comment2', ftString, 67);
               Add('Last3TrkCond', ftString, 11);
               Add('Last3ClmPrice', ftFloat, 0, False, '0');
               Add('Last3Claimed', ftString, 1);
               Add('Last3Purse', ftFloat, 0, False, '0');
               Add('Last3TopFinish1', ftString, 30);
               Add('Last3TopFinish2', ftString, 30);
               Add('Last3TopFinish3', ftString, 30);
               Add('Last3RaceDesc', ftString, 255);
               Add('Last3Day', ftString, 2);
               Add('Last3MonthDesc', ftString, 3);
               Add('Last3Year', ftString, 4);
               Add('Last3GateBreak', ftString, 2);
               Add('Last3Len1Back', ftString, 7);
               Add('Last3Len2Back', ftString, 7);
               Add('Last3StLenBack', ftString, 7);
               Add('Last3FinishBeaten', ftString, 7);
               Add('Last3Equip', ftString, 7);
               Add('Last3Weight', ftInteger);
               Add('Last3TrackVariant', ftInteger);
               Add('Last3Class', ftFloat);
               Add('Last3Speed', ftInteger);
               Add('Last3HorseTime', ftFloat);
               Add('Last3SRWinner', ftSmallint);
               Add('Odds', ftFloat, 0, False, '0');
               Add('FinishPos', ftFloat, 0, False, '0');
               Add('TodaysWagerExpectedWinRoi', ftFloat, 0, False, '0');
               Add('QSP1stCall', ftSmallint);
               Add('QSP1stCallRank', ftSmallint);
               Add('QSP1stCallRunStyle', ftString, 2);
               Add('QSP2ndCall', ftSmallint);
               Add('QSP2ndCallRank', ftSmallint);
               Add('QSP2ndCallRunStyle', ftString, 2);
               Add('KSP1stCall', ftSmallint);
               Add('KSP1stCallRank', ftSmallint);
               Add('KSP2ndCall', ftSmallint);
               Add('KSP2ndCallRank', ftSmallint);
               Add('ByTrkEPSRank', ftSmallint);
               Add('ByMudEPSRank', ftSmallint);
               Add('ByTrfEPSRank', ftSmallint);
               Add('IsLastOutMoveOnTurn', ftBoolean, 0, False, 'False');
               Add('DaysLastOutMoveOnTurn', ftInteger, 0, False, '0');
               Add('IsLastOutFFMove', ftBoolean, 0, False, 'False');
               Add('DaysLastOutFFMove', ftInteger, 0, False, '0');
               Add('IsPriorToLastOutMoveOnTurn', ftBoolean, 0, False, 'False');
               Add('DaysPriorToLastOutMoveOnTurn', ftInteger, 0, False, '0');
               Add('IsPriorToLastOutFFMove', ftBoolean, 0, False, 'False');
               Add('DaysPriorToLastOutFFMove', ftInteger, 0, False, '0');
               Add('LastSRWinnerRank', ftInteger, 0, False, '0');
               Add('LastFractionsLine', ftString, 75);
               Add('LastRunningLine', ftString, 75);
               Add('Last2FractionsLine', ftString, 75);
               Add('Last2RunningLine', ftString, 75);
               Add('Last3FractionsLine', ftString, 75);
               Add('Last3RunningLine', ftString, 75);
               Add('LowestWeight', ftInteger, 0, False, '999');
               Add('LastPos1stCall', ftFloat, 0, False, '0');
               Add('LastPos2ndCall', ftFloat, 0, False, '0');
               Add('LastPosStrCall', ftFloat, 0, False, '0');
               Add('Last2Pos1stCall', ftFloat, 0, False, '0');
               Add('Last2Pos2ndCall', ftFloat, 0, False, '0');
               Add('Last2PosStrCall', ftFloat, 0, False, '0');
               Add('Last3Pos1stCall', ftFloat, 0, False, '0');
               Add('Last3Pos2ndCall', ftFloat, 0, False, '0');
               Add('Last3PosStrCall', ftFloat, 0, False, '0');
               Add('LastTime1stCall', ftFloat, 0, False, '0');
               Add('LastTime2ndCall', ftFloat, 0, False, '0');
               Add('LastTimeStrCall', ftFloat, 0, False, '0');
               Add('LastTimeFinCall', ftFloat, 0, False, '0');
               Add('Last2Time1stCall', ftFloat, 0, False, '0');
               Add('Last2Time2ndCall', ftFloat, 0, False, '0');
               Add('Last2TimeStrCall', ftFloat, 0, False, '0');
               Add('Last2TimeFinCall', ftFloat, 0, False, '0');
               Add('Last3Time1stCall', ftFloat, 0, False, '0');
               Add('Last3Time2ndCall', ftFloat, 0, False, '0');
               Add('Last3TimeStrCall', ftFloat, 0, False, '0');
               Add('Last3TimeFinCall', ftFloat, 0, False, '0');
               Add('LastBL1stCall', ftFloat, 0, False, '0');
               Add('LastBL2ndCall', ftFloat, 0, False, '0');
               Add('LastBLStrCall', ftFloat, 0, False, '0');
               Add('LastBLFinCall', ftFloat, 0, False, '0');
               Add('Last2BL1stCall', ftFloat, 0, False, '0');
               Add('Last2BL2ndCall', ftFloat, 0, False, '0');
               Add('Last2BLStrCall', ftFloat, 0, False, '0');
               Add('Last2BLFinCall', ftFloat, 0, False, '0');
               Add('Last3BL1stCall', ftFloat, 0, False, '0');
               Add('Last3BL2ndCall', ftFloat, 0, False, '0');
               Add('Last3BLStrCall', ftFloat, 0, False, '0');
               Add('Last3BLFinCall', ftFloat, 0, False, '0');
               Add('LastPosFinCall', ftFloat, 0, False, '0');
               Add('Last2PosFinCall', ftFloat, 0, False, '0');
               Add('Last3PosFinCall', ftFloat, 0, False, '0');
               Add('IsUpInClass', ftBoolean, 0, False, 'False');
               Add('IsDownInClass', ftBoolean, 0, False, 'False');
               Add('Is1stClaiming', ftBoolean, 0, False, 'False');
               Add('Is1stMCL', ftBoolean, 0, False, 'False');
               Add('IsHiddenWorkout', ftBoolean, 0, False, 'False');
               Add('Is1stAfterLayoff', ftBoolean, 0, False, 'False');
               Add('Is2ndAfterLayoff', ftBoolean, 0, False, 'False');
               Add('Is3rdAfterLayoff', ftBoolean, 0, False, 'False');
               Add('IsDirtToTurfToDirtAfterLayoff', ftBoolean, 0, False, 'False');
               Add('IsTurfToDirtToTurfAfterLayoff', ftBoolean, 0, False, 'False');
               Add('IsRouteToSprintToRouteAfterLayoff', ftBoolean, 0, False, 'False');
               Add('IsSprintToRouteToSprintAfterLayoff', ftBoolean, 0, False, 'False');
               Add('IsOnlySpeed', ftBoolean, 0, False, 'False');
               Add('IsProvenSpeed', ftBoolean, 0, False, 'False');
               Add('IsProvenSpeedPlus', ftBoolean, 0, False, 'False');
               Add('IsXtremeSpeed', ftBoolean, 0, False, 'False');
               Add('IsLastRaceTurnMove', ftBoolean, 0, False, 'False');
               Add('IsLastRaceFinalFurlongMove', ftBoolean, 0, False, 'False');
               Add('IsPrevToLastRaceTurnMove', ftBoolean, 0, False, 'False');
               Add('IsPrevToLastRaceFinalFurlongMove', ftBoolean, 0, False, 'False');
               Add('Is2yoBred', ftBoolean, 0, False, 'False');
               Add('Is1stBred', ftBoolean, 0, False, 'False');
               Add('IsTurfBred', ftBoolean, 0, False, 'False');
               Add('IsQuirinSpeed', ftBoolean, 0, False, 'False');
               Add('IsKleinSpeed', ftBoolean, 0, False, 'False');
               Add('IsKeyRace', ftBoolean, 0, False, 'False');
               Add('IsBouncyBouncy', ftBoolean, 0, False, 'False');
               Add('IsBestEffortLast', ftBoolean, 0, False, 'False');
               Add('IsShipIn', ftBoolean, 0, False, 'False');
               Add('IsVerifiedClaim', ftBoolean, 0, False, 'False');
               Add('IsUltimateFormFactor', ftBoolean, 0, False, 'False');
               Add('IsBetLast', ftBoolean, 0, False, 'False');
               Add('Is1stOffLayoff', ftBoolean, 0, False, 'False');
               Add('Is2ndOffLayoff', ftBoolean, 0, False, 'False');
               Add('Is3rdOffLayoff', ftBoolean, 0, False, 'False');
               Add('IsFormConsistent', ftBoolean, 0, False, 'False');
               Add('IsX1stBred', ftBoolean, 0, False, 'False');
               Add('IsX2yoBred', ftBoolean, 0, False, 'False');
               Add('IsXTurfBred', ftBoolean, 0, False, 'False');
               Add('IsXtremeSpeed2', ftBoolean, 0, False, 'False');
               Add('IsUnexpectedEarlySpeed', ftBoolean, 0, False, 'False');
               Add('IsTrnDebutPlus', ftBoolean, 0, False, 'False');
               Add('IsTrnDebutTwoPlus', ftBoolean, 0, False, 'False');
               Add('IsTrn2yoPlus', ftBoolean, 0, False, 'False');
               Add('IsTrnTurfPlus', ftBoolean, 0, False, 'False');
               Add('IsTrnTodayPlus', ftBoolean, 0, False, 'False');
               Add('IsTrnTodayMinus', ftBoolean, 0, False, 'False');
               Add('IsOnlySpeed2', ftBoolean, 0, False, 'False');
               Add('IsQuirinSpeed2', ftBoolean, 0, False, 'False');
               Add('IsKleinSpeed2', ftBoolean, 0, False, 'False');
               Add('Is2yoBredSheetSelected', ftBoolean, 0, False, 'False');
               Add('IsTurfBredSheetSelected', ftBoolean, 0, False, 'False');
               Add('Is1stBredSheetSelected', ftBoolean, 0, False, 'False');
               Add('IsSpeedSheetSelected', ftBoolean, 0, False, 'False');
               Add('LowestClass', ftFloat, 0, False, '999');
               Add('StandingIn', ftString, 5);
               Add('StandingInRank', ftSmallint, 0, False, '9999');
               Add('IsOnStandingInList', ftBoolean, 0, False, 'False');
            end;
            with IndexDefs do begin
               Clear;
               Add('', 'TrkCode;RaceDate;RaceNbr;PostPos', [ixPrimary, ixUnique], '', icFull);
               Add('ByHorseName', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;HorseName', [ixCaseInsensitive], '', icFull);
               Add('ByRangeRaceDate', 'RangeRaceDate;RaceDate;TrkCode;RaceDate;RaceNbr;PostPos', [], '', icFull);
               Add('ByHorseNbr', 'RangeRaceDate;TrkCode;RaceDate;HorseNbr', [], '', icFull);
               Add('ByMorningLineTo1', 'RangeRaceDate;MorningLineTo1', [], '', icFull);
               Add('ByEstTimeOfRace', 'RangeRaceDate;EstTimeOfRace', [], '', icFull);
               Add('ByProgSortOrder', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;ProgramNbrSort', [], '', icFull);
               Add('ByPrimaryWinPctRank', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;PrimaryWinPct;TrnTrackRank;JkyTrackRank;TrnWinsRank;JkyWinsRank;OwnWinsRank', [ixDescending], 'PrimaryWinPct', icFull);
               Add('BySecondaryWinPctRank', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;SecondaryWinPct;TrnTrackRank;JkyTrackRank;TrnWinsRank;JkyWinsRank;OwnWinsRank', [ixDescending], 'SecondaryWinPct', icFull);
               Add('ByDefaultWinPctRank', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;DefaultWinPct;TrnTrackRank;JkyTrackRank;TrnWinsRank;JkyWinsRank;OwnWinsRank', [ixDescending], 'DefaultWinPct', icFull);
               Add('ByFinalWinPctRank', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;FinalWinPct;TrnTrackRank;JkyTrackRank;TrnWinsRank;JkyWinsRank;OwnWinsRank', [ixDescending], 'FinalWinPct', icFull);
               Add('ByTodaysWagerWinPctRank', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;TodaysWagerWinPct;TrnTrackRank;JkyTrackRank;TrnWinsRank;JkyWinsRank;OwnWinsRank', [ixDescending], 'TodaysWagerWinPct', icFull);
               Add('ByTEst', 'RangeRaceDate;TrkCode;RaceDate;RaceNbr;KSP1stCall', [ixDescending], 'KSP1stCall', icFull);
            end;
            CreateTable(0, 1, 0, False, '', '', 16384, 512, 0)
         end;
      end;
   finally
      TableToCreate.Free;
   end;
end;

end.
