/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "C:\RatingsData31\HorseHistory"
(
   "TrkCode" VARCHAR(3) NOT NULL DEFAULT '0',
   "RaceDate" DATE NOT NULL,
   "RaceNbr" SMALLINT NOT NULL,
   "PostPos" SMALLINT NOT NULL,
   "RaceType" VARCHAR(10),
   "TypeOfRace" VARCHAR(1) DEFAULT 'T',
   "Surface" VARCHAR(1) DEFAULT 'D',
   "TrkCond" VARCHAR(2) DEFAULT 'FT',
   "DistanceInFeet" SMALLINT DEFAULT 0,
   "DistanceInYards" SMALLINT DEFAULT 0,
   "DistanceInFurlongs" FLOAT DEFAULT 0,
   "Purse" FLOAT DEFAULT 0,
   "ClaimingPrice" FLOAT DEFAULT 0,
   "ProgramNbr" VARCHAR(10),
   "ProgNbrSort" SMALLINT DEFAULT 0,
   "MorningLineDesc" VARCHAR(6),
   "MorningLineTo1" FLOAT DEFAULT 0,
   "MorningLineTo1Rank" SMALLINT DEFAULT 0,
   "FinishPos" SMALLINT DEFAULT 0,
   "Odds" FLOAT DEFAULT 0,
   "IsFavorite" BOOLEAN DEFAULT False,
   "HorseName" VARCHAR(25),
   "HorseNbr" SMALLINT DEFAULT 0,
   "Sex" VARCHAR(1),
   "Age" SMALLINT DEFAULT 0,
   "Equip" VARCHAR(10),
   "Med" VARCHAR(5),
   "IsFirstTimeJuice" BOOLEAN DEFAULT False,
   "IsSecondTimeJuice" BOOLEAN DEFAULT False,
   "IsDebut" BOOLEAN DEFAULT False,
   "IsDebutTwo" BOOLEAN DEFAULT False,
   "IsTurfDebut" BOOLEAN DEFAULT False,
   "DebutIndicator" VARCHAR(2),
   "TurfIndicator" VARCHAR(2),
   "MudIndicator" VARCHAR(2),
   "RouteIndicator" VARCHAR(2),
   "IsClaimed1Back" BOOLEAN DEFAULT False,
   "IsClaimed2Back" BOOLEAN DEFAULT False,
   "IsDirtToTurf" BOOLEAN DEFAULT False,
   "IsTurfToDirt" BOOLEAN DEFAULT False,
   "IsSprToRte" BOOLEAN DEFAULT False,
   "IsRteToSpr" BOOLEAN DEFAULT False,
   "Speed1Back" SMALLINT DEFAULT 0,
   "Speed2Back" SMALLINT DEFAULT 0,
   "Speed3Back" SMALLINT DEFAULT 0,
   "Speed4Back" SMALLINT DEFAULT 0,
   "Speed5Back" SMALLINT DEFAULT 0,
   "DaysLast" SMALLINT DEFAULT 0,
   "DaysLastWork" SMALLINT DEFAULT 0,
   "DaysLastWork2" SMALLINT DEFAULT 0,
   "DaysLastWork3" SMALLINT DEFAULT 0,
   "NbrWorksLast" SMALLINT DEFAULT 0,
   "StartsWorks21" SMALLINT DEFAULT 0,
   "JkyEquibaseKey" VARCHAR(10),
   "TrnEquibaseKey" VARCHAR(10),
   "SireName" VARCHAR(16),
   "DamSireName" VARCHAR(16),
   "DamName" VARCHAR(25),
   "BredIn" VARCHAR(6),
   "Owner" VARCHAR(45),
   "Breeder" VARCHAR(67),
   "TrnTodayStarts" SMALLINT DEFAULT 0,
   "TrnTodayWinPct" FLOAT DEFAULT 0,
   "TrnTodayWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnTurfStarts" SMALLINT DEFAULT 0,
   "TotalTrnTurfWinPct" FLOAT DEFAULT 0,
   "TotalTrnTurfWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn10Starts" SMALLINT DEFAULT 0,
   "TotalTrn10WinPct" FLOAT DEFAULT 0,
   "TotalTrn10WinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn30Starts" SMALLINT DEFAULT 0,
   "TotalTrn30WinPct" FLOAT DEFAULT 0,
   "TotalTrn30WinPctRank" SMALLINT DEFAULT 0,
   "TotalJky10Starts" SMALLINT DEFAULT 0,
   "TotalJky10WinPct" FLOAT DEFAULT 0,
   "TotalJky10WinPctRank" SMALLINT DEFAULT 0,
   "TotalJky30Starts" SMALLINT DEFAULT 0,
   "TotalJky30WinPct" FLOAT DEFAULT 0,
   "TotalJky30WinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnStarts" SMALLINT DEFAULT 0,
   "TotalTrnWinPct" FLOAT DEFAULT 0,
   "TotalTrnWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnDaysStarts" SMALLINT DEFAULT 0,
   "TotalTrnDaysWinPct" FLOAT DEFAULT 0,
   "TotalTrnDaysWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnJkyStarts" SMALLINT DEFAULT 0,
   "TotalTrnJkyWinPct" FLOAT DEFAULT 0,
   "TotalTrnJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnJkyDaysStarts" SMALLINT DEFAULT 0,
   "TotalTrnJkyDaysWinPct" FLOAT DEFAULT 0,
   "TotalTrnJkyDaysWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyStarts" SMALLINT DEFAULT 0,
   "TotalJkyWinPct" FLOAT DEFAULT 0,
   "TotalJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyDaysStarts" SMALLINT DEFAULT 0,
   "TotalJkyDaysWinPct" FLOAT DEFAULT 0,
   "TotalJkyDaysWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnOwnStarts" SMALLINT DEFAULT 0,
   "TotalTrnOwnWinPct" FLOAT DEFAULT 0,
   "TotalTrnOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalOwnStarts" SMALLINT DEFAULT 0,
   "TotalOwnWinPct" FLOAT DEFAULT 0,
   "TotalOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalBrdStarts" SMALLINT DEFAULT 0,
   "TotalBrdWinPct" FLOAT DEFAULT 0,
   "TotalBrdWinPctRank" SMALLINT DEFAULT 0,
   "LastSpeed" SMALLINT DEFAULT 0,
   "LastSpeedRank" SMALLINT DEFAULT 0,
   "Power" FLOAT DEFAULT 0,
   "PowerRank" SMALLINT DEFAULT 0,
   "BackSpeed" SMALLINT DEFAULT 0,
   "BackSpeedRank" SMALLINT DEFAULT 0,
   "EarlyPace" FLOAT DEFAULT 0,
   "EarlyPaceRank" SMALLINT DEFAULT 0,
   "EarlyPaceO" FLOAT DEFAULT 0,
   "EarlyPaceORank" SMALLINT DEFAULT 0,
   "EarlyPaceH" FLOAT DEFAULT 0,
   "EarlyPaceHRank" SMALLINT DEFAULT 0,
   "EarlyPacePos" FLOAT DEFAULT 9999,
   "EarlyPacePosRank" SMALLINT DEFAULT 0,
   "EarlyPacePosO" FLOAT DEFAULT 0,
   "EarlyPacePosORank" SMALLINT DEFAULT 0,
   "EarlyPacePosH" FLOAT DEFAULT 0,
   "EarlyPacePosHRank" SMALLINT DEFAULT 0,
   "MiddlePace" FLOAT DEFAULT 0,
   "MiddlePaceRank" SMALLINT DEFAULT 0,
   "MIddlePaceO" FLOAT DEFAULT 0,
   "MiddlePaceORank" SMALLINT DEFAULT 0,
   "MiddlePaceH" FLOAT DEFAULT 0,
   "MiddlePaceHRank" SMALLINT DEFAULT 0,
   "MiddlePacePos" FLOAT DEFAULT 9999,
   "MiddlePacePosRank" SMALLINT DEFAULT 0,
   "MiddlePacePosO" FLOAT DEFAULT 0,
   "MiddlePacePosORank" SMALLINT DEFAULT 0,
   "MiddlePacePosH" FLOAT DEFAULT 0,
   "MIddlePacePosHRank" SMALLINT DEFAULT 0,
   "LatePace" FLOAT DEFAULT 0,
   "LatePaceRank" SMALLINT DEFAULT 0,
   "LatePaceO" FLOAT DEFAULT 0,
   "LatePaceORank" SMALLINT DEFAULT 0,
   "LatePaceH" FLOAT DEFAULT 0,
   "LatePaceHRank" SMALLINT DEFAULT 0,
   "LatePacePos" FLOAT DEFAULT 9999,
   "LatePacePosRank" SMALLINT DEFAULT 0,
   "LatePacePosO" FLOAT DEFAULT 0,
   "LatePacePosORank" SMALLINT DEFAULT 0,
   "LatePacePosH" FLOAT DEFAULT 0,
   "LatePacePosHRank" SMALLINT DEFAULT 0,
   "FinishPacePos" FLOAT DEFAULT 0,
   "FinishPacePosRank" SMALLINT DEFAULT 0,
   "AvgClass" FLOAT DEFAULT 0,
   "AvgClassRank" SMALLINT DEFAULT 0,
   "ClassRating" FLOAT DEFAULT 0,
   "ClassRatingRank" SMALLINT DEFAULT 0,
   "TurfRating" FLOAT DEFAULT 0,
   "TurfRatingRank" SMALLINT DEFAULT 0,
   "MudRating" FLOAT DEFAULT 0,
   "MudRatingRank" SMALLINT DEFAULT 0,
   "FinalOrderKey" VARCHAR(50) DEFAULT '0',
   "FinalStarts" INTEGER DEFAULT 0,
   "FinalWins" INTEGER DEFAULT 0,
   "FinalWinPct" FLOAT DEFAULT 0,
   "FinalWinPctRank" SMALLINT DEFAULT 0,
   "FinalAvgOdds" FLOAT DEFAULT 0,
   "FinalTotalProfitLoss" FLOAT DEFAULT 0,
   "FinalValueBet" FLOAT DEFAULT 0,
   "FinalValueBetRank" SMALLINT DEFAULT 0,
   "FinalValueOdds" FLOAT DEFAULT 0,
   "PrimaryOrderKey" VARCHAR(50),
   "PrimaryStarts" INTEGER DEFAULT 0,
   "PrimaryWins" INTEGER DEFAULT 0,
   "PrimaryWinPct" FLOAT DEFAULT 0,
   "PrimaryWinPctRank" SMALLINT DEFAULT 0,
   "PrimaryAvgOdds" FLOAT DEFAULT 0,
   "PrimaryTotalProfitLoss" FLOAT DEFAULT 0,
   "PrimaryValueBet" FLOAT DEFAULT 0,
   "PrimaryValueBetRank" SMALLINT DEFAULT 0,
   "SecondaryOrderKey" VARCHAR(50),
   "SecondaryStarts" INTEGER DEFAULT 0,
   "SecondaryWins" INTEGER DEFAULT 0,
   "SecondaryWinPct" FLOAT DEFAULT 0,
   "SecondaryWinPctRank" SMALLINT DEFAULT 0,
   "SecondaryAvgOdds" FLOAT DEFAULT 0,
   "SecondaryTotalProfitLoss" FLOAT DEFAULT 0,
   "SecondaryValueBet" FLOAT DEFAULT 0,
   "SecondaryValueBetRank" SMALLINT DEFAULT 0,
   "DefaultOrderKey" VARCHAR(50),
   "DefaultStarts" INTEGER DEFAULT 0,
   "DefaultWins" INTEGER DEFAULT 0,
   "DefaultWinPct" FLOAT DEFAULT 0,
   "DefaultWinPctRank" SMALLINT DEFAULT 0,
   "DefaultAvgOdds" FLOAT DEFAULT 0,
   "DefaultTotalProfitLoss" FLOAT DEFAULT 0,
   "DefaultValueBet" FLOAT DEFAULT 0,
   "DefaultValueBetRank" SMALLINT DEFAULT 0,
   "IsFinalValue" BOOLEAN DEFAULT False,
   "IsChalkValue" BOOLEAN DEFAULT False,
   "IsPlayableValue" BOOLEAN DEFAULT False,
   "DamAllWinPct" FLOAT DEFAULT 0,
   "DamAllWinPctRank" SMALLINT DEFAULT 0,
   "DamAllTurfWinPct" FLOAT DEFAULT 0,
   "DamAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "DamAllMudWinPct" FLOAT DEFAULT 0,
   "DamAllMudWinPctRank" SMALLINT DEFAULT 0,
   "SireAllWinPct" FLOAT DEFAULT 0,
   "SireAllWinPctRank" SMALLINT DEFAULT 0,
   "SireAllTurfWinPct" FLOAT DEFAULT 0,
   "SireAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "SireAllMudWinPct" FLOAT DEFAULT 0,
   "SireAllMudWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllWinPct" FLOAT DEFAULT 0,
   "DamSireAllWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllTurfWinPct" FLOAT DEFAULT 0,
   "DamSireAllTurfWinPctRank" SMALLINT DEFAULT 0,
   "DamSireAllMudWinPct" FLOAT DEFAULT 0,
   "DamSireAllMudWinPctRank" SMALLINT DEFAULT 0,
   "TodaysClass" SMALLINT DEFAULT 0,
   "AvgSpeed" SMALLINT DEFAULT 0,
   "AvgSpeedRank" SMALLINT DEFAULT 0,
   "AvgClassRating" SMALLINT DEFAULT 0,
   "AvgClassRatingRank" SMALLINT DEFAULT 0,
   "BackClass" SMALLINT DEFAULT 0,
   "BackClassRank" SMALLINT DEFAULT 0,
   "BackPace1" FLOAT DEFAULT 0,
   "BackPace1Rank" INTEGER DEFAULT 0,
   "BackPace2" FLOAT DEFAULT 0,
   "BackPace2Rank" INTEGER DEFAULT 0,
   "PastSpeed" SMALLINT DEFAULT 0,
   "PastSpeedRank" SMALLINT DEFAULT 0,
   "TotalTrnOddsStarts" INTEGER DEFAULT 0,
   "TotalTrnOddsWinPct" FLOAT DEFAULT 0,
   "TotalTrnOddsWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyOddsStarts" INTEGER,
   "TotalJkyOddsWinPct" FLOAT DEFAULT 0,
   "TotalJkyOddsWinPctRank" SMALLINT DEFAULT 0,
   "CurrClass" SMALLINT DEFAULT 0,
   "CurrClassRank" SMALLINT DEFAULT 0,
   "BaseRPI" FLOAT DEFAULT 0,
   "BaseRPIRank" SMALLINT DEFAULT 0,
   "TurfRPI" FLOAT DEFAULT 0,
   "TurfRPIRank" SMALLINT DEFAULT 0,
   "MudRPI" FLOAT DEFAULT 0,
   "MudRPIRank" SMALLINT DEFAULT 0,
   "MaidenRPI" FLOAT DEFAULT 0,
   "MaidenRPIRank" SMALLINT DEFAULT 0,
   "ConnectionRPI" FLOAT DEFAULT 0,
   "ConnectionRPIRank" SMALLINT DEFAULT 0,
   "BaseIV" FLOAT DEFAULT 0,
   "BaseIVRank" SMALLINT DEFAULT 0,
   "MudIV" FLOAT DEFAULT 0,
   "MudIVRank" SMALLINT DEFAULT 0,
   "TurfIV" FLOAT DEFAULT 0,
   "TurfIVRank" SMALLINT DEFAULT 0,
   "MaidenIV" FLOAT DEFAULT 0,
   "MaidenIVRank" VARCHAR(10) DEFAULT '0',
   "ConnectionIV" FLOAT DEFAULT 0,
   "ConnectionIVRank" SMALLINT DEFAULT 0,
   "PaceIV" FLOAT DEFAULT 0,
   "PaceIVRank" SMALLINT DEFAULT 0,
   "PacePosIV" FLOAT DEFAULT 0,
   "PacePosIVRank" SMALLINT DEFAULT 0,
   "SpeedIV" FLOAT DEFAULT 0,
   "SpeedIVRank" SMALLINT DEFAULT 0,
   "ClassIV" FLOAT DEFAULT 0,
   "ClassIVRank" SMALLINT DEFAULT 0,
   "SpeedPoints" FLOAT DEFAULT 0,
   "SpeedPointsRank" SMALLINT DEFAULT 0,
   "PDQPaceRating" FLOAT DEFAULT 0,
   "PDQPaceRatingRank" SMALLINT DEFAULT 0,
   "TotalTrnFavStarts" SMALLINT DEFAULT 0,
   "TotalTrnFavWinPct" SMALLINT DEFAULT 0,
   "FrontDoubleLinerStarts" INTEGER DEFAULT 0,
   "FrontDoubleLinerWins" SMALLINT DEFAULT 0,
   "FrontDoubleLinerWinPct" FLOAT DEFAULT 0,
   "FrontDoubleLinerValueBet" FLOAT DEFAULT 0,
   "FrontDoubleLinerStartsByTrk" INTEGER DEFAULT 0,
   "FrontDoubleLinerWinsByTrk" SMALLINT DEFAULT 0,
   "FrontDoubleLinerWinPctByTrk" FLOAT DEFAULT 0,
   "FrontDoubleLinerValueBetByTrk" FLOAT DEFAULT 0,
   "IsSuperTrainer" BOOLEAN DEFAULT False,
   "IsSuperJockey" BOOLEAN DEFAULT False,
   "IsSuperOwner" BOOLEAN DEFAULT False,
   "IsDollar" BOOLEAN DEFAULT False,
   "IsDoubleDollar" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner0" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner1" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner2" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner3" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner0" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner1" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner2" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner3" BOOLEAN DEFAULT False,
   "IsTripleLiner0" BOOLEAN DEFAULT False,
   "IsTripleLiner1" BOOLEAN DEFAULT False,
   "IsTripleLiner2" BOOLEAN DEFAULT False,
   "IsTripleLiner3" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner" BOOLEAN DEFAULT False,
   "IsTripleDot" BOOLEAN DEFAULT False,
   "IsFrontDoubleDot" BOOLEAN DEFAULT False,
   "IsBackDoubleDot" BOOLEAN DEFAULT False,
   "IsTripleLiner" BOOLEAN DEFAULT False,
   "IsAngleSheetSelected" BOOLEAN DEFAULT False,
   "IsTipSheetSelected" BOOLEAN DEFAULT False,
   "IsPrintedOnValueSheet" BOOLEAN DEFAULT False,
   "IsPrintedOnAngleSheet" BOOLEAN DEFAULT False,
   "IsYouBetTrack" BOOLEAN DEFAULT True,
   "IsLayoffAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndDown" BOOLEAN DEFAULT False,
   "IsFirstTimeClaiming" BOOLEAN DEFAULT False,
   "IsBelowClaimedPrice" BOOLEAN DEFAULT False,
   "WagerAmt" SMALLINT DEFAULT 0,
   "Wager" VARCHAR(10) DEFAULT 'NO BET',
   "WagerProfitLoss" FLOAT DEFAULT 0,
   "ValueChoice" SMALLINT DEFAULT 0,
   "Pk3Choice" FLOAT DEFAULT 0,
   "TriChoice" FLOAT DEFAULT 0,
   "AngleChoice" SMALLINT DEFAULT 0,
   "TipChoice" SMALLINT DEFAULT 0,
   "FinalSheetOrder" SMALLINT DEFAULT 0,
   "FinalSheetOrderRank" SMALLINT DEFAULT 0,
   "TrnTurfToDirtStarts" SMALLINT DEFAULT 0,
   "TrnTurfToDirtWinPct" SMALLINT DEFAULT 0,
   "TrnDirtToTurfStarts" SMALLINT DEFAULT 0,
   "TrnDirtToTurfWinPct" SMALLINT DEFAULT 0,
   "TrnRteToSprStarts" SMALLINT DEFAULT 0,
   "TrnRteToSprWinPct" SMALLINT DEFAULT 0,
   "TrnSprToRteStarts" SMALLINT DEFAULT 0,
   "TrnSprToRteWinPct" SMALLINT DEFAULT 0,
   "TotalTrnDebutStarts" SMALLINT DEFAULT 0,
   "TotalTrnDebutWinPct" SMALLINT DEFAULT 0,
   "TotalTrnDebutTwoStarts" SMALLINT DEFAULT 0,
   "TotalTrnDebutTwoWinPct" SMALLINT DEFAULT 0,
   "TotalTrn91PlusStarts" SMALLINT DEFAULT 0,
   "TotalTrn91PlusWinPct" SMALLINT DEFAULT 0,
   "TotalTrnWork91PlusStarts" SMALLINT DEFAULT 0,
   "TotalTrnWork91PlusWinPct" SMALLINT DEFAULT 0,
   "TotalTrnAftClmStarts" SMALLINT DEFAULT 0,
   "TotalTrnAftClmWinPct" SMALLINT DEFAULT 0,
   "TotalTrnFirstJuiceStarts" SMALLINT DEFAULT 0,
   "TotalTrnFirstJuiceWinPct" SMALLINT DEFAULT 0,
   "TotalTrnSecondJuiceStarts" SMALLINT DEFAULT 0,
   "TotalTrnSecondJuiceWinPct" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOnStarts" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOnWinPct" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOffStarts" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOffWinPct" SMALLINT DEFAULT 0,
   "TotalTrnClaimed1BackStarts" SMALLINT DEFAULT 0,
   "TotalTrnClaimed1BackWinPct" SMALLINT DEFAULT 0,
   "TotalTrnClaimed2BackStarts" SMALLINT DEFAULT 0,
   "TotalTrnClaimed2BackWinPct" SMALLINT DEFAULT 0,
   "LastTrkCode" VARCHAR(3),
   "LastRaceNbr" SMALLINT DEFAULT 0,
   "LastRaceDate" DATE,
   "LastPostPos" SMALLINT DEFAULT 0,
   "LastRaceType" VARCHAR(6),
   "LastDistance" FLOAT DEFAULT 0,
   "LastSurf" VARCHAR(1) DEFAULT 'D',
   "LastClaimed" VARCHAR(1) DEFAULT 'False',
   "LastClmPrice" FLOAT DEFAULT 0,
   "LastPurse" FLOAT DEFAULT 0,
   "LastOdds" FLOAT DEFAULT 0,
   "LastFinishPos" SMALLINT DEFAULT 0,
   "LastFavoriteIndicator" VARCHAR(1),
   "LastTrkCond" VARCHAR(2) DEFAULT 'FT',
   "LastRaceKeyStarters" SMALLINT DEFAULT 0,
   "LastRaceKeyWinners" SMALLINT DEFAULT 0,
   "AngleDesc" VARCHAR(10),
   "RouteStarts" SMALLINT DEFAULT 0,
   "SprintStarts" SMALLINT DEFAULT 0,
   "IsBlinkersOn" BOOLEAN DEFAULT False,
   "IsBlinkersOff" BOOLEAN DEFAULT False,
   "LastEquip" VARCHAR(7),
   "ValueIndicator" VARCHAR(2),
   "EstTimeOfRace" TIME,
   "EstTimeOfFirstRace" TIME,
PRIMARY KEY ("TrkCode","RaceDate","RaceNbr","PostPos") COMPRESS FULL
DESCRIPTION 'Horse History'
LOCALE CODE 0
USER MAJOR VERSION 4
);

CREATE INDEX IF NOT EXISTS "ByRaceDate" ON "C:\RatingsData31\HorseHistory" ("RaceDate") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByHorseName" ON "C:\RatingsData31\HorseHistory" ("HorseName") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByFinalWinPctRank" ON "C:\RatingsData31\HorseHistory" ("TrkCode","RaceDate","RaceNbr","FinalWinPct" DESC,"Power" DESC) COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByProgramNbr" ON "C:\RatingsData31\HorseHistory" ("TrkCode","RaceDate","RaceNbr","ProgramNbr") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByRaceDateTrkCode" ON "C:\RatingsData31\HorseHistory" ("RaceDate","TrkCode","RaceNbr","PostPos") COMPRESS FULL;
CREATE INDEX IF NOT EXISTS "ByRangeRaceDate" ON "C:\RatingsData31\HorseHistory" 
("RaceDate","TrkCode","RaceDate","RaceNbr","PostPos") COMPRESS FULL;
