/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "Entry"
(
   "TrkCode" VARCHAR(3) NOT NULL,
   "RaceDate" DATE NOT NULL,
   "RangeRaceDate" DATE,
   "RaceNbr" SMALLINT NOT NULL,
   "PostPos" SMALLINT NOT NULL,
   "RaceType" VARCHAR(4),
   "Surface" VARCHAR(1),
   "EstTimeOfRace" TIME,
   "DistanceInFurlongs" FLOAT,
   "Entry" VARCHAR(5),
   "ProgramNbr" VARCHAR(10),
   "ProgramNbrSort" SMALLINT,
   "MorningLineDesc" VARCHAR(15),
   "HorseName" VARCHAR(25),
   "Med" VARCHAR(5),
   "Equip" VARCHAR(6),
   "IsFirstTimeJuice" BOOLEAN DEFAULT False,
   "IsBlinkersOn" BOOLEAN DEFAULT False,
   "IsBlinkersOff" BOOLEAN DEFAULT False,
   "TurfIndicator" VARCHAR(2),
   "DebutIndicator" VARCHAR(2),
   "RouteIndicator" VARCHAR(2),
   "MudIndicator" VARCHAR(2),
   "IsScratched" BOOLEAN DEFAULT False,
   "Age" SMALLINT DEFAULT 0,
   "Sex" VARCHAR(3),
   "Color" VARCHAR(10),
   "Weight" VARCHAR(10),
   "IsSuperTrainer" BOOLEAN DEFAULT False,
   "Trainer" VARCHAR(30),
   "TrnWinsRank" SMALLINT DEFAULT 0,
   "TrnEarningsRank" SMALLINT DEFAULT 0,
   "TrnTrackRank" SMALLINT DEFAULT 0,
   "IsSuperJockey" BOOLEAN DEFAULT False,
   "Jockey" VARCHAR(25),
   "JkyWinsRank" SMALLINT DEFAULT 0,
   "JkyEarningsRank" SMALLINT DEFAULT 0,
   "JkyTrackRank" SMALLINT DEFAULT 0,
   "IsSuperOwner" BOOLEAN DEFAULT False,
   "Owner" VARCHAR(45),
   "OwnWinsRank" SMALLINT DEFAULT 0,
   "OwnEarningsRank" SMALLINT DEFAULT 0,
   "Breeder" VARCHAR(67),
   "TotalTrnStarts" SMALLINT DEFAULT 0,
   "TotalTrnWins" SMALLINT DEFAULT 0,
   "TotalTrnWinPct" FLOAT DEFAULT 0,
   "TotalTrnWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnJkyStarts" SMALLINT DEFAULT 0,
   "TotalTrnJkyWins" SMALLINT DEFAULT 0,
   "TotalTrnJkyWinPct" FLOAT DEFAULT 0,
   "TotalTrnJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnOwnStarts" SMALLINT DEFAULT 0,
   "TotalTrnOwnWins" SMALLINT DEFAULT 0,
   "TotalTrnOwnWinPct" FLOAT DEFAULT 0,
   "TotalTrnOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn1To45Starts" SMALLINT DEFAULT 0,
   "TotalTrn1To45Wins" SMALLINT DEFAULT 0,
   "TotalTrn1To45WinPct" FLOAT DEFAULT 0,
   "TotalTrnWork1To45Starts" SMALLINT DEFAULT 0,
   "TotalTrnWork1To45Wins" SMALLINT DEFAULT 0,
   "TotalTrnWork1To45WinPct" FLOAT DEFAULT 0,
   "TotalTrn46To120Starts" SMALLINT DEFAULT 0,
   "TotalTrn46To120Wins" SMALLINT DEFAULT 0,
   "TotalTrn46To120WinPct" FLOAT DEFAULT 0,
   "TotalTrnWork46To120Starts" SMALLINT DEFAULT 0,
   "TotalTrnWork46To120Wins" SMALLINT DEFAULT 0,
   "TotalTrnWork46To120WinPct" FLOAT DEFAULT 0,
   "TotalTrn120PlusStarts" SMALLINT DEFAULT 0,
   "TotalTrn120PlusWins" SMALLINT DEFAULT 0,
   "TotalTrn120PlusWinPct" FLOAT DEFAULT 0,
   "TotalTrnWork120PlusStarts" SMALLINT DEFAULT 0,
   "TotalTrnWork120PlusWins" SMALLINT DEFAULT 0,
   "TotalTrnWork120PlusWinPct" FLOAT DEFAULT 0,
   "TotalTrnDebutStarts" SMALLINT DEFAULT 0,
   "TotalTrnDebutWins" SMALLINT DEFAULT 0,
   "TotalTrnDebutWinPct" FLOAT DEFAULT 0,
   "TotalTrnDebutTwoStarts" SMALLINT DEFAULT 0,
   "TotalTrnDebutTwoWins" SMALLINT DEFAULT 0,
   "TotalTrnDebutTwoWinPct" FLOAT DEFAULT 0,
   "TotalTrnFirstJuiceStarts" SMALLINT DEFAULT 0,
   "TotalTrnFirstJuiceWins" SMALLINT DEFAULT 0,
   "TotalTrnFirstJuiceWinPct" FLOAT DEFAULT 0,
   "TotalTrnBlinkersOnStarts" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOnWins" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOnWinPct" FLOAT DEFAULT 0,
   "TotalTrnBlinkersOffStarts" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOffWins" SMALLINT DEFAULT 0,
   "TotalTrnBlinkersOffWinPct" FLOAT DEFAULT 0,
   "TotalTrnTurfStarts" SMALLINT DEFAULT 0,
   "TotalTrnTurfWins" SMALLINT DEFAULT 0,
   "TotalTrnTurfWinPct" FLOAT DEFAULT 0,
   "TotalTrnTurfWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn30Starts" SMALLINT DEFAULT 0,
   "TotalTrn30Wins" SMALLINT DEFAULT 0,
   "TotalTrn30WinPct" FLOAT DEFAULT 0,
   "TotalTrn30WinPctRank" SMALLINT DEFAULT 0,
   "TotalTrnAftClmStarts" SMALLINT DEFAULT 0,
   "TotalTrnAftClmWins" SMALLINT DEFAULT 0,
   "TotalTrnAftClmWinPct" FLOAT DEFAULT 0,
   "TotalTrnOddsStarts" SMALLINT DEFAULT 0,
   "TotalTrnOddsWins" SMALLINT DEFAULT 0,
   "TotalTrnOddsWinPct" FLOAT DEFAULT 0,
   "TotalTrnOddsWinPctRank" SMALLINT DEFAULT 0,
   "TotalTrn1stStarts" SMALLINT DEFAULT 0,
   "TotalTrn1stWins" SMALLINT DEFAULT 0,
   "TotalTrn1stWinPct" FLOAT DEFAULT 0,
   "TotalTrn2yoStarts" SMALLINT DEFAULT 0,
   "TotalTrn2yoWins" SMALLINT DEFAULT 0,
   "TotalTrn2yoWinPct" FLOAT DEFAULT 0,
   "TotalTrn2oWinPctRank" SMALLINT DEFAULT 0,
   "TrnTodayStarts" SMALLINT DEFAULT 0,
   "TrnTodayWins" SMALLINT DEFAULT 0,
   "TrnTodayWinPct" FLOAT DEFAULT 0,
   "TrnTodayWinPctRank" SMALLINT DEFAULT 0,
   "TrnDirtToTurfStarts" SMALLINT DEFAULT 0,
   "TrnDirtToTurfWinPct" SMALLINT DEFAULT 0,
   "TrnTurfToDirtStarts" SMALLINT DEFAULT 0,
   "TrnTurfToDirtWinPct" SMALLINT DEFAULT 0,
   "TrnRteToSprStarts" SMALLINT DEFAULT 0,
   "TrnRteToSprWinPct" SMALLINT DEFAULT 0,
   "TrnSprToRteStarts" SMALLINT DEFAULT 0,
   "TrnSprToRteWinPct" SMALLINT DEFAULT 0,
   "TrnStkWinPct" SMALLINT DEFAULT 0,
   "TrnClmWinPct" SMALLINT DEFAULT 0,
   "TrnMdnWinPct" SMALLINT DEFAULT 0,
   "TrnAlwWinPct" SMALLINT DEFAULT 0,
   "TotalJkyStarts" SMALLINT DEFAULT 0,
   "TotalJkyWins" SMALLINT DEFAULT 0,
   "TotalJkyWinPct" FLOAT DEFAULT 0,
   "TotalJkyWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyDaysStarts" SMALLINT DEFAULT 0,
   "TotalJkyDaysWins" SMALLINT DEFAULT 0,
   "TotalJkyDaysWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyDaysWinPct" FLOAT DEFAULT 0,
   "TotalJkyOddsStarts" SMALLINT DEFAULT 0,
   "TotalJkyOddsWins" SMALLINT DEFAULT 0,
   "TotalJkyOddsWinPct" FLOAT DEFAULT 0,
   "TotalJkyOddsWinPctRank" SMALLINT DEFAULT 0,
   "TotalJkyTurfStarts" SMALLINT DEFAULT 0,
   "TotalJkyTurfWins" SMALLINT DEFAULT 0,
   "TotalJkyTurfWinPct" FLOAT DEFAULT 0,
   "TotalJky10Starts" SMALLINT DEFAULT 0,
   "TotalJky10Wins" SMALLINT DEFAULT 0,
   "TotalJky10WinPct" FLOAT DEFAULT 0,
   "TotalJky10WinPctRank" SMALLINT DEFAULT 0,
   "TotalJky30Starts" SMALLINT DEFAULT 0,
   "TotalJky30Wins" SMALLINT DEFAULT 0,
   "TotalJky30WinPct" FLOAT DEFAULT 0,
   "TotalJky30WinPctRank" SMALLINT DEFAULT 0,
   "TotalJky2yoStarts" SMALLINT DEFAULT 0,
   "TotalJky2yoWins" SMALLINT DEFAULT 0,
   "TotalJky2yoWinPct" FLOAT DEFAULT 0,
   "TotalOwnStarts" SMALLINT DEFAULT 0,
   "TotalOwnWins" SMALLINT DEFAULT 0,
   "TotalOwnWinPct" FLOAT DEFAULT 0,
   "TotalOwnWinPctRank" SMALLINT DEFAULT 0,
   "TotalOwnTop3WinPct" SMALLINT DEFAULT 0,
   "TotalBrdStarts" SMALLINT DEFAULT 0,
   "TotalBrdWins" SMALLINT DEFAULT 0,
   "TotalBrdWinPct" FLOAT DEFAULT 0,
   "TotalBrdWinPctRank" SMALLINT DEFAULT 0,
   "BredIn" VARCHAR(6),
   "Sire" VARCHAR(25),
   "SireTurfLastYearRank" SMALLINT DEFAULT 0,
   "SireTurfLastYearStarts" INTEGER DEFAULT 0,
   "SireTurfLastYearPctOfEarnings" SMALLINT DEFAULT 0,
   "SireGeneralLastYearRank" SMALLINT DEFAULT 0,
   "SireGeneralLastYearStudFee" FLOAT DEFAULT 0,
   "SireJuvenileLastYearRank" SMALLINT DEFAULT 0,
   "SireJuvenileThisYearRank" SMALLINT DEFAULT 0,
   "SireTurfThisYearRank" SMALLINT DEFAULT 0,
   "SireTurfThisYearStarts" INTEGER DEFAULT 0,
   "SireTurfThisYearPctOfEarnings" SMALLINT DEFAULT 0,
   "SireGeneralThisYearRank" SMALLINT DEFAULT 0,
   "SireGeneralThisYearStudFee" FLOAT DEFAULT 0,
   "SireAEI" FLOAT DEFAULT 0,
   "SireAWThisYearRank" SMALLINT DEFAULT 0,
   "SireAWLastYearRank" SMALLINT DEFAULT 0,
   "Dam" VARCHAR(25),
   "DamSire" VARCHAR(25),
   "DamSireTurfLastYearRank" SMALLINT DEFAULT 0,
   "DamSireTurfLastYearStarts" INTEGER DEFAULT 0,
   "DamSireTurfLastYearPctOfEarnings" SMALLINT DEFAULT 0,
   "DamSireGeneralLastYearRank" SMALLINT DEFAULT 0,
   "DamSireGeneralLastYearStudFee" FLOAT DEFAULT 0,
   "DamSireJuvenileLastYearRank" SMALLINT DEFAULT 0,
   "DamSireJuvenileThisYearRank" SMALLINT DEFAULT 0,
   "DamSireTurfThisYearRank" SMALLINT DEFAULT 0,
   "DamSireTurfThisYearStarts" INTEGER DEFAULT 0,
   "DamSireTurfThisYearPctOfEarnings" SMALLINT DEFAULT 0,
   "DamSireGeneralThisYearRank" SMALLINT DEFAULT 0,
   "DamSireGeneralThisYearStudFee" FLOAT DEFAULT 0,
   "DamSireAEI" FLOAT,
   "DamSireAWThisYearRank" SMALLINT,
   "DamSireAWLastYearRank" SMALLINT,
   "DaysLast" SMALLINT DEFAULT 0,
   "DaysLastWork" SMALLINT DEFAULT 0,
   "LastTrkCode" VARCHAR(3),
   "LastRaceNbr" INTEGER DEFAULT 0,
   "LastRaceDate" DATE,
   "LastPostPos" SMALLINT DEFAULT 0,
   "LastRaceType" VARCHAR(6),
   "LastSurf" VARCHAR(1),
   "LastRaceConditions" VARCHAR(20),
   "LastDistanceDesc" VARCHAR(16),
   "LastDistance" FLOAT DEFAULT 0,
   "LastOdds" FLOAT DEFAULT 0,
   "LastFavoriteIndicator" VARCHAR(1),
   "LastDQIndicator" VARCHAR(2),
   "LastJockey" VARCHAR(15),
   "LastComment" VARCHAR(100),
   "LastComment2" VARCHAR(200),
   "LastTrkCond" VARCHAR(3),
   "LastClmPrice" FLOAT DEFAULT 0,
   "LastClaimed" VARCHAR(1),
   "LastPurse" FLOAT DEFAULT 0,
   "LastDay" VARCHAR(2),
   "LastMonthDesc" VARCHAR(3),
   "LastYear" VARCHAR(4),
   "LastGateBreak" VARCHAR(2),
   "LastLen1Back" VARCHAR(7),
   "LastLen2Back" VARCHAR(7),
   "LastStLenBack" VARCHAR(7),
   "LastFinishBeaten" VARCHAR(7),
   "LastEquip" VARCHAR(7),
   "LastWeight" INTEGER,
   "LastHorseTime" FLOAT,
   "LastRaceDesc" VARCHAR(150),
   "MorningLineTo1" FLOAT,
   "MorningLineTo1Rank" SMALLINT,
   "IsDirtToTurf" BOOLEAN DEFAULT False,
   "IsTurfToDirt" BOOLEAN DEFAULT False,
   "IsSprToRte" BOOLEAN DEFAULT False,
   "IsRteToSpr" BOOLEAN DEFAULT False,
   "LastSpeed" SMALLINT DEFAULT 0,
   "LastSpeedRank" SMALLINT DEFAULT 0,
   "Power" FLOAT DEFAULT 0,
   "PowerRank" SMALLINT DEFAULT 0,
   "BackSpeed" SMALLINT DEFAULT 0,
   "BackSpeedRank" SMALLINT DEFAULT 0,
   "AvgClass" FLOAT DEFAULT 0,
   "AvgClassRank" SMALLINT DEFAULT 0,
   "AvgSpeed" SMALLINT DEFAULT 0,
   "AvgSpeedRank" SMALLINT DEFAULT 0,
   "AvgClassRating" FLOAT DEFAULT 0,
   "AvgClassRatingRank" SMALLINT DEFAULT 0,
   "BackClass" FLOAT DEFAULT 0,
   "BackClassRank" SMALLINT DEFAULT 0,
   "CurrClass" FLOAT,
   "CurrClassRank" SMALLINT DEFAULT 0,
   "EarlyPace" FLOAT DEFAULT 0,
   "EarlyPaceRank" SMALLINT DEFAULT 0,
   "EarlyPacePos" FLOAT DEFAULT 9999,
   "EarlyPacePosRank" SMALLINT DEFAULT 0,
   "MiddlePace" FLOAT DEFAULT 0,
   "MiddlePaceRank" SMALLINT DEFAULT 0,
   "MiddlePacePos" FLOAT DEFAULT 9999,
   "MiddlePacePosRank" SMALLINT DEFAULT 0,
   "LatePace" FLOAT DEFAULT 0,
   "LatePaceRank" SMALLINT DEFAULT 0,
   "LatePacePos" FLOAT DEFAULT 9999,
   "LatePacePosRank" SMALLINT DEFAULT 0,
   "FinishPacePos" FLOAT DEFAULT 0,
   "FinishPacePosRank" SMALLINT DEFAULT 0,
   "EarlyPaceAdvantage" FLOAT DEFAULT 0,
   "MiddlePaceAdvantage" FLOAT DEFAULT 0,
   "LatePaceAdvantage" FLOAT DEFAULT 0,
   "IsClaimed1Back" BOOLEAN DEFAULT False,
   "IsClaimed2Back" BOOLEAN DEFAULT False,
   "IsLayoffAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndUp" BOOLEAN DEFAULT False,
   "IsClaimedAndDown" BOOLEAN DEFAULT False,
   "IsFirstTimeClaiming" BOOLEAN DEFAULT False,
   "IsBelowClaimedPrice" BOOLEAN DEFAULT False,
   "LifeStarts" SMALLINT DEFAULT 0,
   "LifeWins" SMALLINT DEFAULT 0,
   "LifePlcs" SMALLINT DEFAULT 0,
   "LifeShos" SMALLINT DEFAULT 0,
   "LifeEarnings" INTEGER DEFAULT 0,
   "LifeEPS" INTEGER DEFAULT 0,
   "TurfStarts" SMALLINT DEFAULT 0,
   "TurfWins" SMALLINT DEFAULT 0,
   "TurfPlcs" SMALLINT DEFAULT 0,
   "TurfShos" SMALLINT DEFAULT 0,
   "TurfEarnings" INTEGER DEFAULT 0,
   "TurfEPS" INTEGER DEFAULT 0,
   "MudStarts" SMALLINT DEFAULT 0,
   "MudWins" SMALLINT DEFAULT 0,
   "MudPlcs" SMALLINT DEFAULT 0,
   "MudShos" SMALLINT DEFAULT 0,
   "MudEarnings" INTEGER DEFAULT 0,
   "MudEPS" INTEGER DEFAULT 0,
   "TrkStarts" SMALLINT DEFAULT 0,
   "TrkWins" SMALLINT DEFAULT 0,
   "TrkPlcs" SMALLINT DEFAULT 0,
   "TrkShos" SMALLINT DEFAULT 0,
   "TrkEarnings" INTEGER DEFAULT 0,
   "TrkEPS" INTEGER DEFAULT 0,
   "RouteStarts" SMALLINT DEFAULT 0,
   "RouteWins" SMALLINT DEFAULT 0,
   "RoutePlcs" SMALLINT DEFAULT 0,
   "RouteShos" SMALLINT DEFAULT 0,
   "SprintStarts" SMALLINT DEFAULT 0,
   "SprintWins" SMALLINT DEFAULT 0,
   "SprintPlcs" SMALLINT DEFAULT 0,
   "SprintShos" SMALLINT DEFAULT 0,
   "AngleDesc" VARCHAR(200),
   "IsWagerSheetSelected" BOOLEAN DEFAULT False,
   "IsYouBetTrack" BOOLEAN DEFAULT False,
   "IsPrintedOnValueSheet" BOOLEAN DEFAULT False,
   "HorseNbr" SMALLINT DEFAULT 0,
   "WorkLine1" VARCHAR(250),
   "WorkLine2" VARCHAR(250),
   "IsFrontDoubleLiner" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner" BOOLEAN DEFAULT False,
   "IsTripleLiner" BOOLEAN DEFAULT False,
   "IsFrontDoubleDot" BOOLEAN DEFAULT False,
   "IsBackDoubleDot" BOOLEAN DEFAULT False,
   "IsTripleDot" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner0" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner0" BOOLEAN DEFAULT False,
   "IsTripleLiner0" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner1" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner1" BOOLEAN DEFAULT False,
   "IsTripleLiner1" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner2" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner2" BOOLEAN DEFAULT False,
   "IsTripleLiner2" BOOLEAN DEFAULT False,
   "IsFrontDoubleLiner3" BOOLEAN DEFAULT False,
   "IsBackDoubleLiner3" BOOLEAN DEFAULT False,
   "IsTripleLiner3" BOOLEAN DEFAULT False,
   "TodaysWagerOrderKey" VARCHAR(50),
   "TodaysWagerStarts" INTEGER DEFAULT 0,
   "TodaysWagerWins" INTEGER DEFAULT 0,
   "TodaysWagerWinPct" FLOAT DEFAULT 0,
   "TodaysWagerWinPctRank" SMALLINT DEFAULT 0,
   "TodaysWagerAvgOdds" FLOAT DEFAULT 0,
   "TodaysWagerMinOdds" FLOAT DEFAULT 0,
   "TodaysWagerMaxOdds" FLOAT DEFAULT 0,
   "TodaysWagerAvgWinOdds" FLOAT DEFAULT 0,
   "TodaysWagerMinWinOdds" FLOAT DEFAULT 0,
   "TodaysWagerMaxWinOdds" FLOAT DEFAULT 0,
   "TodaysWagerValueBet" FLOAT DEFAULT 0,
   "Last2TrkCode" VARCHAR(3),
   "Last2RaceNbr" INTEGER DEFAULT 0,
   "Last2RaceDate" DATE,
   "Last2PostPos" SMALLINT DEFAULT 0,
   "Last2RaceType" VARCHAR(6),
   "Last2Surf" VARCHAR(1),
   "Last2RaceConditions" VARCHAR(3),
   "Last2DistanceDesc" VARCHAR(16),
   "Last2Distance" FLOAT DEFAULT 0,
   "Last2Odds" FLOAT DEFAULT 0,
   "Last2FavoriteIndicator" VARCHAR(1),
   "Last2DQIndicator" VARCHAR(2),
   "Last2Jockey" VARCHAR(15),
   "Last2Comment" VARCHAR(100),
   "Last2Comment2" VARCHAR(200),
   "Last2TrkCond" VARCHAR(2),
   "Last2ClmPrice" FLOAT DEFAULT 0,
   "Last2Claimed" VARCHAR(1),
   "Last2Purse" FLOAT DEFAULT 0,
   "Last2Day" VARCHAR(2),
   "Last2MonthDesc" VARCHAR(3),
   "Last2Year" VARCHAR(4),
   "Last2GateBreak" VARCHAR(2),
   "Last2Len1Back" VARCHAR(7),
   "Last2Len2Back" VARCHAR(7),
   "Last2StLenBack" VARCHAR(7),
   "Last2FinishBeaten" VARCHAR(7),
   "Last2Equip" VARCHAR(2),
   "Last2Weight" INTEGER,
   "Last2Speed" INTEGER,
   "Last2HorseTime" FLOAT,
   "Last2RaceDesc" VARCHAR(150),
   "Last3TrkCode" VARCHAR(3),
   "Last3RaceNbr" INTEGER DEFAULT 0,
   "Last3RaceDate" DATE,
   "Last3PostPos" SMALLINT DEFAULT 0,
   "Last3RaceType" VARCHAR(6),
   "Last3Surf" VARCHAR(1),
   "Last3RaceConditions" VARCHAR(20),
   "Last3DistanceDesc" VARCHAR(16),
   "Last3Distance" FLOAT DEFAULT 0,
   "Last3Odds" FLOAT DEFAULT 0,
   "Last3FavoriteIndicator" VARCHAR(1),
   "Last3DQIndicator" VARCHAR(2),
   "Last3Jockey" VARCHAR(15),
   "Last3Comment" VARCHAR(100),
   "Last3Comment2" VARCHAR(200),
   "Last3TrkCond" VARCHAR(2),
   "Last3ClmPrice" FLOAT DEFAULT 0,
   "Last3Claimed" VARCHAR(1),
   "Last3Purse" FLOAT DEFAULT 0,
   "Last3Day" VARCHAR(2),
   "Last3MonthDesc" VARCHAR(3),
   "Last3Year" VARCHAR(4),
   "Last3GateBreak" VARCHAR(2),
   "Last3Len1Back" VARCHAR(7),
   "Last3Len2Back" VARCHAR(7),
   "Last3StLenBack" VARCHAR(7),
   "Last3FinishBeaten" VARCHAR(7),
   "Last3Equip" VARCHAR(7),
   "Last3Weight" INTEGER,
   "Last3Speed" INTEGER,
   "Last3HorseTime" FLOAT,
   "Last3RaceDesc" VARCHAR(150),
   "Odds" FLOAT DEFAULT 0,
   "FinishPos" FLOAT DEFAULT 0,
   "QSP1stCall" SMALLINT,
   "QSP1stCallRank" SMALLINT,
   "QSP1stCallRunStyle" VARCHAR(2),
   "QSP2ndCall" SMALLINT,
   "QSP2ndCallRank" SMALLINT,
   "QSP2ndCallRunStyle" VARCHAR(2),
   "KSP1stCall" SMALLINT,
   "KSP1stCallRank" SMALLINT,
   "KSP2ndCall" SMALLINT,
   "KSP2ndCallRank" SMALLINT,
   "LastPos1stCall" FLOAT DEFAULT 0,
   "LastPos2ndCall" FLOAT DEFAULT 0,
   "LastPosStrCall" FLOAT DEFAULT 0,
   "Last2Pos1stCall" FLOAT DEFAULT 0,
   "Last2Pos2ndCall" FLOAT DEFAULT 0,
   "Last2PosStrCall" FLOAT DEFAULT 0,
   "Last3Pos1stCall" FLOAT DEFAULT 0,
   "Last3Pos2ndCall" FLOAT DEFAULT 0,
   "Last3PosStrCall" FLOAT DEFAULT 0,
   "LastTime1stCall" FLOAT DEFAULT 0,
   "LastTime2ndCall" FLOAT DEFAULT 0,
   "LastTimeStrCall" FLOAT DEFAULT 0,
   "LastTimeFinCall" FLOAT DEFAULT 0,
   "Last2Time1stCall" FLOAT DEFAULT 0,
   "Last2Time2ndCall" FLOAT DEFAULT 0,
   "Last2TimeStrCall" FLOAT DEFAULT 0,
   "Last2TimeFinCall" FLOAT DEFAULT 0,
   "Last3Time1stCall" FLOAT DEFAULT 0,
   "Last3Time2ndCall" FLOAT DEFAULT 0,
   "Last3TimeStrCall" FLOAT DEFAULT 0,
   "Last3TimeFinCall" FLOAT DEFAULT 0,
   "LastBL1stCall" FLOAT DEFAULT 0,
   "LastBL2ndCall" FLOAT DEFAULT 0,
   "LastBLStrCall" FLOAT DEFAULT 0,
   "LastBLFinCall" FLOAT DEFAULT 0,
   "Last2BL1stCall" FLOAT DEFAULT 0,
   "Last2BL2ndCall" FLOAT DEFAULT 0,
   "Last2BLStrCall" FLOAT DEFAULT 0,
   "Last2BLFinCall" FLOAT DEFAULT 0,
   "Last3BL1stCall" FLOAT DEFAULT 0,
   "Last3BL2ndCall" FLOAT DEFAULT 0,
   "Last3BLStrCall" FLOAT DEFAULT 0,
   "Last3BLFinCall" FLOAT DEFAULT 0,
   "LastPosFinCall" FLOAT DEFAULT 0,
   "Last2PosFinCall" FLOAT DEFAULT 0,
   "Last3PosFinCall" FLOAT DEFAULT 0,
   "Is1stClaiming" BOOLEAN DEFAULT False,
   "Is1stMCL" BOOLEAN DEFAULT False,
   "Is1stAfterLayoff" BOOLEAN DEFAULT False,
   "Is2ndAfterLayoff" BOOLEAN DEFAULT False,
   "Is3rdAfterLayoff" BOOLEAN DEFAULT False,
   "IsDirtToTurfToDirtAfterLayoff" BOOLEAN DEFAULT False,
   "IsTurfToDirtToTurfAfterLayoff" BOOLEAN DEFAULT False,
   "IsRouteToSprintToRouteAfterLayoff" BOOLEAN DEFAULT False,
   "IsSprintToRouteToSprintAfterLayoff" BOOLEAN DEFAULT False,
   "Is2yoBred" BOOLEAN DEFAULT False,
   "Is1stBred" BOOLEAN DEFAULT False,
   "IsTurfBred" BOOLEAN DEFAULT False,
   "Is1stOffLayoff" BOOLEAN DEFAULT False,
   "Is2ndOffLayoff" BOOLEAN DEFAULT False,
   "Is3rdOffLayoff" BOOLEAN DEFAULT False,
   "StandingIn" VARCHAR(5),
   "StandingInRank" SMALLINT DEFAULT 9999,
   "IsOnStandingInList" BOOLEAN DEFAULT False,
   "ValueROI" FLOAT DEFAULT 0,
   "ValueROICnt" SMALLINT DEFAULT 0,
   "ValueDesc" VARCHAR(255),
   "DollarCnt" SMALLINT DEFAULT 0,
   "ListType" VARCHAR(1) DEFAULT 'R',
   "PowerAdvantage" FLOAT DEFAULT 0,
   "PowerAdvantageKey" INTEGER DEFAULT 0,
   "PostPosWinPct" SMALLINT DEFAULT 0,
   "PostPosStarts" INTEGER DEFAULT 0,
   "PostPosWinPctRank" FLOAT DEFAULT 0,
   "PaceIndicatorWinPct" FLOAT DEFAULT 0,
   "PaceIndicatorWinPctRank" SMALLINT DEFAULT 0,
   "ElimWinPct" FLOAT DEFAULT 0,
   "Elim2WinPct" FLOAT DEFAULT 0,
   "TodaysWagerOddsDesc" VARCHAR(10) DEFAULT '99/1',
   "PowerAdvantageWinPct" FLOAT DEFAULT 0,
   "EarlyPaceAdvantageWinPct" FLOAT DEFAULT 0,
   "EarlyPaceAdvantageWinPctRank" SMALLINT,
   "EarlyPaceAdvantageValueBet" FLOAT DEFAULT 0,
   "MiddlePaceAdvantageWinPct" FLOAT DEFAULT 0,
   "MiddlePaceAdvantageWinPctRank" SMALLINT,
   "MiddlePaceAdvantageValueBet" FLOAT DEFAULT 0,
   "LatePaceAdvantageWinPct" FLOAT DEFAULT 0,
   "LatePaceAdvantageWinPctRank" SMALLINT,
   "IsHeavyChalk" BOOLEAN DEFAULT False,
   "MorningLineWinPct" FLOAT DEFAULT 0,
   "IsEliminated" BOOLEAN DEFAULT False,
   "IsValueDebutSelected" BOOLEAN DEFAULT False,
   "IsValueDebutTwoSelected" BOOLEAN DEFAULT False,
   "IsValueWagerSelected" BOOLEAN DEFAULT False,
   "IsPTCTrack" BOOLEAN DEFAULT False,
   "IsTwinSpiresTrack" BOOLEAN DEFAULT False,
   "TodaysAltWagerWinPct" FLOAT,
   "TodaysAltWagerWinPctRank" SMALLINT,
   "SelectorChoice" SMALLINT DEFAULT 0,
   "IsSpeedSheetSelected" BOOLEAN DEFAULT False,
   "ClassRating" FLOAT DEFAULT 0,
   "ClassRatingRank" SMALLINT DEFAULT 0,
   "TurfRating" FLOAT DEFAULT 0,
   "TurfRatingRank" SMALLINT DEFAULT 0,
   "MudRating" FLOAT DEFAULT 0,
   "MudRatingRank" SMALLINT DEFAULT 0,
   "DistanceRating" FLOAT DEFAULT 0,
   "DistanceRatingRank" SMALLINT DEFAULT 0,
   "AWRating" FLOAT DEFAULT 0,
   "AWRatingRank" SMALLINT DEFAULT 0,
   "SireClassRating" FLOAT DEFAULT 0,
   "SireClassRatingRank" SMALLINT DEFAULT 0,
   "DamSireClassRating" FLOAT DEFAULT 0,
   "DamSireClassRatingRank" SMALLINT DEFAULT 0,
   "SireTurfRating" FLOAT DEFAULT 0,
   "SireTurfRatingRank" SMALLINT DEFAULT 0,
   "DamSireTurfRating" FLOAT DEFAULT 0,
   "DamSireTurfRatingRank" SMALLINT DEFAULT 0,
   "SireMudRatingRank" SMALLINT DEFAULT 0,
   "SireMudRating" FLOAT DEFAULT 0,
   "DamSireMudRating" FLOAT DEFAULT 0,
   "DamSireMudRatingRank" SMALLINT DEFAULT 0,
   "SireSprintRating" FLOAT DEFAULT 0,
   "SireSprintRatingRank" SMALLINT DEFAULT 0,
   "DamSireSprintRating" FLOAT DEFAULT 0,
   "DamSireSprintRatingRank" SMALLINT DEFAULT 0,
   "SireRouteRating" FLOAT DEFAULT 0,
   "SireRouteRatingRank" SMALLINT DEFAULT 0,
   "DamSireRouteRating" FLOAT DEFAULT 0,
   "DamSireRouteRatingRank" SMALLINT DEFAULT 0,
   "SireAWRating" FLOAT DEFAULT 0,
   "SireAWRatingRank" SMALLINT DEFAULT 0,
   "DamSireAWRating" FLOAT DEFAULT 0,
   "DamSireAWRatingRank" SMALLINT DEFAULT 0,
   "TrainerRating" FLOAT DEFAULT 0,
   "TrainerRatingRank" SMALLINT DEFAULT 0,
   "TrainerOwnerRating" FLOAT DEFAULT 0,
   "TrainerOwnerRatingRank" SMALLINT DEFAULT 0,
   "TrainerJockeyRating" FLOAT DEFAULT 0,
   "TrainerJockeyRatingRank" SMALLINT DEFAULT 0,
   "TrainerTrackRating" FLOAT DEFAULT 0,
   "TrainerTrackRatingRank" SMALLINT DEFAULT 0,
   "JockeyRating" FLOAT DEFAULT 0,
   "JockeyRatingRank" SMALLINT DEFAULT 0,
   "JockeyOwnerRating" FLOAT DEFAULT 0,
   "JockeyOwnerRatingRank" SMALLINT DEFAULT 0,
   "JockeyTrackRating" FLOAT DEFAULT 0,
   "JockeyTrackRatingRank" SMALLINT DEFAULT 0,
   "OwnerRating" FLOAT DEFAULT 0,
   "OwnerRatingRank" SMALLINT DEFAULT 0,
   "TurfOrder" VARCHAR(25),
   "MaidenOrder" VARCHAR(25),
   "MudOrder" VARCHAR(25),
   "AWOrder" VARCHAR(25),
   "DistanceOrder" VARCHAR(25),
   "FinalOrderWinPct" FLOAT DEFAULT 0,
   "FinalOrderWinPctRank" SMALLINT DEFAULT 0,
   "FinalOrderKey" VARCHAR(25),
   "IsTrainerSheetSelected" BOOLEAN DEFAULT False,
   "TCPlusMinus" INTEGER DEFAULT 0,
   "TJMeetWinPct" INTEGER,
   "TJ365WinPct" INTEGER,
   "PacificTime" VARCHAR(20),
   "FinalWinPct" FLOAT,
PRIMARY KEY ("TrkCode","RaceDate","RaceNbr","PostPos") COMPRESS NONE
INDEX PAGE SIZE 16384
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE NOCASE INDEX IF NOT EXISTS "ByHorseName" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","HorseName");
CREATE INDEX IF NOT EXISTS "ByRangeRaceDate" ON "Entry" ("RangeRaceDate","RaceDate","TrkCode","RaceDate","RaceNbr","PostPos");
CREATE INDEX IF NOT EXISTS "ByHorseNbr" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","HorseNbr");
CREATE INDEX IF NOT EXISTS "ByEstTimeOfRace" ON "Entry" ("RangeRaceDate","EstTimeOfRace");
CREATE INDEX IF NOT EXISTS "ByProgSortOrder" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","ProgramNbrSort");
CREATE INDEX IF NOT EXISTS "ByTodaysWagerWinPctRank" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","TodaysWagerWinPct" DESC,"TotalTrnDebutWinPct" DESC,"TotalTrnDebutTwoWinPct" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByLastSpeedRank" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","LastSpeed" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByBackSpeedRank" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","BackSpeed" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByPowerRank" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","Power" DESC,"TrnTrackRank","JkyTrackRank","TrnWinsRank","JkyWinsRank","OwnWinsRank");
CREATE INDEX IF NOT EXISTS "ByTotalTrnOddsWinPctRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","TotalTrnOddsWinPct" DESC);
CREATE INDEX IF NOT EXISTS "ByTotalJkyOddsWinPctRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","TotalJkyOddsWinPct" DESC);
CREATE INDEX IF NOT EXISTS "ByMorningLineTo1Rank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","MorningLineTo1","Power");
CREATE INDEX IF NOT EXISTS "ByTrnTodayWinPctRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","TrnTodayWinPct" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByQSP1stCallRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","QSP1stCall" DESC,"KSP1stCall","Power" DESC);
CREATE INDEX IF NOT EXISTS "ByQSP2ndCallRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","QSP2ndCall" DESC,"KSP2ndCall","Power" DESC);
CREATE INDEX IF NOT EXISTS "ByKSP1stCallRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","KSP1stCall","QSP1stCall" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByKSP2ndCallRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","KSP2ndCall","QSP2ndCall" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByEarlyPaceRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","EarlyPace" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByMiddlePaceRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","MiddlePace" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByLatePaceRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","LatePace" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByEarlyPacePosRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","EarlyPacePos","Power" DESC);
CREATE INDEX IF NOT EXISTS "ByMiddlePacePosRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","MiddlePacePos","Power" DESC);
CREATE INDEX IF NOT EXISTS "ByLatePacePosRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","LatePacePos","Power" DESC);
CREATE INDEX IF NOT EXISTS "ByTotalTrnJkyWinPctRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","TotalTrnJkyWinPct" DESC,"TotalTrnJkyWinPct" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByTotalTrn30WinPctRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","TotalTrn30WinPct" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByTotalJky30WinPctRank" ON "Entry" ("TrkCode","RaceDate","RaceNbr","TotalJky30WinPct" DESC,"Power" DESC);
CREATE INDEX IF NOT EXISTS "ByHorseNameRaceNbr" ON "Entry" ("HorseName","RaceNbr");
CREATE INDEX IF NOT EXISTS "ByFinalOrderWinPctRank" ON "Entry" ("RangeRaceDate","TrkCode","RaceDate","RaceNbr","FinalOrderWinPct" DESC,"Power" DESC);
