/* SQL-92 Table Creation Script with DBISAM Extensions */

CREATE TABLE IF NOT EXISTS "C:\RatingsData31\RankingStatsByTrk"
(
   "TrkCode" VARCHAR(3),
   "Name" VARCHAR(50),
   "Rank" INTEGER,
   "Starts" INTEGER,
   "WinPct" FLOAT,
   "PlcPct" FLOAT,
   "ShoPct" FLOAT,
   "AvgOdds" FLOAT,
   "AvgWinOdds" FLOAT,
   "ValueBet" FLOAT,
   "BEWinPct" FLOAT,
   "FP1" INTEGER,
   "FP2" INTEGER,
   "FP3" INTEGER,
   "FP4" INTEGER,
   "FP5" INTEGER,
   "FP6" INTEGER,
   "FP7" INTEGER,
   "FP8" INTEGER,
   "FP9" INTEGER,
   "FP10" INTEGER,
   "FP11" INTEGER,
   "FP12" INTEGER,
   "FP13" INTEGER,
   "FP14" INTEGER,
   "FP15" INTEGER,
   "FP16" INTEGER,
   "FP17" INTEGER,
   "FP18" INTEGER,
   "FP19" INTEGER,
   "FP20" INTEGER,
   "TO1" FLOAT,
   "TO2" FLOAT,
   "TO3" FLOAT,
   "TO4" FLOAT,
   "TO5" FLOAT,
   "TO6" FLOAT,
   "TO7" FLOAT,
   "TO8" FLOAT,
   "TO9" FLOAT,
   "TO10" FLOAT,
   "TO11" FLOAT,
   "TO12" FLOAT,
   "TO13" FLOAT,
   "TO14" FLOAT,
   "TO15" FLOAT,
   "TO16" FLOAT,
   "TO17" FLOAT,
   "TO18" FLOAT,
   "TO19" FLOAT,
   "TO20" FLOAT,
   "Type" VARCHAR(10),
   "IVWinners" FLOAT,
   "IVStarters" FLOAT,
   "IVTotalWinners" FLOAT,
   "IVTotalStarters" FLOAT,
   "IV" FLOAT,
   "TotalOdds" FLOAT,
   "TotalWinOdds" FLOAT,
PRIMARY KEY ("TrkCode","Name","Rank") COMPRESS FULL
LOCALE CODE 0
USER MAJOR VERSION 1
);

