SELECT 
  Entry.FinalAvgOdds,
  Entry.FinalME,
  Entry.FinalWinPct,
  Entry.FinalLineTo1,
  Entry.FinalStarts,
  Entry.FinalWins,
  Entry.MorningLineTo1,
  Entry.MorningLineTo1Probability,
  Entry.MorningLineTo1Fair,
  Entry.MorningLineTo1FairProbability,
  Entry.FinalKellyPct
FROM
  Entry
