SELECT
TrkCode as Track, 
RaceDate, 
RaceNbr, 
PostPos As Post,  
RaceType As Class, 
DebutIndicator,
TurfIndicator, 
Sex,
Age,
FinishPos,
MorningLineTo1 as ML, 
Odds, 
IF (MorningLineTo1Rank=1, 'Yes','No') AS IsMLFavorite,                                                     
IF (Surface = 'T', 'Turf', 'Dirt') AS Surface,
IF (FinishPos = 1, 'WON','LOST') AS Finish, 
IF (DistanceInFurlongs >= 8, 'Route', 'Sprint') AS Distance,
IF (TrnTrackRank > 0 and TrnTrackRank < 21 ,'Yes','No') AS IsTrnTop20Track,
IF (JkyTrackRank > 0 and TrnTrackRank < 21,'Yes','No') AS IsJkyTop20Track,
IF (NbrWorksLast > 0 or StartsWorks21 > 0,'Yes','No') AS IsActive,
IF (Is1stBred,'Yes','No') AS Is1stBred, 
IF (Is2YoBred,'Yes','No') AS Is2YoBred,
IF (IsTurfBred,'Yes','No') AS IsTurfBred,
IF (IsFirstTimeJuice,'Yes','No') AS IsFirstTimeJuice,
IF (IsSecondTimeJuice,'Yes','No') AS IsSecondTimeJuice,
IF (IsTrnTodayPlus,'Yes','No') AS IsTrnTodayPlus, 
IF (IsTrnTodayMinus,'Yes','No') AS IsTrnTodayMinus,
IF (FinishPos < 2, Odds,0)  As WinsOdds,
IF (BackSpeedRank                 = 1,'Yes','No') AS IsTopBackSpeedRank                    ,
IF (LastSpeedRank                 = 1,'Yes','No') AS IsTopLastSpeedRank                    ,
IF (BackClassRank                 = 1,'Yes','No') AS IsTopBackClassRank                    ,
IF (LastClassRank                 = 1,'Yes','No') AS IsTopLastClassRank                    ,
IF (FinalWinPctRank               = 1,'Yes','No') AS IsTopFinalWinPctRank                  ,
IF (PrimaryWinPctRank             = 1,'Yes','No') AS IsTopPrimaryWinPctRank                ,
IF (SecondaryWinPctRank           = 1,'Yes','No') AS IsTopSecondaryWinPctRank              ,
IF (DefaultWinPctRank             = 1,'Yes','No') AS IsTopDefaultWinPctRank                ,
IF (EstMorningLineWinPctRank      = 1,'Yes','No') AS IsTopEstMorningLineWinPctRank         ,
IF (TodaysWagerWinPctRank         = 1,'Yes','No') AS IsTopTodaysWagerWinPctRank            ,
IF (MorningLineTo1Rank            = 1,'Yes','No') AS IsTopMorningLineTo1Rank               ,
IF (PowerRank                     = 1,'Yes','No') AS IsTopPowerRank                        ,
IF (AvgClassRank                  = 1,'Yes','No') AS IsTopAvgClassRank                     ,
IF (AvgSpeedRank                  = 1,'Yes','No') AS IsTopAvgSpeedRank                     ,
IF (AvgClassRatingRank            = 1,'Yes','No') AS IsTopAvgClassRatingRank               ,
IF (EarlyPaceRank                 = 1,'Yes','No') AS IsTopEarlyPaceRank                    ,
IF (EarlyPacePosRank              = 1,'Yes','No') AS IsTopEarlyPacePosRank                 ,
IF (MiddlePaceRank                = 1,'Yes','No') AS IsTopMiddlePaceRank                   ,
IF (MiddlePacePosRank             = 1,'Yes','No') AS IsTopMiddlePacePosRank                ,
IF (LatePaceRank                  = 1,'Yes','No') AS IsTopLatePaceRank                     ,
IF (LatePacePosRank               = 1,'Yes','No') AS IsTopLatePacePosRank                  ,
IF (QSP1stCallRank                = 1,'Yes','No') AS IsTopQSP1stCallRank                   ,
IF (KSP1stCallRank                = 1,'Yes','No') AS IsTopKSP1stCallRank                   ,
IF (QSP2ndCallRank                = 1,'Yes','No') AS IsTopQSP2ndCallRank                   ,
IF (KSP2ndCallRank                = 1,'Yes','No') AS IsTopKSP2ndCallRank                   
INTO qryRanks
FROM  HorseHistory 
WHERE 
(RaceDate >= '2006-03-01') AND
(Odds > 0) AND
(FinishPos > 0) AND 
(IsYouBetTrack=True);
