SELECT
TrkCode as Track, 
RaceDate, 
RaceNbr, 
PostPos As Post,  
RaceType As Class, 
IF (Surface = 'T', 'Turf', 'Dirt') AS Surface,
MorningLineTo1 as ML, 
Odds, 
IF (MorningLineTo1Rank=1, 'Yes','No') AS IsMLFavorite,                                                     
IF (Odds < MorningLineTo1, 'Yes','No') AS IsOddsLessML,                                                     
IF (Odds > 0 and Odds <= 1, 'Yes','No') AS IsOddsGt0To1,
IF (Odds > 1 and Odds <= 2, 'Yes','No') AS IsOddsGt1To2,
IF (Odds > 2 and Odds <= 4, 'Yes','No') AS IsOddsGt2LessEq4,
IF (Odds > 4 and Odds <= 10, 'Yes','No') AS IsOddsGt4LessEq10,
IF (Odds > 10 and Odds <= 20, 'Yes','No') AS IsOddsGt10LessEq20,
IF (Odds > 20 and Odds <= 30, 'Yes','No') AS IsOddsGt20LessEq30,
IF (Odds > 30 and Odds <= 40, 'Yes','No') AS IsOddsGt30LessEq40,
IF (Odds > 40 and Odds <= 50, 'Yes','No') AS IsOddsGt40LessEq50,
IF (Odds > 50, 'Yes','No') AS IsOddsGt50,
IF (MorningLineTo1 > 0 and MorningLineTo1 <= 1, 'Yes','No') AS IsMLGt0To1,
IF (MorningLineTo1 > 1 and MorningLineTo1 <= 2, 'Yes','No') AS IsMLGt1To2,
IF (MorningLineTo1 > 2 and MorningLineTo1 <= 4, 'Yes','No') AS IsMLGt2LessEq4,
IF (MorningLineTo1 > 4 and MorningLineTo1 <= 10, 'Yes','No') AS IsMLGt4LessEq10,
IF (MorningLineTo1 > 10 and  MorningLineTo1 <= 20, 'Yes','No') AS IsMLGt10LessEq20,
IF (MorningLineTo1 > 20 and  MorningLineTo1 <= 30, 'Yes','No') AS IsMLGt20LessEq30,
IF (MorningLineTo1 > 30, 'Yes','No') AS IsMLGt30,
DebutIndicator,
TurfIndicator, 
Sex,
Age,
FinishPos,
IF (FinishPos = 1, 'WON','LOST') AS Finish, 
IF (DistanceInFurlongs >= 8, 'Route', 'Sprint') AS Distance,
IF (TrnTrackRank = 1 ,'Yes','No') AS IsTopTrnTrack,
IF (JkyTrackRank = 1 ,'Yes','No') AS IsTopJkyTrack,
IF (TrnTrackRank > 0 and TrnTrackRank < 21 ,'Yes','No') AS IsTrnTop20Track,
IF (JkyTrackRank > 0 and JkyTrackRank < 21,'Yes','No') AS IsJkyTop20Track,
IF (IsTrnTodayMinus,'Yes','No') AS IsTrnTodayMinus,
IF (OwnWinsRank > 0,'Yes','No') AS IsOwnerTopWins,
IF (OwnEarningsRank,'Yes','No') AS IsOwnerTopEarnings,
IF (IsBlinkersOn, 'Yes','No') AS IsBlinkersOn,
IF (IsBlinkersOff, 'Yes','No') AS IsBlinkersOff,
IF (NbrWorksLast > 0,'Yes','No') AS WorkedSinceLast,
IF (StartsWorks21 > 0,'Yes','No') AS StartedWorkedLast21,
IF (StartsWorks21 > 0 or NbrWorksLast > 0 ,'Yes','No') AS IsActive,
IF (IsClaimed1Back,'Yes','No') AS IsClaimed1Back ,
IF (IsClaimed2Back,'Yes','No') AS IsClaimed2Back  ,
IF (IsDirtToTurf ,'Yes','No') AS IsDirtToTurf ,
IF (IsTurfToDirt ,'Yes','No') AS IsTurfToDirt,
IF (IsSprToRte ,'Yes','No') AS IsSprToRte,
IF (IsRteToSpr,'Yes','No') AS IsRteToSpr,
IF (IsUpInClass,'Yes','No') AS IsUpInClass,
IF (IsDownInClass,'Yes','No') AS IsDownInClass,
IF (Is1stClaiming ,'Yes','No') AS Is1stClaiming,
IF (Is1stMCL,'Yes','No') AS Is1stMCL,
IF (IsHiddenWorkout ,'Yes','No') AS IsHiddenWorkout,
IF (Is1stAfterLayoff,'Yes','No') AS Is1stAfterLayoff,
IF (Is2ndAfterLayoff,'Yes','No') AS Is2ndAfterLayoff,                           
IF (Is3rdAfterLayoff,'Yes','No') AS Is3rdAfterLayoff,                           
IF (IsDirtToTurfToDirtAfterLayoff,'Yes','No') AS IsDirtToTurfToDirtAfterLayoff,
IF (IsTurfToDirtToTurfAfterLayoff,'Yes','No') AS IsTurfToDirtToTurfAfterLayoff,
IF (IsRouteToSprintToRouteAfterLayoff,'Yes','No') AS IsRouteToSprintToRouteAfterLayoff,
IF (IsSprintToRouteToSprintAfterLayoff,'Yes','No') AS IsSprintToRouteToSprintAfterLayoff,
IF (IsOnlySpeed,'Yes','No') AS IsOnlySpeed,
IF (IsKleinSpeed,'Yes','No') AS IsKleinSpeed,
IF (IsQuirinSpeed,'Yes','No') AS IsQuirinSpeed,
IF (IsKleinSpeed2,'Yes','No') AS IsKleinSpeed2,
IF (IsQuirinSpeed2,'Yes','No') AS IsQuirinSpeed2,
IF (IsProvenSpeed,'Yes','No') AS IsProvenSpeed,
IF (IsProvenSpeedPlus,'Yes','No') AS IsProvenSpeedPlus,
IF (IsXtremeSpeed,'Yes','No') AS IsXtremeSpeed,
IF (IsXtremeSpeed2,'Yes','No') AS IsXtremeSpeed2,
IF (IsLastRaceTurnMove,'Yes','No') AS IsLastRaceTurnMove,
IF (IsLastRaceFinalFurlongMove,'Yes','No') AS IsLastRaceFinalFurlongMove,
IF (IsPrevToLastRaceTurnMove,'Yes','No') AS IsPrevToLastRaceTurnMove,
IF (IsPrevToLastRaceFinalFurlongMove,'Yes','No') AS IsPrevToLastRaceFinalFurlongMove,
IF (Is2yoBred,'Yes','No') AS Is2yoBred, 
IF (Is1stBred,'Yes','No') AS Is1stBred,
IF (IsTurfBred,'Yes','No') AS IsTurfBred,
IF (IsKeyRace,'Yes','No') AS IsKeyRace,
IF (IsBouncyBouncy,'Yes','No') AS IsBouncyBouncy,
IF (IsBestEffortLast,'Yes','No') AS IsBestEffortLast,
IF (IsShipIn,'Yes','No') AS IsShipIn,
IF (IsYouBetTrack,'Yes','No') AS IsYouBetTrack,
IF (IsVerifiedClaim,'Yes','No') AS IsVerifiedClaim,
IF (IsBetLast,'Yes','No') AS IsBetLast,
IF (IsUltimateFormFactor,'Yes','No') AS IsUltimateFormFactor,
IF (IsFormConsistent ,'Yes','No') AS IsFormConsistent,
IF (IsUnexpectedEarlySpeed ,'Yes','No') AS IsUnexpectedEarlySpeed ,
IF (IsFirstTimeJuice,'Yes','No') AS IsFirstTimeJuice,
IF (IsSecondTimeJuice,'Yes','No') AS IsSecondTimeJuice, 
IF (FinishPos < 2, Odds,0)  As WinsOdds,
IF (FinishPos > 1, Odds,0)  As OtherOdds
INTO qrySpeed
FROM HorseHistory 
WHERE 
(RaceDate >= '2006-02-01') AND
(Odds > 0) AND
(FinishPos > 0) AND 
(IsXtremeSpeed=TRUE) AND
(IsYouBetTrack=TRUE);
