unit ReportHospital;

interface

uses
   Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
   ComCtrls, ExtCtrls, DBISAMTb, ppComm, ppRelatv, ppDB, ppDBPipe, Db,
   ppBands, ppClass, ppModule, raCodMod, ppCtrls, ppMemo, ppVar,
   ppReport, ppStrtch, ppSubRpt, ppPrnabl, ppCache, ppProd, StdCtrls,
   daDataModule, ppParameter, mLog, ppBarCod;

type
   THospitalReportForm = class(TForm)
      dbHospitalReport: TDBISAMDatabase;
      staBar: TStatusBar;
      pnlPrgBar: TPanel;
      prgBar: TProgressBar;
      btnCreatePdf: TButton;
      tblRacesLoop: TDBISAMTable;
      tblRacesMaster: TDBISAMTable;
      plRacesReport: TppDBPipeline;
      dsRacesMaster: TDataSource;
      timCloseFormCheck: TTimer;
      ppParameterList1: TppParameterList;
      dsEntries: TDataSource;
      plEntries: TppDBPipeline;
      ppHospitalReport: TppReport;
      hLog: TmLog;
      tblEntries: TDBISAMTable;
      ppHeaderBand1: TppHeaderBand;
      ppDBText1: TppDBText;
      ppDBText2: TppDBText;
      ppLabel24: TppLabel;
      ppSystemVariable1: TppSystemVariable;
      ppDBText8: TppDBText;
      ppDetailBand1: TppDetailBand;
      ppSubReport1: TppSubReport;
      ppChildReport12: TppChildReport;
      aTitleBand: TppTitleBand;
      RaceDesc: TppDBText;
      ppLabel5: TppLabel;
      ppLabel6: TppLabel;
      ppLabel10: TppLabel;
      ppLabel14: TppLabel;
      ppLabel8: TppLabel;
      ppLabel27: TppLabel;
      ppLabel28: TppLabel;
      ppLabel29: TppLabel;
      ppLabel20: TppLabel;
      ppLabel9: TppLabel;
      ppLabel30: TppLabel;
      ppLabel37: TppLabel;
      ppLabel38: TppLabel;
      ppLabel41: TppLabel;
      ppLabel12: TppLabel;
      ppLabel7: TppLabel;
      ppLabel26: TppLabel;
      ppLabel19: TppLabel;
      ppLabel18: TppLabel;
      ppLabel35: TppLabel;
      ppLabel36: TppLabel;
      ppLabel15: TppLabel;
      ppLabel60: TppLabel;
      ppLabel44: TppLabel;
      ppLabel46: TppLabel;
      ppLabel57: TppLabel;
      RaceCondition: TppDBMemo;
      ppLabel61: TppLabel;
      ppLabel33: TppLabel;
      ppLabel50: TppLabel;
      ppDBText6: TppDBText;
      ppDBText7: TppDBText;
      ppLabel23: TppLabel;
      ppLabel39: TppLabel;
      ppLabel1: TppLabel;
      lblSireTurf: TppLabel;
      lblSire2yo: TppLabel;
      ppLabel34: TppLabel;
      ppLabel2: TppLabel;
      ppDBText11: TppDBText;
      ppDBText16: TppDBText;
      ppLabel11: TppLabel;
      ppLabel40: TppLabel;
      ppLabel53: TppLabel;
      ppLabel55: TppLabel;
      ppDBText18: TppDBText;
      ppLabel59: TppLabel;
      ppLabel63: TppLabel;
      lblPowerOrder: TppLabel;
      WagerSheetOrder: TppDBText;
      ppLine8: TppLine;
      lblErlPace: TppLabel;
      lblMidPace: TppLabel;
      lblLatePace: TppLabel;
      ErlPaceSheetOrder: TppDBText;
      MidPaceSheetOrder: TppDBText;
      LatePaceSheetOrder: TppDBText;
      ppLine23: TppLine;
      ppHeaderBand2: TppHeaderBand;
      aDetailBand: TppDetailBand;
      ppLine5: TppLine;
      ppLine14: TppLine;
      ppLine7: TppLine;
      ppLine6: TppLine;
      ppLine2: TppLine;
      ProgramNbr: TppDBText;
      Trainer: TppDBText;
      Jockey: TppDBText;
      Med: TppDBText;
      Pace: TppDBText;
      TotalTrnWinPct: TppDBText;
      TotalTrnJkyWinPct: TppDBText;
      TotalJky30WinPct: TppDBText;
      Sex: TppDBText;
      Age: TppDBText;
      ppDBText13: TppDBText;
      BredIn: TppDBText;
      TotalTrnDebutWinPct: TppDBText;
      MidPace: TppDBText;
      TotalJkyWinPct: TppDBText;
      ppLine10: TppLine;
      TotalTrnTurfWinPct: TppDBText;
      TotalTrnAftClmWinPct: TppDBText;
      TotalTrnDebutTwoWinPct: TppDBText;
      SurfaceChange: TppVariable;
      DistanceChange: TppVariable;
      lblErlPos: TppLabel;
      lblMidPos: TppLabel;
      LastComment2: TppDBText;
      TotalTrn2yoWinPct: TppDBText;
      ppLine18: TppLine;
      Equip: TppDBText;
      Weight: TppDBText;
      TotalTrnFirstJuiceWinPct: TppDBText;
      TotalTrnBlinkersOnWinPct: TppDBText;
      TotalTrnBlinkersOffWinPct: TppDBText;
      TurfIndicator: TppDBText;
      DebutIndicator: TppDBText;
      RouteIndicator: TppDBText;
      ppLine15: TppLine;
      TurfRating: TppDBText;
      Last2Comment2: TppDBText;
      ppLine4: TppLine;
      layoffline1: TppLine;
      ppLine12: TppLine;
      LastRaceDesc: TppDBText;
      Last2RaceDesc: TppDBText;
      TurfWins: TppDBText;
      MudStarts: TppDBText;
      MudWins: TppDBText;
      TrkStarts: TppDBText;
      ppDBText15: TppDBText;
      lblTrack: TppLabel;
      ppLabel67: TppLabel;
      ppLine16: TppLine;
      DaysLast: TppDBText;
      lblOnTurf: TppLabel;
      Power: TppDBText;
      ppDBText5: TppDBText;
      SireName: TppDBText;
      ML: TppDBText;
      lblRoute: TppLabel;
      RouteStarts: TppDBText;
      RouteWins: TppDBText;
      QSP1stCallRunStyle: TppDBText;
      lblSprint: TppLabel;
      SprintStarts: TppDBText;
      SprintWins: TppDBText;
      lblLife: TppLabel;
      LifeStarts: TppDBText;
      LifeWins: TppDBText;
      HorseName: TppDBText;
      ppLine13: TppLine;
      ppLine19: TppLine;
      ppLine21: TppLine;
      ppLine22: TppLine;
      TotalTrnOwnWinPct: TppDBText;
      TurfStarts: TppDBText;
      ppDBText41: TppDBText;
      OwnerName: TppDBText;
      ppLine1: TppLine;
      PowerAdvantage: TppDBText;
      ppLine3: TppLine;
      ppDBText12: TppDBText;
      ppLine9: TppLine;
      ppLine11: TppLine;
      ppLine20: TppLine;
      TotalTrn46To120WinPct: TppDBText;
      ppLabel22: TppLabel;
      PostPos: TppDBText;
      TotalTrn30WinPct: TppDBText;
      ppLine25: TppLine;
      ppLine26: TppLine;
      ppLine27: TppLine;
      ppLine28: TppLine;
      ppLine29: TppLine;
      ClassRating: TppDBText;
      DistanceRating: TppDBText;
      MudRating: TppDBText;
      ppLine30: TppLine;
      ppLine31: TppLine;
      TodaysWagerWinPct: TppDBText;
      ppFooterBand1: TppFooterBand;
      ppSummaryWagerTypeBand: TppSummaryBand;
      dbWagerType: TppDBMemo;
      ppGroup1: TppGroup;
      ppGroupHeaderBand1: TppGroupHeaderBand;
      ppGroupFooterBand1: TppGroupFooterBand;
      raCodeModule1: TraCodeModule;
      ppGroup2: TppGroup;
      ppGroupHeaderBand2: TppGroupHeaderBand;
      ppGroupFooterBand2: TppGroupFooterBand;
      ppDBText3: TppDBText;
      ppDBText4: TppDBText;
      ppDBText9: TppDBText;
      ppDBText19: TppDBText;
      ppDBText21: TppDBText;
      ppDBText22: TppDBText;
      ppDBText23: TppDBText;
    ppLabel4: TppLabel;
    ppLabel13: TppLabel;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppLabel16: TppLabel;
    ppDBText27: TppDBText;
    TrainerJockeySheetOrder: TppDBText;
    ppLabel21: TppLabel;
    ppDBText29: TppDBText;
    TurfSheetOrder: TppDBText;
    ppLabel25: TppLabel;
    ppLabel31: TppLabel;
    ppLabel42: TppLabel;
    MaidenSheetOrder: TppDBText;
    ppLabel17: TppLabel;
    ppDBText20: TppDBText;
    ppDBText24: TppDBText;
    ppDBText30: TppDBText;
    ppDBText31: TppDBText;
    ppDBText32: TppDBText;
    ppDBText33: TppDBText;
    ppDBText34: TppDBText;
    ppDBText35: TppDBText;
    ppDBText36: TppDBText;
    ppDBText37: TppDBText;
    ppDBText38: TppDBText;
    ppLabel47: TppLabel;
    ppLabel48: TppLabel;
    ppLabel49: TppLabel;
    ppLabel43: TppLabel;
    ppDBText10: TppDBText;
    ppDBText14: TppDBText;
    ppLabel45: TppLabel;
    ppLabel51: TppLabel;
    ppDBText28: TppDBText;
    ppDBText39: TppDBText;
    ppLine17: TppLine;
    ppLine32: TppLine;
    ppLabel52: TppLabel;
    ppDBText40: TppDBText;
    ppDBText42: TppDBText;
    ppLabel54: TppLabel;
    ppLabel56: TppLabel;
    ppLabel58: TppLabel;
    ppLine34: TppLine;
    ppLabel62: TppLabel;
    ppLine33: TppLine;
    ppLine35: TppLine;
    ppDBText43: TppDBText;
    ppLabel64: TppLabel;
    ppDBText44: TppDBText;
    ppLabel65: TppLabel;
    tblEntriesTrkCode: TStringField;
    tblEntriesRaceDate: TDateField;
    tblEntriesRangeRaceDate: TDateField;
    tblEntriesRaceNbr: TSmallintField;
    tblEntriesPostPos: TSmallintField;
    tblEntriesRaceType: TStringField;
    tblEntriesSurface: TStringField;
    tblEntriesEstTimeOfRace: TTimeField;
    tblEntriesDistanceInFurlongs: TFloatField;
    tblEntriesEntry: TStringField;
    tblEntriesProgramNbr: TStringField;
    tblEntriesProgramNbrSort: TSmallintField;
    tblEntriesMorningLineDesc: TStringField;
    tblEntriesHorseName: TStringField;
    tblEntriesMed: TStringField;
    tblEntriesEquip: TStringField;
    tblEntriesIsFirstTimeJuice: TBooleanField;
    tblEntriesIsBlinkersOn: TBooleanField;
    tblEntriesIsBlinkersOff: TBooleanField;
    tblEntriesTurfIndicator: TStringField;
    tblEntriesDebutIndicator: TStringField;
    tblEntriesRouteIndicator: TStringField;
    tblEntriesMudIndicator: TStringField;
    tblEntriesIsScratched: TBooleanField;
    tblEntriesAge: TSmallintField;
    tblEntriesSex: TStringField;
    tblEntriesColor: TStringField;
    tblEntriesWeight: TStringField;
    tblEntriesIsSuperTrainer: TBooleanField;
    tblEntriesTrainer: TStringField;
    tblEntriesTrnWinsRank: TSmallintField;
    tblEntriesTrnEarningsRank: TSmallintField;
    tblEntriesTrnTrackRank: TSmallintField;
    tblEntriesIsSuperJockey: TBooleanField;
    tblEntriesJockey: TStringField;
    tblEntriesJkyWinsRank: TSmallintField;
    tblEntriesJkyEarningsRank: TSmallintField;
    tblEntriesJkyTrackRank: TSmallintField;
    tblEntriesIsSuperOwner: TBooleanField;
    tblEntriesOwner: TStringField;
    tblEntriesOwnWinsRank: TSmallintField;
    tblEntriesOwnEarningsRank: TSmallintField;
    tblEntriesBreeder: TStringField;
    tblEntriesTotalTrnStarts: TSmallintField;
    tblEntriesTotalTrnWins: TSmallintField;
    tblEntriesTotalTrnWinPct: TFloatField;
    tblEntriesTotalTrnWinPctRank: TSmallintField;
    tblEntriesTotalTrnJkyStarts: TSmallintField;
    tblEntriesTotalTrnJkyWins: TSmallintField;
    tblEntriesTotalTrnJkyWinPct: TFloatField;
    tblEntriesTotalTrnJkyWinPctRank: TSmallintField;
    tblEntriesTotalTrnOwnStarts: TSmallintField;
    tblEntriesTotalTrnOwnWins: TSmallintField;
    tblEntriesTotalTrnOwnWinPct: TFloatField;
    tblEntriesTotalTrnOwnWinPctRank: TSmallintField;
    tblEntriesTotalTrn1To45Starts: TSmallintField;
    tblEntriesTotalTrn1To45Wins: TSmallintField;
    tblEntriesTotalTrn1To45WinPct: TFloatField;
    tblEntriesTotalTrnWork1To45Starts: TSmallintField;
    tblEntriesTotalTrnWork1To45Wins: TSmallintField;
    tblEntriesTotalTrnWork1To45WinPct: TFloatField;
    tblEntriesTotalTrn46To120Starts: TSmallintField;
    tblEntriesTotalTrn46To120Wins: TSmallintField;
    tblEntriesTotalTrn46To120WinPct: TFloatField;
    tblEntriesTotalTrnWork46To120Starts: TSmallintField;
    tblEntriesTotalTrnWork46To120Wins: TSmallintField;
    tblEntriesTotalTrnWork46To120WinPct: TFloatField;
    tblEntriesTotalTrn120PlusStarts: TSmallintField;
    tblEntriesTotalTrn120PlusWins: TSmallintField;
    tblEntriesTotalTrn120PlusWinPct: TFloatField;
    tblEntriesTotalTrnWork120PlusStarts: TSmallintField;
    tblEntriesTotalTrnWork120PlusWins: TSmallintField;
    tblEntriesTotalTrnWork120PlusWinPct: TFloatField;
    tblEntriesTotalTrnDebutStarts: TSmallintField;
    tblEntriesTotalTrnDebutWins: TSmallintField;
    tblEntriesTotalTrnDebutWinPct: TFloatField;
    tblEntriesTotalTrnDebutTwoStarts: TSmallintField;
    tblEntriesTotalTrnDebutTwoWins: TSmallintField;
    tblEntriesTotalTrnDebutTwoWinPct: TFloatField;
    tblEntriesTotalTrnFirstJuiceStarts: TSmallintField;
    tblEntriesTotalTrnFirstJuiceWins: TSmallintField;
    tblEntriesTotalTrnFirstJuiceWinPct: TFloatField;
    tblEntriesTotalTrnBlinkersOnStarts: TSmallintField;
    tblEntriesTotalTrnBlinkersOnWins: TSmallintField;
    tblEntriesTotalTrnBlinkersOnWinPct: TFloatField;
    tblEntriesTotalTrnBlinkersOffStarts: TSmallintField;
    tblEntriesTotalTrnBlinkersOffWins: TSmallintField;
    tblEntriesTotalTrnBlinkersOffWinPct: TFloatField;
    tblEntriesTotalTrnTurfStarts: TSmallintField;
    tblEntriesTotalTrnTurfWins: TSmallintField;
    tblEntriesTotalTrnTurfWinPct: TFloatField;
    tblEntriesTotalTrnTurfWinPctRank: TSmallintField;
    tblEntriesTotalTrn30Starts: TSmallintField;
    tblEntriesTotalTrn30Wins: TSmallintField;
    tblEntriesTotalTrn30WinPct: TFloatField;
    tblEntriesTotalTrn30WinPctRank: TSmallintField;
    tblEntriesTotalTrnAftClmStarts: TSmallintField;
    tblEntriesTotalTrnAftClmWins: TSmallintField;
    tblEntriesTotalTrnAftClmWinPct: TFloatField;
    tblEntriesTotalTrnOddsStarts: TSmallintField;
    tblEntriesTotalTrnOddsWins: TSmallintField;
    tblEntriesTotalTrnOddsWinPct: TFloatField;
    tblEntriesTotalTrnOddsWinPctRank: TSmallintField;
    tblEntriesTotalTrn1stStarts: TSmallintField;
    tblEntriesTotalTrn1stWins: TSmallintField;
    tblEntriesTotalTrn1stWinPct: TFloatField;
    tblEntriesTotalTrn2yoStarts: TSmallintField;
    tblEntriesTotalTrn2yoWins: TSmallintField;
    tblEntriesTotalTrn2yoWinPct: TFloatField;
    tblEntriesTotalTrn2oWinPctRank: TSmallintField;
    tblEntriesTrnTodayStarts: TSmallintField;
    tblEntriesTrnTodayWins: TSmallintField;
    tblEntriesTrnTodayWinPct: TFloatField;
    tblEntriesTrnTodayWinPctRank: TSmallintField;
    tblEntriesTrnDirtToTurfStarts: TSmallintField;
    tblEntriesTrnDirtToTurfWinPct: TSmallintField;
    tblEntriesTrnTurfToDirtStarts: TSmallintField;
    tblEntriesTrnTurfToDirtWinPct: TSmallintField;
    tblEntriesTrnRteToSprStarts: TSmallintField;
    tblEntriesTrnRteToSprWinPct: TSmallintField;
    tblEntriesTrnSprToRteStarts: TSmallintField;
    tblEntriesTrnSprToRteWinPct: TSmallintField;
    tblEntriesTrnStkWinPct: TSmallintField;
    tblEntriesTrnClmWinPct: TSmallintField;
    tblEntriesTrnMdnWinPct: TSmallintField;
    tblEntriesTrnAlwWinPct: TSmallintField;
    tblEntriesTotalJkyStarts: TSmallintField;
    tblEntriesTotalJkyWins: TSmallintField;
    tblEntriesTotalJkyWinPct: TFloatField;
    tblEntriesTotalJkyWinPctRank: TSmallintField;
    tblEntriesTotalJkyDaysStarts: TSmallintField;
    tblEntriesTotalJkyDaysWins: TSmallintField;
    tblEntriesTotalJkyDaysWinPctRank: TSmallintField;
    tblEntriesTotalJkyDaysWinPct: TFloatField;
    tblEntriesTotalJkyOddsStarts: TSmallintField;
    tblEntriesTotalJkyOddsWins: TSmallintField;
    tblEntriesTotalJkyOddsWinPct: TFloatField;
    tblEntriesTotalJkyOddsWinPctRank: TSmallintField;
    tblEntriesTotalJkyTurfStarts: TSmallintField;
    tblEntriesTotalJkyTurfWins: TSmallintField;
    tblEntriesTotalJkyTurfWinPct: TFloatField;
    tblEntriesTotalJky10Starts: TSmallintField;
    tblEntriesTotalJky10Wins: TSmallintField;
    tblEntriesTotalJky10WinPct: TFloatField;
    tblEntriesTotalJky10WinPctRank: TSmallintField;
    tblEntriesTotalJky30Starts: TSmallintField;
    tblEntriesTotalJky30Wins: TSmallintField;
    tblEntriesTotalJky30WinPct: TFloatField;
    tblEntriesTotalJky30WinPctRank: TSmallintField;
    tblEntriesTotalJky2yoStarts: TSmallintField;
    tblEntriesTotalJky2yoWins: TSmallintField;
    tblEntriesTotalJky2yoWinPct: TFloatField;
    tblEntriesTotalOwnStarts: TSmallintField;
    tblEntriesTotalOwnWins: TSmallintField;
    tblEntriesTotalOwnWinPct: TFloatField;
    tblEntriesTotalOwnWinPctRank: TSmallintField;
    tblEntriesTotalOwnTop3WinPct: TSmallintField;
    tblEntriesTotalBrdStarts: TSmallintField;
    tblEntriesTotalBrdWins: TSmallintField;
    tblEntriesTotalBrdWinPct: TFloatField;
    tblEntriesTotalBrdWinPctRank: TSmallintField;
    tblEntriesBredIn: TStringField;
    tblEntriesSire: TStringField;
    tblEntriesSireTurfLastYearRank: TSmallintField;
    tblEntriesSireTurfLastYearStarts: TIntegerField;
    tblEntriesSireTurfLastYearPctOfEarnings: TSmallintField;
    tblEntriesSireGeneralLastYearRank: TSmallintField;
    tblEntriesSireGeneralLastYearStudFee: TFloatField;
    tblEntriesSireJuvenileLastYearRank: TSmallintField;
    tblEntriesSireJuvenileThisYearRank: TSmallintField;
    tblEntriesSireTurfThisYearRank: TSmallintField;
    tblEntriesSireTurfThisYearStarts: TIntegerField;
    tblEntriesSireTurfThisYearPctOfEarnings: TSmallintField;
    tblEntriesSireGeneralThisYearRank: TSmallintField;
    tblEntriesSireGeneralThisYearStudFee: TFloatField;
    tblEntriesSireAEI: TFloatField;
    tblEntriesSireAWThisYearRank: TSmallintField;
    tblEntriesSireAWLastYearRank: TSmallintField;
    tblEntriesDam: TStringField;
    tblEntriesDamSire: TStringField;
    tblEntriesDamSireTurfLastYearRank: TSmallintField;
    tblEntriesDamSireTurfLastYearStarts: TIntegerField;
    tblEntriesDamSireTurfLastYearPctOfEarnings: TSmallintField;
    tblEntriesDamSireGeneralLastYearRank: TSmallintField;
    tblEntriesDamSireGeneralLastYearStudFee: TFloatField;
    tblEntriesDamSireJuvenileLastYearRank: TSmallintField;
    tblEntriesDamSireJuvenileThisYearRank: TSmallintField;
    tblEntriesDamSireTurfThisYearRank: TSmallintField;
    tblEntriesDamSireTurfThisYearStarts: TIntegerField;
    tblEntriesDamSireTurfThisYearPctOfEarnings: TSmallintField;
    tblEntriesDamSireGeneralThisYearRank: TSmallintField;
    tblEntriesDamSireGeneralThisYearStudFee: TFloatField;
    tblEntriesDamSireAEI: TFloatField;
    tblEntriesDamSireAWThisYearRank: TSmallintField;
    tblEntriesDamSireAWLastYearRank: TSmallintField;
    tblEntriesDaysLast: TSmallintField;
    tblEntriesDaysLastWork: TSmallintField;
    tblEntriesLastTrkCode: TStringField;
    tblEntriesLastRaceNbr: TIntegerField;
    tblEntriesLastRaceDate: TDateField;
    tblEntriesLastPostPos: TSmallintField;
    tblEntriesLastRaceType: TStringField;
    tblEntriesLastSurf: TStringField;
    tblEntriesLastRaceConditions: TStringField;
    tblEntriesLastDistanceDesc: TStringField;
    tblEntriesLastDistance: TFloatField;
    tblEntriesLastOdds: TFloatField;
    tblEntriesLastFavoriteIndicator: TStringField;
    tblEntriesLastDQIndicator: TStringField;
    tblEntriesLastJockey: TStringField;
    tblEntriesLastComment: TStringField;
    tblEntriesLastComment2: TStringField;
    tblEntriesLastTrkCond: TStringField;
    tblEntriesLastClmPrice: TFloatField;
    tblEntriesLastClaimed: TStringField;
    tblEntriesLastPurse: TFloatField;
    tblEntriesLastDay: TStringField;
    tblEntriesLastMonthDesc: TStringField;
    tblEntriesLastYear: TStringField;
    tblEntriesLastGateBreak: TStringField;
    tblEntriesLastLen1Back: TStringField;
    tblEntriesLastLen2Back: TStringField;
    tblEntriesLastStLenBack: TStringField;
    tblEntriesLastFinishBeaten: TStringField;
    tblEntriesLastEquip: TStringField;
    tblEntriesLastWeight: TIntegerField;
    tblEntriesLastHorseTime: TFloatField;
    tblEntriesLastRaceDesc: TStringField;
    tblEntriesMorningLineTo1: TFloatField;
    tblEntriesMorningLineTo1Rank: TSmallintField;
    tblEntriesIsDirtToTurf: TBooleanField;
    tblEntriesIsTurfToDirt: TBooleanField;
    tblEntriesIsSprToRte: TBooleanField;
    tblEntriesIsRteToSpr: TBooleanField;
    tblEntriesLastSpeed: TSmallintField;
    tblEntriesLastSpeedRank: TSmallintField;
    tblEntriesPower: TFloatField;
    tblEntriesPowerRank: TSmallintField;
    tblEntriesBackSpeed: TSmallintField;
    tblEntriesBackSpeedRank: TSmallintField;
    tblEntriesAvgClass: TFloatField;
    tblEntriesAvgClassRank: TSmallintField;
    tblEntriesAvgSpeed: TSmallintField;
    tblEntriesAvgSpeedRank: TSmallintField;
    tblEntriesAvgClassRating: TFloatField;
    tblEntriesAvgClassRatingRank: TSmallintField;
    tblEntriesBackClass: TFloatField;
    tblEntriesBackClassRank: TSmallintField;
    tblEntriesCurrClass: TFloatField;
    tblEntriesCurrClassRank: TSmallintField;
    tblEntriesEarlyPace: TFloatField;
    tblEntriesEarlyPaceRank: TSmallintField;
    tblEntriesEarlyPacePos: TFloatField;
    tblEntriesEarlyPacePosRank: TSmallintField;
    tblEntriesMiddlePace: TFloatField;
    tblEntriesMiddlePaceRank: TSmallintField;
    tblEntriesMiddlePacePos: TFloatField;
    tblEntriesMiddlePacePosRank: TSmallintField;
    tblEntriesLatePace: TFloatField;
    tblEntriesLatePaceRank: TSmallintField;
    tblEntriesLatePacePos: TFloatField;
    tblEntriesLatePacePosRank: TSmallintField;
    tblEntriesFinishPacePos: TFloatField;
    tblEntriesFinishPacePosRank: TSmallintField;
    tblEntriesEarlyPaceAdvantage: TFloatField;
    tblEntriesMiddlePaceAdvantage: TFloatField;
    tblEntriesLatePaceAdvantage: TFloatField;
    tblEntriesIsClaimed1Back: TBooleanField;
    tblEntriesIsClaimed2Back: TBooleanField;
    tblEntriesIsLayoffAndUp: TBooleanField;
    tblEntriesIsClaimedAndUp: TBooleanField;
    tblEntriesIsClaimedAndDown: TBooleanField;
    tblEntriesIsFirstTimeClaiming: TBooleanField;
    tblEntriesIsBelowClaimedPrice: TBooleanField;
    tblEntriesLifeStarts: TSmallintField;
    tblEntriesLifeWins: TSmallintField;
    tblEntriesLifePlcs: TSmallintField;
    tblEntriesLifeShos: TSmallintField;
    tblEntriesLifeEarnings: TIntegerField;
    tblEntriesLifeEPS: TIntegerField;
    tblEntriesTurfStarts: TSmallintField;
    tblEntriesTurfWins: TSmallintField;
    tblEntriesTurfPlcs: TSmallintField;
    tblEntriesTurfShos: TSmallintField;
    tblEntriesTurfEarnings: TIntegerField;
    tblEntriesTurfEPS: TIntegerField;
    tblEntriesMudStarts: TSmallintField;
    tblEntriesMudWins: TSmallintField;
    tblEntriesMudPlcs: TSmallintField;
    tblEntriesMudShos: TSmallintField;
    tblEntriesMudEarnings: TIntegerField;
    tblEntriesMudEPS: TIntegerField;
    tblEntriesTrkStarts: TSmallintField;
    tblEntriesTrkWins: TSmallintField;
    tblEntriesTrkPlcs: TSmallintField;
    tblEntriesTrkShos: TSmallintField;
    tblEntriesTrkEarnings: TIntegerField;
    tblEntriesTrkEPS: TIntegerField;
    tblEntriesRouteStarts: TSmallintField;
    tblEntriesRouteWins: TSmallintField;
    tblEntriesRoutePlcs: TSmallintField;
    tblEntriesRouteShos: TSmallintField;
    tblEntriesSprintStarts: TSmallintField;
    tblEntriesSprintWins: TSmallintField;
    tblEntriesSprintPlcs: TSmallintField;
    tblEntriesSprintShos: TSmallintField;
    tblEntriesAngleDesc: TStringField;
    tblEntriesIsWagerSheetSelected: TBooleanField;
    tblEntriesIsYouBetTrack: TBooleanField;
    tblEntriesIsPrintedOnValueSheet: TBooleanField;
    tblEntriesHorseNbr: TSmallintField;
    tblEntriesWorkLine1: TStringField;
    tblEntriesWorkLine2: TStringField;
    tblEntriesIsFrontDoubleLiner: TBooleanField;
    tblEntriesIsBackDoubleLiner: TBooleanField;
    tblEntriesIsTripleLiner: TBooleanField;
    tblEntriesIsFrontDoubleDot: TBooleanField;
    tblEntriesIsBackDoubleDot: TBooleanField;
    tblEntriesIsTripleDot: TBooleanField;
    tblEntriesIsFrontDoubleLiner0: TBooleanField;
    tblEntriesIsBackDoubleLiner0: TBooleanField;
    tblEntriesIsTripleLiner0: TBooleanField;
    tblEntriesIsFrontDoubleLiner1: TBooleanField;
    tblEntriesIsBackDoubleLiner1: TBooleanField;
    tblEntriesIsTripleLiner1: TBooleanField;
    tblEntriesIsFrontDoubleLiner2: TBooleanField;
    tblEntriesIsBackDoubleLiner2: TBooleanField;
    tblEntriesIsTripleLiner2: TBooleanField;
    tblEntriesIsFrontDoubleLiner3: TBooleanField;
    tblEntriesIsBackDoubleLiner3: TBooleanField;
    tblEntriesIsTripleLiner3: TBooleanField;
    tblEntriesTodaysWagerOrderKey: TStringField;
    tblEntriesTodaysWagerStarts: TIntegerField;
    tblEntriesTodaysWagerWins: TIntegerField;
    tblEntriesTodaysWagerWinPct: TFloatField;
    tblEntriesTodaysWagerWinPctRank: TSmallintField;
    tblEntriesTodaysWagerAvgOdds: TFloatField;
    tblEntriesTodaysWagerMinOdds: TFloatField;
    tblEntriesTodaysWagerMaxOdds: TFloatField;
    tblEntriesTodaysWagerAvgWinOdds: TFloatField;
    tblEntriesTodaysWagerMinWinOdds: TFloatField;
    tblEntriesTodaysWagerMaxWinOdds: TFloatField;
    tblEntriesTodaysWagerValueBet: TFloatField;
    tblEntriesLast2TrkCode: TStringField;
    tblEntriesLast2RaceNbr: TIntegerField;
    tblEntriesLast2RaceDate: TDateField;
    tblEntriesLast2PostPos: TSmallintField;
    tblEntriesLast2RaceType: TStringField;
    tblEntriesLast2Surf: TStringField;
    tblEntriesLast2RaceConditions: TStringField;
    tblEntriesLast2DistanceDesc: TStringField;
    tblEntriesLast2Distance: TFloatField;
    tblEntriesLast2Odds: TFloatField;
    tblEntriesLast2FavoriteIndicator: TStringField;
    tblEntriesLast2DQIndicator: TStringField;
    tblEntriesLast2Jockey: TStringField;
    tblEntriesLast2Comment: TStringField;
    tblEntriesLast2Comment2: TStringField;
    tblEntriesLast2TrkCond: TStringField;
    tblEntriesLast2ClmPrice: TFloatField;
    tblEntriesLast2Claimed: TStringField;
    tblEntriesLast2Purse: TFloatField;
    tblEntriesLast2Day: TStringField;
    tblEntriesLast2MonthDesc: TStringField;
    tblEntriesLast2Year: TStringField;
    tblEntriesLast2GateBreak: TStringField;
    tblEntriesLast2Len1Back: TStringField;
    tblEntriesLast2Len2Back: TStringField;
    tblEntriesLast2StLenBack: TStringField;
    tblEntriesLast2FinishBeaten: TStringField;
    tblEntriesLast2Equip: TStringField;
    tblEntriesLast2Weight: TIntegerField;
    tblEntriesLast2Speed: TIntegerField;
    tblEntriesLast2HorseTime: TFloatField;
    tblEntriesLast2RaceDesc: TStringField;
    tblEntriesLast3TrkCode: TStringField;
    tblEntriesLast3RaceNbr: TIntegerField;
    tblEntriesLast3RaceDate: TDateField;
    tblEntriesLast3PostPos: TSmallintField;
    tblEntriesLast3RaceType: TStringField;
    tblEntriesLast3Surf: TStringField;
    tblEntriesLast3RaceConditions: TStringField;
    tblEntriesLast3DistanceDesc: TStringField;
    tblEntriesLast3Distance: TFloatField;
    tblEntriesLast3Odds: TFloatField;
    tblEntriesLast3FavoriteIndicator: TStringField;
    tblEntriesLast3DQIndicator: TStringField;
    tblEntriesLast3Jockey: TStringField;
    tblEntriesLast3Comment: TStringField;
    tblEntriesLast3Comment2: TStringField;
    tblEntriesLast3TrkCond: TStringField;
    tblEntriesLast3ClmPrice: TFloatField;
    tblEntriesLast3Claimed: TStringField;
    tblEntriesLast3Purse: TFloatField;
    tblEntriesLast3Day: TStringField;
    tblEntriesLast3MonthDesc: TStringField;
    tblEntriesLast3Year: TStringField;
    tblEntriesLast3GateBreak: TStringField;
    tblEntriesLast3Len1Back: TStringField;
    tblEntriesLast3Len2Back: TStringField;
    tblEntriesLast3StLenBack: TStringField;
    tblEntriesLast3FinishBeaten: TStringField;
    tblEntriesLast3Equip: TStringField;
    tblEntriesLast3Weight: TIntegerField;
    tblEntriesLast3Speed: TIntegerField;
    tblEntriesLast3HorseTime: TFloatField;
    tblEntriesLast3RaceDesc: TStringField;
    tblEntriesOdds: TFloatField;
    tblEntriesFinishPos: TFloatField;
    tblEntriesQSP1stCall: TSmallintField;
    tblEntriesQSP1stCallRank: TSmallintField;
    tblEntriesQSP1stCallRunStyle: TStringField;
    tblEntriesQSP2ndCall: TSmallintField;
    tblEntriesQSP2ndCallRank: TSmallintField;
    tblEntriesQSP2ndCallRunStyle: TStringField;
    tblEntriesKSP1stCall: TSmallintField;
    tblEntriesKSP1stCallRank: TSmallintField;
    tblEntriesKSP2ndCall: TSmallintField;
    tblEntriesKSP2ndCallRank: TSmallintField;
    tblEntriesLastPos1stCall: TFloatField;
    tblEntriesLastPos2ndCall: TFloatField;
    tblEntriesLastPosStrCall: TFloatField;
    tblEntriesLast2Pos1stCall: TFloatField;
    tblEntriesLast2Pos2ndCall: TFloatField;
    tblEntriesLast2PosStrCall: TFloatField;
    tblEntriesLast3Pos1stCall: TFloatField;
    tblEntriesLast3Pos2ndCall: TFloatField;
    tblEntriesLast3PosStrCall: TFloatField;
    tblEntriesLastTime1stCall: TFloatField;
    tblEntriesLastTime2ndCall: TFloatField;
    tblEntriesLastTimeStrCall: TFloatField;
    tblEntriesLastTimeFinCall: TFloatField;
    tblEntriesLast2Time1stCall: TFloatField;
    tblEntriesLast2Time2ndCall: TFloatField;
    tblEntriesLast2TimeStrCall: TFloatField;
    tblEntriesLast2TimeFinCall: TFloatField;
    tblEntriesLast3Time1stCall: TFloatField;
    tblEntriesLast3Time2ndCall: TFloatField;
    tblEntriesLast3TimeStrCall: TFloatField;
    tblEntriesLast3TimeFinCall: TFloatField;
    tblEntriesLastBL1stCall: TFloatField;
    tblEntriesLastBL2ndCall: TFloatField;
    tblEntriesLastBLStrCall: TFloatField;
    tblEntriesLastBLFinCall: TFloatField;
    tblEntriesLast2BL1stCall: TFloatField;
    tblEntriesLast2BL2ndCall: TFloatField;
    tblEntriesLast2BLStrCall: TFloatField;
    tblEntriesLast2BLFinCall: TFloatField;
    tblEntriesLast3BL1stCall: TFloatField;
    tblEntriesLast3BL2ndCall: TFloatField;
    tblEntriesLast3BLStrCall: TFloatField;
    tblEntriesLast3BLFinCall: TFloatField;
    tblEntriesLastPosFinCall: TFloatField;
    tblEntriesLast2PosFinCall: TFloatField;
    tblEntriesLast3PosFinCall: TFloatField;
    tblEntriesIs1stClaiming: TBooleanField;
    tblEntriesIs1stMCL: TBooleanField;
    tblEntriesIs1stAfterLayoff: TBooleanField;
    tblEntriesIs2ndAfterLayoff: TBooleanField;
    tblEntriesIs3rdAfterLayoff: TBooleanField;
    tblEntriesIsDirtToTurfToDirtAfterLayoff: TBooleanField;
    tblEntriesIsTurfToDirtToTurfAfterLayoff: TBooleanField;
    tblEntriesIsRouteToSprintToRouteAfterLayoff: TBooleanField;
    tblEntriesIsSprintToRouteToSprintAfterLayoff: TBooleanField;
    tblEntriesIs2yoBred: TBooleanField;
    tblEntriesIs1stBred: TBooleanField;
    tblEntriesIsTurfBred: TBooleanField;
    tblEntriesIs1stOffLayoff: TBooleanField;
    tblEntriesIs2ndOffLayoff: TBooleanField;
    tblEntriesIs3rdOffLayoff: TBooleanField;
    tblEntriesStandingIn: TStringField;
    tblEntriesStandingInRank: TSmallintField;
    tblEntriesIsOnStandingInList: TBooleanField;
    tblEntriesValueROI: TFloatField;
    tblEntriesValueROICnt: TSmallintField;
    tblEntriesValueDesc: TStringField;
    tblEntriesDollarCnt: TSmallintField;
    tblEntriesListType: TStringField;
    tblEntriesPowerAdvantage: TFloatField;
    tblEntriesPowerAdvantageKey: TIntegerField;
    tblEntriesPostPosWinPct: TSmallintField;
    tblEntriesPostPosStarts: TIntegerField;
    tblEntriesPostPosWinPctRank: TFloatField;
    tblEntriesPaceIndicatorWinPct: TFloatField;
    tblEntriesPaceIndicatorWinPctRank: TSmallintField;
    tblEntriesElimWinPct: TFloatField;
    tblEntriesElim2WinPct: TFloatField;
    tblEntriesTodaysWagerOddsDesc: TStringField;
    tblEntriesPowerAdvantageWinPct: TFloatField;
    tblEntriesEarlyPaceAdvantageWinPct: TFloatField;
    tblEntriesEarlyPaceAdvantageWinPctRank: TSmallintField;
    tblEntriesEarlyPaceAdvantageValueBet: TFloatField;
    tblEntriesMiddlePaceAdvantageWinPct: TFloatField;
    tblEntriesMiddlePaceAdvantageWinPctRank: TSmallintField;
    tblEntriesMiddlePaceAdvantageValueBet: TFloatField;
    tblEntriesLatePaceAdvantageWinPct: TFloatField;
    tblEntriesLatePaceAdvantageWinPctRank: TSmallintField;
    tblEntriesIsHeavyChalk: TBooleanField;
    tblEntriesMorningLineWinPct: TFloatField;
    tblEntriesIsEliminated: TBooleanField;
    tblEntriesIsValueDebutSelected: TBooleanField;
    tblEntriesIsValueDebutTwoSelected: TBooleanField;
    tblEntriesIsValueWagerSelected: TBooleanField;
    tblEntriesIsPTCTrack: TBooleanField;
    tblEntriesIsTwinSpiresTrack: TBooleanField;
    tblEntriesTodaysAltWagerWinPct: TFloatField;
    tblEntriesTodaysAltWagerWinPctRank: TSmallintField;
    tblEntriesSelectorChoice: TSmallintField;
    tblEntriesIsSpeedSheetSelected: TBooleanField;
    tblEntriesClassRating: TFloatField;
    tblEntriesClassRatingRank: TSmallintField;
    tblEntriesTurfRating: TFloatField;
    tblEntriesTurfRatingRank: TSmallintField;
    tblEntriesMudRating: TFloatField;
    tblEntriesMudRatingRank: TSmallintField;
    tblEntriesDistanceRating: TFloatField;
    tblEntriesDistanceRatingRank: TSmallintField;
    tblEntriesAWRating: TFloatField;
    tblEntriesAWRatingRank: TSmallintField;
    tblEntriesSireClassRating: TFloatField;
    tblEntriesSireClassRatingRank: TSmallintField;
    tblEntriesDamSireClassRating: TFloatField;
    tblEntriesDamSireClassRatingRank: TSmallintField;
    tblEntriesSireTurfRating: TFloatField;
    tblEntriesSireTurfRatingRank: TSmallintField;
    tblEntriesDamSireTurfRating: TFloatField;
    tblEntriesDamSireTurfRatingRank: TSmallintField;
    tblEntriesSireMudRatingRank: TSmallintField;
    tblEntriesSireMudRating: TFloatField;
    tblEntriesDamSireMudRating: TFloatField;
    tblEntriesDamSireMudRatingRank: TSmallintField;
    tblEntriesSireSprintRating: TFloatField;
    tblEntriesSireSprintRatingRank: TSmallintField;
    tblEntriesDamSireSprintRating: TFloatField;
    tblEntriesDamSireSprintRatingRank: TSmallintField;
    tblEntriesSireRouteRating: TFloatField;
    tblEntriesSireRouteRatingRank: TSmallintField;
    tblEntriesDamSireRouteRating: TFloatField;
    tblEntriesDamSireRouteRatingRank: TSmallintField;
    tblEntriesSireAWRating: TFloatField;
    tblEntriesSireAWRatingRank: TSmallintField;
    tblEntriesDamSireAWRating: TFloatField;
    tblEntriesDamSireAWRatingRank: TSmallintField;
    tblEntriesTrainerRating: TFloatField;
    tblEntriesTrainerRatingRank: TSmallintField;
    tblEntriesTrainerOwnerRating: TFloatField;
    tblEntriesTrainerOwnerRatingRank: TSmallintField;
    tblEntriesTrainerJockeyRating: TFloatField;
    tblEntriesTrainerJockeyRatingRank: TSmallintField;
    tblEntriesTrainerTrackRating: TFloatField;
    tblEntriesTrainerTrackRatingRank: TSmallintField;
    tblEntriesJockeyRating: TFloatField;
    tblEntriesJockeyRatingRank: TSmallintField;
    tblEntriesJockeyOwnerRating: TFloatField;
    tblEntriesJockeyOwnerRatingRank: TSmallintField;
    tblEntriesJockeyTrackRating: TFloatField;
    tblEntriesJockeyTrackRatingRank: TSmallintField;
    tblEntriesOwnerRating: TFloatField;
    tblEntriesOwnerRatingRank: TSmallintField;
    tblEntriesTurfOrder: TStringField;
    tblEntriesMaidenOrder: TStringField;
    tblEntriesMudOrder: TStringField;
    tblEntriesAWOrder: TStringField;
    tblEntriesDistanceOrder: TStringField;
    tblEntriesFinalOrderWinPct: TFloatField;
    tblEntriesFinalOrderWinPctRank: TSmallintField;
    tblEntriesFinalOrderKey: TStringField;
    tblEntriesIsTrainerSheetSelected: TBooleanField;
    tblEntriesTCPlusMinus: TIntegerField;
    tblEntriesTJMeetWinPct: TIntegerField;
    tblEntriesTJMeetStarts: TIntegerField;
    tblEntriesTJ365WinPct: TIntegerField;
    tblEntriesTJ365Starts: TIntegerField;
    tblEntriesPacificTime: TStringField;
    tblEntriesFinalWinPct: TFloatField;
    tblEntriesFinalOrderValueBet: TFloatField;
    tblRacesMasterTrkCode: TStringField;
    tblRacesMasterRaceDate: TDateField;
    tblRacesMasterRangeRaceDate: TDateField;
    tblRacesMasterRaceNbr: TSmallintField;
    tblRacesMasterEstTimeOfRace: TTimeField;
    tblRacesMasterEstTimeOfFirstRace: TTimeField;
    tblRacesMasterLocalTimeOfRace: TTimeField;
    tblRacesMasterCT: TStringField;
    tblRacesMasterSurface: TStringField;
    tblRacesMasterActualSurface: TStringField;
    tblRacesMasterAltSurface: TStringField;
    tblRacesMasterDistanceInFeet: TSmallintField;
    tblRacesMasterDistanceInYards: TSmallintField;
    tblRacesMasterDistanceInFurlongs: TFloatField;
    tblRacesMasterDistanceDesc: TStringField;
    tblRacesMasterRaceType: TStringField;
    tblRacesMasterTypeOfRace: TStringField;
    tblRacesMasterRaceTypeDesc: TStringField;
    tblRacesMasterRaceDesc: TStringField;
    tblRacesMasterRaceCondition: TMemoField;
    tblRacesMasterIsTurfRace: TBooleanField;
    tblRacesMasterIsRouteRace: TBooleanField;
    tblRacesMasterIsMaidenSpecialRace: TBooleanField;
    tblRacesMasterIsMaidenClaimingRace: TBooleanField;
    tblRacesMasterIsMaidenOrTurfRace: TBooleanField;
    tblRacesMasterIsTwoYearOldRace: TBooleanField;
    tblRacesMasterIsClaimingRace: TBooleanField;
    tblRacesMasterAgeSexRestriction: TStringField;
    tblRacesMasterPurse: TFloatField;
    tblRacesMasterClaimingPrice: TFloatField;
    tblRacesMasterSimulcastTrkCode: TStringField;
    tblRacesMasterSimulcastRaceNbr: TSmallintField;
    tblRacesMasterRaceAutoInc: TAutoIncField;
    tblRacesMasterTimeDiff: TTimeField;
    tblRacesMasterIsDDRace: TBooleanField;
    tblRacesMasterDDRaceNbr: TStringField;
    tblRacesMasterIsPk3Race: TBooleanField;
    tblRacesMasterPk3RaceNbr: TStringField;
    tblRacesMasterIsPk4Race: TBooleanField;
    tblRacesMasterPk4RaceNbr: TSmallintField;
    tblRacesMasterIsPk6Race: TBooleanField;
    tblRacesMasterPK6RaceNbr: TSmallintField;
    tblRacesMasterIsTriRace: TBooleanField;
    tblRacesMasterIsSuperRace: TBooleanField;
    tblRacesMasterIsQuiRace: TBooleanField;
    tblRacesMasterIsExaRace: TBooleanField;
    tblRacesMasterNbrTriKey: TIntegerField;
    tblRacesMasterIsPk3Leg1: TBooleanField;
    tblRacesMasterIsPk4Leg1: TBooleanField;
    tblRacesMasterIsPk6Leg1: TBooleanField;
    tblRacesMasterIsPk9Leg1: TBooleanField;
    tblRacesMasterIsDDLeg1: TBooleanField;
    tblRacesMasterTotalPk3Choices: TSmallintField;
    tblRacesMasterPk3KeyType: TSmallintField;
    tblRacesMasterPk3Selected: TBooleanField;
    tblRacesMasterTotalTriChoices: TSmallintField;
    tblRacesMasterTotalSuperChoices: TSmallintField;
    tblRacesMasterTotalDDChoices: TSmallintField;
    tblRacesMasterTopLastSpeed: TSmallintField;
    tblRacesMasterTopBackSpeed: TSmallintField;
    tblRacesMasterTopLastClass: TFloatField;
    tblRacesMasterAltWager1: TStringField;
    tblRacesMasterAltWager2: TStringField;
    tblRacesMasterAltWager3: TStringField;
    tblRacesMasterAltWager4: TStringField;
    tblRacesMasterAltWager5: TStringField;
    tblRacesMasterAltWager6: TStringField;
    tblRacesMasterWager1: TStringField;
    tblRacesMasterWager2: TStringField;
    tblRacesMasterWager3: TStringField;
    tblRacesMasterWager4: TStringField;
    tblRacesMasterWager5: TStringField;
    tblRacesMasterWager6: TStringField;
    tblRacesMasterWagerFinalOrder: TStringField;
    tblRacesMasterWagerSheetOrder: TStringField;
    tblRacesMasterTodaysWagerOrder: TStringField;
    tblRacesMasterTri: TStringField;
    tblRacesMasterDD: TStringField;
    tblRacesMasterSuper: TStringField;
    tblRacesMasterExacta: TStringField;
    tblRacesMasterQuinella: TStringField;
    tblRacesMasterPick3: TStringField;
    tblRacesMasterPick4: TStringField;
    tblRacesMasterPick6: TStringField;
    tblRacesMasterIsPrintedOnValueSheet: TBooleanField;
    tblRacesMasterIsYoubetTrack: TBooleanField;
    tblRacesMasterWPSWagerAmt: TFloatField;
    tblRacesMasterSfcWagerAmt: TFloatField;
    tblRacesMasterTriWagerAmt: TFloatField;
    tblRacesMasterExaWagerAmt: TFloatField;
    tblRacesMasterQuiWagerAmt: TFloatField;
    tblRacesMasterDDWagerAmt: TFloatField;
    tblRacesMasterPk3WagerAmt: TFloatField;
    tblRacesMasterPk4WagerAmt: TFloatField;
    tblRacesMasterPk6WagerAmt: TFloatField;
    tblRacesMasterTopEarlyPace: TFloatField;
    tblRacesMasterTopMiddlePace: TFloatField;
    tblRacesMasterTopLatePace: TFloatField;
    tblRacesMasterTopEarlyPacePos: TFloatField;
    tblRacesMasterTopMiddlePacePos: TFloatField;
    tblRacesMasterTopLatePacePos: TFloatField;
    tblRacesMasterSecondEarlyPace: TFloatField;
    tblRacesMasterSecondMiddlePace: TFloatField;
    tblRacesMasterSecondLatePace: TFloatField;
    tblRacesMasterSecondEarlyPacePos: TFloatField;
    tblRacesMasterSecondMiddlePacePos: TFloatField;
    tblRacesMasterSecondLatePacePos: TFloatField;
    tblRacesMasterTopPower: TFloatField;
    tblRacesMasterSecondTopPower: TFloatField;
    tblRacesMasterThirdTopPower: TFloatField;
    tblRacesMasterFourthTopPower: TFloatField;
    tblRacesMasterMaxWPSBet: TFloatField;
    tblRacesMasterMaxGimmickBet: TFloatField;
    tblRacesMasterNbrStarters: TSmallintField;
    tblRacesMasterNbrDebutStarters: TSmallintField;
    tblRacesMasterNbrDebutTwoStarters: TSmallintField;
    tblRacesMasterNbrTurfDebutStarters: TSmallintField;
    tblRacesMasterNbrRouteDebutStarters: TSmallintField;
    tblRacesMasterNbrScratchedStarters: TSmallintField;
    tblRacesMasterNbrRunners: TSmallintField;
    tblRacesMasterOrigSurface: TStringField;
    tblRacesMasterIsPk9Place: TBooleanField;
    tblRacesMasterPk9RaceNbr: TSmallintField;
    tblRacesMasterRaceCondition1: TStringField;
    tblRacesMasterRaceCondition2: TStringField;
    tblRacesMasterRaceCondition3: TStringField;
    tblRacesMasterRaceCondition4: TStringField;
    tblRacesMasterRaceCondition5: TStringField;
    tblRacesMasterRaceCondition6: TStringField;
    tblRacesMasterBetLine: TStringField;
    tblRacesMasterRaceConditions: TStringField;
    tblRacesMasterTrkCond: TStringField;
    tblRacesMasterOrigDistanceDesc: TStringField;
    tblRacesMasterIsExactaMatched: TBooleanField;
    tblRacesMasterExactaNbrs: TStringField;
    tblRacesMasterExactaWager: TFloatField;
    tblRacesMasterExactaPayout: TFloatField;
    tblRacesMasterIsTrifectaMatched: TBooleanField;
    tblRacesMasterTrifectaNbrs: TStringField;
    tblRacesMasterTrifectaWager: TFloatField;
    tblRacesMasterTrifectaPayout: TFloatField;
    tblRacesMasterIsSuperfectaMatched: TBooleanField;
    tblRacesMasterSuperfectaNbrs: TStringField;
    tblRacesMasterSuperfectaWager: TFloatField;
    tblRacesMasterSuperfectaPayout: TFloatField;
    tblRacesMasterIsDailyDoubleMatchedFirstRace: TBooleanField;
    tblRacesMasterIsDailyDoubleMatchedLastRace: TBooleanField;
    tblRacesMasterDDFirstRace: TStringField;
    tblRacesMasterDDLastRace: TStringField;
    tblRacesMasterDailyDoubleNbrsFirstRace: TStringField;
    tblRacesMasterDailyDoubleNbrsLastRace: TStringField;
    tblRacesMasterDailyDoubleWagerFirstRace: TFloatField;
    tblRacesMasterDailyDoubleWagerLastRace: TFloatField;
    tblRacesMasterDailyDoublePayoutFirstRace: TFloatField;
    tblRacesMasterDailyDoublePayoutLastRace: TFloatField;
    tblRacesMasterIsQuinellaMatched: TBooleanField;
    tblRacesMasterQuinellaNbrs: TStringField;
    tblRacesMasterQuinellaWager: TFloatField;
    tblRacesMasterQuinellaPayout: TFloatField;
    tblRacesMasterIsPick3MatchedFirstRace: TBooleanField;
    tblRacesMasterIsPick3MatchedLastRace: TBooleanField;
    tblRacesMasterPick3FirstRace: TStringField;
    tblRacesMasterPick3LastRace: TStringField;
    tblRacesMasterPick3NbrsFirstRace: TStringField;
    tblRacesMasterPick3NbrsLastRace: TStringField;
    tblRacesMasterPick3WagerFirstRace: TFloatField;
    tblRacesMasterPick3WagerLastRace: TFloatField;
    tblRacesMasterPick3PayoutFirstRace: TFloatField;
    tblRacesMasterPick3PayoutLastRace: TFloatField;
    tblRacesMasterPick3NbrsLeg1: TStringField;
    tblRacesMasterPick3NbrsLeg2: TStringField;
    tblRacesMasterPick3NbrsLeg3: TStringField;
    tblRacesMasterIsPick4MatchedFirstRace: TBooleanField;
    tblRacesMasterIsPick4MatchedLastRace: TBooleanField;
    tblRacesMasterPick4FirstRace: TStringField;
    tblRacesMasterPick4LastRace: TStringField;
    tblRacesMasterPick4NbrsFirstRace: TStringField;
    tblRacesMasterPick4NbrsLastRace: TStringField;
    tblRacesMasterPick4WagerFirstRace: TFloatField;
    tblRacesMasterPick4WagerLastRace: TFloatField;
    tblRacesMasterPick4PayoutFirstRace: TFloatField;
    tblRacesMasterPick4PayoutLastRace: TFloatField;
    tblRacesMasterPick4NbrsLeg1: TStringField;
    tblRacesMasterPick4NbrsLeg2: TStringField;
    tblRacesMasterPick4NbrsLeg3: TStringField;
    tblRacesMasterPick4NbrsLeg4: TStringField;
    tblRacesMasterIsPick6MatchedFirstRace: TBooleanField;
    tblRacesMasterIsPick6MatchedLastRace: TBooleanField;
    tblRacesMasterPick6FirstRace: TStringField;
    tblRacesMasterPick6LastRace: TStringField;
    tblRacesMasterPick6NbrsFirstRace: TStringField;
    tblRacesMasterPick6NbrsLastRace: TStringField;
    tblRacesMasterPick6WagerFirstRace: TFloatField;
    tblRacesMasterPick6WagerLastRace: TFloatField;
    tblRacesMasterPick6PayoutFirstRace: TFloatField;
    tblRacesMasterPick6PayoutLastRace: TFloatField;
    tblRacesMasterIsWinMatched: TBooleanField;
    tblRacesMasterWinNbrs: TStringField;
    tblRacesMasterWinPayout: TFloatField;
    tblRacesMasterWinPlcPayout: TFloatField;
    tblRacesMasterWinShoPayout: TFloatField;
    tblRacesMasterIsPlcMatched: TBooleanField;
    tblRacesMasterPlcNbrs: TStringField;
    tblRacesMasterPlcPayout: TFloatField;
    tblRacesMasterPlcShoPayout: TFloatField;
    tblRacesMasterIsShoMatched: TBooleanField;
    tblRacesMasterShoNbrs: TStringField;
    tblRacesMasterShoPayout: TFloatField;
    tblRacesMasterRaceShape: TStringField;
    tblRacesMasterPostTimes: TStringField;
    tblRacesMasterIs10CentSuperfectaRace: TBooleanField;
    tblRacesMasterIs50CentTrifectaRace: TBooleanField;
    tblRacesMasterIs50CentPk3Race: TBooleanField;
    tblRacesMasterIs50CentPk4Race: TBooleanField;
    tblRacesMasterET: TStringField;
    tblRacesMasterMT: TStringField;
    tblRacesMasterPT: TStringField;
    tblRacesMasterIsWagerSheetSelected: TBooleanField;
    tblRacesMasterValue: TStringField;
    tblRacesMasterIsPTCTrack: TBooleanField;
    tblRacesMasterIsTwinSpiresTrack: TBooleanField;
    tblRacesMasterTodaysAltWagerWinPct: TFloatField;
    tblRacesMasterTodaysAltWagerWinPctRank: TSmallintField;
    tblRacesMasterMudSheetOrder: TStringField;
    tblRacesMasterTurfSheetOrder: TStringField;
    tblRacesMasterMaidenSheetOrder: TStringField;
    tblRacesMasterDistanceSheetOrder: TStringField;
    tblRacesMasterAWSheetOrder: TStringField;
    tblRacesMasterTrainerSheetOrder: TStringField;
    tblRacesMasterJockeySheetOrder: TStringField;
    tblRacesMasterOwnerSheetOrder: TStringField;
    tblRacesMasterTrainerJockeySheetOrder: TStringField;
    tblRacesMasterErlPaceSheetOrder: TStringField;
    tblRacesMasterMidPaceSheetOrder: TStringField;
    tblRacesMasterLatePaceSheetOrder: TStringField;
    tblRacesMasterErlPacePosSheetOrder: TStringField;
    tblRacesMasterMidPacePosSheetOrder: TStringField;
    tblRacesMasterLatePacePosSheetOrder: TStringField;
    tblRacesMasterPacificTime: TStringField;
    tblRacesMasterPowerGapOrder: TStringField;
    tblRacesMasterErlPaceGapOrder: TStringField;
    tblRacesMasterMidPaceGapOrder: TStringField;
    tblRacesMasterLatePaceGapOrder: TStringField;
    tblRacesMasterErlPacePosGapOrder: TStringField;
    tblRacesMasterMidPacePosGapOrder: TStringField;
    tblRacesMasterLatePacePosGapOrder: TStringField;
    tblRacesMasterEarlyPacePar: TIntegerField;
    tblRacesMasterMiddlePacePar: TIntegerField;
    tblRacesMasterLatePacePar: TIntegerField;
    tblRacesMasterSpeedPacePar: TIntegerField;
    tblRacesLoopTrkCode: TStringField;
    tblRacesLoopRaceDate: TDateField;
    tblRacesLoopRangeRaceDate: TDateField;
    tblRacesLoopRaceNbr: TSmallintField;
    tblRacesLoopEstTimeOfRace: TTimeField;
    tblRacesLoopEstTimeOfFirstRace: TTimeField;
    tblRacesLoopLocalTimeOfRace: TTimeField;
    tblRacesLoopCT: TStringField;
    tblRacesLoopSurface: TStringField;
    tblRacesLoopActualSurface: TStringField;
    tblRacesLoopAltSurface: TStringField;
    tblRacesLoopDistanceInFeet: TSmallintField;
    tblRacesLoopDistanceInYards: TSmallintField;
    tblRacesLoopDistanceInFurlongs: TFloatField;
    tblRacesLoopDistanceDesc: TStringField;
    tblRacesLoopRaceType: TStringField;
    tblRacesLoopTypeOfRace: TStringField;
    tblRacesLoopRaceTypeDesc: TStringField;
    tblRacesLoopRaceDesc: TStringField;
    tblRacesLoopRaceCondition: TMemoField;
    tblRacesLoopIsTurfRace: TBooleanField;
    tblRacesLoopIsRouteRace: TBooleanField;
    tblRacesLoopIsMaidenSpecialRace: TBooleanField;
    tblRacesLoopIsMaidenClaimingRace: TBooleanField;
    tblRacesLoopIsMaidenOrTurfRace: TBooleanField;
    tblRacesLoopIsTwoYearOldRace: TBooleanField;
    tblRacesLoopIsClaimingRace: TBooleanField;
    tblRacesLoopAgeSexRestriction: TStringField;
    tblRacesLoopPurse: TFloatField;
    tblRacesLoopClaimingPrice: TFloatField;
    tblRacesLoopSimulcastTrkCode: TStringField;
    tblRacesLoopSimulcastRaceNbr: TSmallintField;
    tblRacesLoopRaceAutoInc: TAutoIncField;
    tblRacesLoopTimeDiff: TTimeField;
    tblRacesLoopIsDDRace: TBooleanField;
    tblRacesLoopDDRaceNbr: TStringField;
    tblRacesLoopIsPk3Race: TBooleanField;
    tblRacesLoopPk3RaceNbr: TStringField;
    tblRacesLoopIsPk4Race: TBooleanField;
    tblRacesLoopPk4RaceNbr: TSmallintField;
    tblRacesLoopIsPk6Race: TBooleanField;
    tblRacesLoopPK6RaceNbr: TSmallintField;
    tblRacesLoopIsTriRace: TBooleanField;
    tblRacesLoopIsSuperRace: TBooleanField;
    tblRacesLoopIsQuiRace: TBooleanField;
    tblRacesLoopIsExaRace: TBooleanField;
    tblRacesLoopNbrTriKey: TIntegerField;
    tblRacesLoopIsPk3Leg1: TBooleanField;
    tblRacesLoopIsPk4Leg1: TBooleanField;
    tblRacesLoopIsPk6Leg1: TBooleanField;
    tblRacesLoopIsPk9Leg1: TBooleanField;
    tblRacesLoopIsDDLeg1: TBooleanField;
    tblRacesLoopTotalPk3Choices: TSmallintField;
    tblRacesLoopPk3KeyType: TSmallintField;
    tblRacesLoopPk3Selected: TBooleanField;
    tblRacesLoopTotalTriChoices: TSmallintField;
    tblRacesLoopTotalSuperChoices: TSmallintField;
    tblRacesLoopTotalDDChoices: TSmallintField;
    tblRacesLoopTopLastSpeed: TSmallintField;
    tblRacesLoopTopBackSpeed: TSmallintField;
    tblRacesLoopTopLastClass: TFloatField;
    tblRacesLoopAltWager1: TStringField;
    tblRacesLoopAltWager2: TStringField;
    tblRacesLoopAltWager3: TStringField;
    tblRacesLoopAltWager4: TStringField;
    tblRacesLoopAltWager5: TStringField;
    tblRacesLoopAltWager6: TStringField;
    tblRacesLoopWager1: TStringField;
    tblRacesLoopWager2: TStringField;
    tblRacesLoopWager3: TStringField;
    tblRacesLoopWager4: TStringField;
    tblRacesLoopWager5: TStringField;
    tblRacesLoopWager6: TStringField;
    tblRacesLoopWagerFinalOrder: TStringField;
    tblRacesLoopWagerSheetOrder: TStringField;
    tblRacesLoopTodaysWagerOrder: TStringField;
    tblRacesLoopTri: TStringField;
    tblRacesLoopDD: TStringField;
    tblRacesLoopSuper: TStringField;
    tblRacesLoopExacta: TStringField;
    tblRacesLoopQuinella: TStringField;
    tblRacesLoopPick3: TStringField;
    tblRacesLoopPick4: TStringField;
    tblRacesLoopPick6: TStringField;
    tblRacesLoopIsPrintedOnValueSheet: TBooleanField;
    tblRacesLoopIsYoubetTrack: TBooleanField;
    tblRacesLoopWPSWagerAmt: TFloatField;
    tblRacesLoopSfcWagerAmt: TFloatField;
    tblRacesLoopTriWagerAmt: TFloatField;
    tblRacesLoopExaWagerAmt: TFloatField;
    tblRacesLoopQuiWagerAmt: TFloatField;
    tblRacesLoopDDWagerAmt: TFloatField;
    tblRacesLoopPk3WagerAmt: TFloatField;
    tblRacesLoopPk4WagerAmt: TFloatField;
    tblRacesLoopPk6WagerAmt: TFloatField;
    tblRacesLoopTopEarlyPace: TFloatField;
    tblRacesLoopTopMiddlePace: TFloatField;
    tblRacesLoopTopLatePace: TFloatField;
    tblRacesLoopTopEarlyPacePos: TFloatField;
    tblRacesLoopTopMiddlePacePos: TFloatField;
    tblRacesLoopTopLatePacePos: TFloatField;
    tblRacesLoopSecondEarlyPace: TFloatField;
    tblRacesLoopSecondMiddlePace: TFloatField;
    tblRacesLoopSecondLatePace: TFloatField;
    tblRacesLoopSecondEarlyPacePos: TFloatField;
    tblRacesLoopSecondMiddlePacePos: TFloatField;
    tblRacesLoopSecondLatePacePos: TFloatField;
    tblRacesLoopTopPower: TFloatField;
    tblRacesLoopSecondTopPower: TFloatField;
    tblRacesLoopThirdTopPower: TFloatField;
    tblRacesLoopFourthTopPower: TFloatField;
    tblRacesLoopMaxWPSBet: TFloatField;
    tblRacesLoopMaxGimmickBet: TFloatField;
    tblRacesLoopNbrStarters: TSmallintField;
    tblRacesLoopNbrDebutStarters: TSmallintField;
    tblRacesLoopNbrDebutTwoStarters: TSmallintField;
    tblRacesLoopNbrTurfDebutStarters: TSmallintField;
    tblRacesLoopNbrRouteDebutStarters: TSmallintField;
    tblRacesLoopNbrScratchedStarters: TSmallintField;
    tblRacesLoopNbrRunners: TSmallintField;
    tblRacesLoopOrigSurface: TStringField;
    tblRacesLoopIsPk9Place: TBooleanField;
    tblRacesLoopPk9RaceNbr: TSmallintField;
    tblRacesLoopRaceCondition1: TStringField;
    tblRacesLoopRaceCondition2: TStringField;
    tblRacesLoopRaceCondition3: TStringField;
    tblRacesLoopRaceCondition4: TStringField;
    tblRacesLoopRaceCondition5: TStringField;
    tblRacesLoopRaceCondition6: TStringField;
    tblRacesLoopBetLine: TStringField;
    tblRacesLoopRaceConditions: TStringField;
    tblRacesLoopTrkCond: TStringField;
    tblRacesLoopOrigDistanceDesc: TStringField;
    tblRacesLoopIsExactaMatched: TBooleanField;
    tblRacesLoopExactaNbrs: TStringField;
    tblRacesLoopExactaWager: TFloatField;
    tblRacesLoopExactaPayout: TFloatField;
    tblRacesLoopIsTrifectaMatched: TBooleanField;
    tblRacesLoopTrifectaNbrs: TStringField;
    tblRacesLoopTrifectaWager: TFloatField;
    tblRacesLoopTrifectaPayout: TFloatField;
    tblRacesLoopIsSuperfectaMatched: TBooleanField;
    tblRacesLoopSuperfectaNbrs: TStringField;
    tblRacesLoopSuperfectaWager: TFloatField;
    tblRacesLoopSuperfectaPayout: TFloatField;
    tblRacesLoopIsDailyDoubleMatchedFirstRace: TBooleanField;
    tblRacesLoopIsDailyDoubleMatchedLastRace: TBooleanField;
    tblRacesLoopDDFirstRace: TStringField;
    tblRacesLoopDDLastRace: TStringField;
    tblRacesLoopDailyDoubleNbrsFirstRace: TStringField;
    tblRacesLoopDailyDoubleNbrsLastRace: TStringField;
    tblRacesLoopDailyDoubleWagerFirstRace: TFloatField;
    tblRacesLoopDailyDoubleWagerLastRace: TFloatField;
    tblRacesLoopDailyDoublePayoutFirstRace: TFloatField;
    tblRacesLoopDailyDoublePayoutLastRace: TFloatField;
    tblRacesLoopIsQuinellaMatched: TBooleanField;
    tblRacesLoopQuinellaNbrs: TStringField;
    tblRacesLoopQuinellaWager: TFloatField;
    tblRacesLoopQuinellaPayout: TFloatField;
    tblRacesLoopIsPick3MatchedFirstRace: TBooleanField;
    tblRacesLoopIsPick3MatchedLastRace: TBooleanField;
    tblRacesLoopPick3FirstRace: TStringField;
    tblRacesLoopPick3LastRace: TStringField;
    tblRacesLoopPick3NbrsFirstRace: TStringField;
    tblRacesLoopPick3NbrsLastRace: TStringField;
    tblRacesLoopPick3WagerFirstRace: TFloatField;
    tblRacesLoopPick3WagerLastRace: TFloatField;
    tblRacesLoopPick3PayoutFirstRace: TFloatField;
    tblRacesLoopPick3PayoutLastRace: TFloatField;
    tblRacesLoopPick3NbrsLeg1: TStringField;
    tblRacesLoopPick3NbrsLeg2: TStringField;
    tblRacesLoopPick3NbrsLeg3: TStringField;
    tblRacesLoopIsPick4MatchedFirstRace: TBooleanField;
    tblRacesLoopIsPick4MatchedLastRace: TBooleanField;
    tblRacesLoopPick4FirstRace: TStringField;
    tblRacesLoopPick4LastRace: TStringField;
    tblRacesLoopPick4NbrsFirstRace: TStringField;
    tblRacesLoopPick4NbrsLastRace: TStringField;
    tblRacesLoopPick4WagerFirstRace: TFloatField;
    tblRacesLoopPick4WagerLastRace: TFloatField;
    tblRacesLoopPick4PayoutFirstRace: TFloatField;
    tblRacesLoopPick4PayoutLastRace: TFloatField;
    tblRacesLoopPick4NbrsLeg1: TStringField;
    tblRacesLoopPick4NbrsLeg2: TStringField;
    tblRacesLoopPick4NbrsLeg3: TStringField;
    tblRacesLoopPick4NbrsLeg4: TStringField;
    tblRacesLoopIsPick6MatchedFirstRace: TBooleanField;
    tblRacesLoopIsPick6MatchedLastRace: TBooleanField;
    tblRacesLoopPick6FirstRace: TStringField;
    tblRacesLoopPick6LastRace: TStringField;
    tblRacesLoopPick6NbrsFirstRace: TStringField;
    tblRacesLoopPick6NbrsLastRace: TStringField;
    tblRacesLoopPick6WagerFirstRace: TFloatField;
    tblRacesLoopPick6WagerLastRace: TFloatField;
    tblRacesLoopPick6PayoutFirstRace: TFloatField;
    tblRacesLoopPick6PayoutLastRace: TFloatField;
    tblRacesLoopIsWinMatched: TBooleanField;
    tblRacesLoopWinNbrs: TStringField;
    tblRacesLoopWinPayout: TFloatField;
    tblRacesLoopWinPlcPayout: TFloatField;
    tblRacesLoopWinShoPayout: TFloatField;
    tblRacesLoopIsPlcMatched: TBooleanField;
    tblRacesLoopPlcNbrs: TStringField;
    tblRacesLoopPlcPayout: TFloatField;
    tblRacesLoopPlcShoPayout: TFloatField;
    tblRacesLoopIsShoMatched: TBooleanField;
    tblRacesLoopShoNbrs: TStringField;
    tblRacesLoopShoPayout: TFloatField;
    tblRacesLoopRaceShape: TStringField;
    tblRacesLoopPostTimes: TStringField;
    tblRacesLoopIs10CentSuperfectaRace: TBooleanField;
    tblRacesLoopIs50CentTrifectaRace: TBooleanField;
    tblRacesLoopIs50CentPk3Race: TBooleanField;
    tblRacesLoopIs50CentPk4Race: TBooleanField;
    tblRacesLoopET: TStringField;
    tblRacesLoopMT: TStringField;
    tblRacesLoopPT: TStringField;
    tblRacesLoopIsWagerSheetSelected: TBooleanField;
    tblRacesLoopValue: TStringField;
    tblRacesLoopIsPTCTrack: TBooleanField;
    tblRacesLoopIsTwinSpiresTrack: TBooleanField;
    tblRacesLoopTodaysAltWagerWinPct: TFloatField;
    tblRacesLoopTodaysAltWagerWinPctRank: TSmallintField;
    tblRacesLoopMudSheetOrder: TStringField;
    tblRacesLoopTurfSheetOrder: TStringField;
    tblRacesLoopMaidenSheetOrder: TStringField;
    tblRacesLoopDistanceSheetOrder: TStringField;
    tblRacesLoopAWSheetOrder: TStringField;
    tblRacesLoopTrainerSheetOrder: TStringField;
    tblRacesLoopJockeySheetOrder: TStringField;
    tblRacesLoopOwnerSheetOrder: TStringField;
    tblRacesLoopTrainerJockeySheetOrder: TStringField;
    tblRacesLoopErlPaceSheetOrder: TStringField;
    tblRacesLoopMidPaceSheetOrder: TStringField;
    tblRacesLoopLatePaceSheetOrder: TStringField;
    tblRacesLoopErlPacePosSheetOrder: TStringField;
    tblRacesLoopMidPacePosSheetOrder: TStringField;
    tblRacesLoopLatePacePosSheetOrder: TStringField;
    tblRacesLoopPacificTime: TStringField;
    tblRacesLoopPowerGapOrder: TStringField;
    tblRacesLoopErlPaceGapOrder: TStringField;
    tblRacesLoopMidPaceGapOrder: TStringField;
    tblRacesLoopLatePaceGapOrder: TStringField;
    tblRacesLoopErlPacePosGapOrder: TStringField;
    tblRacesLoopMidPacePosGapOrder: TStringField;
    tblRacesLoopLatePacePosGapOrder: TStringField;
    tblRacesLoopEarlyPacePar: TIntegerField;
    tblRacesLoopMiddlePacePar: TIntegerField;
    tblRacesLoopLatePacePar: TIntegerField;
    tblRacesLoopSpeedPacePar: TIntegerField;
    ppDBText45: TppDBText;
    ppLabel3: TppLabel;
    ppDBText17: TppDBText;
    ppLabel32: TppLabel;
    ppLabel66: TppLabel;
    ppDBText46: TppDBText;
    ppLabel68: TppLabel;
    ppDBText47: TppDBText;
    ppLabel69: TppLabel;
      procedure FormCreate(Sender: TObject);
      procedure FormDestroy(Sender: TObject);
      procedure btnCreatePdfClick(Sender: TObject);
      procedure FormActivate(Sender: TObject);
      procedure timCloseFormCheckTimer(Sender: TObject);
      procedure plRacesReportNext(Sender: TObject);
      procedure plEntriesNext(Sender: TObject);
      procedure plEntriesRecordPositionChange(Sender: TObject);
      procedure plEntriesTraversal(Sender: TObject);
      procedure dbHospitalReportBeforeConnect(Sender: TObject);
    procedure plRacesReportTraversal(Sender: TObject);
    procedure dsEntriesDataChange(Sender: TObject; Field: TField);
   private
      { Private declarations }
      bCreateReportsActive: boolean;
   public
      { Public declarations }
   end;

var
   HospitalReportForm: THospitalReportForm;

implementation

uses UnitCommonCode, StrMan;

{$R *.DFM}

//******************* TTipSheetReportForm.FormCreate *************************

procedure THospitalReportForm.FormCreate(Sender: TObject);
begin

   hLog.LogFileName := LOG_PATH + LOG_FILENAME;
   with dbHospitalReport do begin
      Close;
      Directory := DATA_PATH;
      Open;
   end;

end;

//******************* TTipSheetReportForm.FormDestroy *************************

procedure THospitalReportForm.FormDestroy(Sender: TObject);
begin

   hLog.LogFileName := LOG_PATH + LOG_FILENAME;
   tblRacesLoop.Active := False;
   tblRacesMaster.Active := False;

   tblEntries.Active := False;
   //   tblATrainerList.Active := False;

   with dbHospitalReport do begin
      Close;
   end;

end;

//******************* TTipSheetReportForm.btnCreatePdfClick *************************

procedure THospitalReportForm.btnCreatePdfClick(Sender: TObject);
var
   sTrkCode: string;
   sPrevTrkCode: string;
   wYear: Word;
   wMonth: Word;
   wDay: Word;
   sFileName: string;
   iAttributes: integer;
   tsFile: TSearchRec;

begin


   tblRacesLoop.Active := False;
   tblRacesMaster.Active := False;
   tblEntries.Active := False;

   prgBar.Position := 0;
   pnlPrgBar.Visible := False;
   staBar.SimpleText := '';
   bCreateReportsActive := False;

   try

      sPrevTrkCode := '';
      tblRacesLoop.Active := True;

      tblRacesMaster.Active := False;
      tblEntries.Active := False;

      //      tblATrainerList.Active := True;

      prgBar.Max := tblRacesLoop.RecordCount;
      prgBar.Position := 0;
      pnlPrgBar.Visible := True;

      tblRacesLoop.First();
      while not tblRacesLoop.Eof do begin
         prgBar.Position := prgBar.Position + 1;
         Application.ProcessMessages();
         sTrkCode := tblRacesLoop.FieldByName('TrkCode').AsString;
         if sPrevTrkCode <> tblRacesLoop.FieldByName('TrkCode').AsString then begin
            sPrevTrkCode := tblRacesLoop.FieldByName('TrkCode').AsString;

            tblRacesMaster.Active := True;
            tblRacesMaster.Filtered := False;
            tblRacesMaster.Filter := 'TrkCode=''' + tblRacesLoop.FieldByName('TrkCode').AsString + '''';
            tblRacesMaster.Filtered := True;

            DecodeDate(tblRacesLoop.FieldByName('RaceDate').AsDateTime, wYear, wMonth, wDay);
            sFileName := tblRacesLoop.FieldByName('TrkCode').AsString + sm.Str(wMonth, 2) + sm.Str(wDay, 2) + '.pdf';

            with ppHospitalReport do begin
               AllowPrintToFile := True;
               ShowPrintDialog := False;
               ShowCancelDialog := False;
               DeviceType := 'PDFFile';
               TextFileName := PDF_HOSPITAL_REPORT_PATH + sFileName;
               staBar.SimpleText := 'Processing ' + TextFileName;
               Application.ProcessMessages;
               ppHospitalReport.Print;
            end;

            iAttributes := faAnyFile;
            if (FindFirst(ppHospitalReport.TextFileName, iAttributes, tsFile) = 0) then begin
               if (tsFile.Size < MIN_REPORT_FILE_SIZE) then begin
                  DeleteFile(ppHospitalReport.TextFileName);
                  Application.ProcessMessages();
               end;
            end;
            FindClose(tsFile);

         end;
         tblRacesLoop.Next();
      end;

   except
      tblRacesLoop.Active := False;
      tblRacesMaster.Active := False;
      tblEntries.Active := False;
      //      tblATrainerList.Active := False;

      prgBar.Position := 0;
      pnlPrgBar.Visible := False;
      staBar.SimpleText := '';
      bCreateReportsActive := False;
   end;

   tblRacesLoop.Active := False;
   tblRacesMaster.Active := False;
   tblEntries.Active := False;

   prgBar.Position := 0;
   pnlPrgBar.Visible := False;
   staBar.SimpleText := '';
   bCreateReportsActive := False;



end;

procedure THospitalReportForm.FormActivate(Sender: TObject);
begin

   bCreateReportsActive := True;
   btnCreatePdfClick(Sender);

end;

procedure THospitalReportForm.timCloseFormCheckTimer(Sender: TObject);
begin

   if not bCreateReportsActive then begin
      Close;
   end;

end;

procedure THospitalReportForm.plRacesReportNext(Sender: TObject);
begin
   Application.ProcessMessages;
end;

procedure THospitalReportForm.plEntriesNext(Sender: TObject);
begin
   Application.ProcessMessages;
end;

procedure THospitalReportForm.plEntriesRecordPositionChange(Sender: TObject);
begin
   Application.ProcessMessages;
end;

procedure THospitalReportForm.plEntriesTraversal(Sender: TObject);
begin
   Application.ProcessMessages;
end;

procedure THospitalReportForm.dbHospitalReportBeforeConnect(
   Sender: TObject);
begin
   dbHospitalReport.Directory := DATA_PATH;

end;

procedure THospitalReportForm.plRacesReportTraversal(Sender: TObject);
begin
         Application.ProcessMessages();
         Application.ProcessMessages();

end;

procedure THospitalReportForm.dsEntriesDataChange(Sender: TObject;
  Field: TField);
begin
         Application.ProcessMessages();

end;

end.

